In [1]:
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
from pydantic_ai import Agent
from typing import List, Any

In [3]:
import json

with open("my_chunks_sections.json", "r", encoding="utf-8") as f:
    my_chunks_sections = json.load(f)

len(my_chunks_sections)
my_chunks_sections[0]

{'filename': 'binance-spot-api-docs-master/CHANGELOG_CN.md',
 'section': '## REST API\n\n- `POST /api/v3/userDataStream`\n- `PUT /api/v3/userDataStream`\n- `DELETE /api/v3/userDataStream`'}

In [4]:
from minsearch import Index, VectorSearch
from sentence_transformers import SentenceTransformer
from tqdm.auto import tqdm
import numpy as np

In [5]:
def normalize_binance_chunks(chunks):
    normalized = []

    for i, doc in enumerate(chunks):
        item = dict(doc)

        chunk_text = (
            item.get("chunk")
            or item.get("content")
            or item.get("text")
            or ""
        )

        title = item.get("title", "") or item.get("heading", "") or ""
        filename = (
            item.get("filename", "")
            or item.get("file_path", "")
            or item.get("path", "")
            or item.get("source", "")
            or ""
        )
        section = item.get("section", "") or item.get("header", "") or ""
        description = item.get("description", "") or ""

        normalized.append({
            "id": item.get("id", str(i)),
            "chunk": chunk_text,
            "title": title,
            "filename": filename,
            "section": section,
            "description": description,
            "url": item.get("url", ""),
            "raw": item
        })

    return normalized

In [6]:
binance_docs = []

for i, d in enumerate(my_chunks_sections):
    binance_docs.append({
        "id": str(i),
        "chunk": d.get("chunk", "") if isinstance(d, dict) else "",
        "title": d.get("title", "") if isinstance(d, dict) else "",
        "description": d.get("description", "") if isinstance(d, dict) else "",
        "filename": d.get("filename", "") if isinstance(d, dict) else "",
        "section": d.get("section", "") if isinstance(d, dict) else ""
    })

len(binance_docs)

367

In [7]:
binance_docs[0]

{'id': '0',
 'chunk': '',
 'title': '',
 'description': '',
 'filename': 'binance-spot-api-docs-master/CHANGELOG_CN.md',
 'section': '## REST API\n\n- `POST /api/v3/userDataStream`\n- `PUT /api/v3/userDataStream`\n- `DELETE /api/v3/userDataStream`'}

In [8]:
text_index = Index(
    text_fields=["chunk", "title", "description", "filename", "section"],
    keyword_fields=[]
)

text_index.fit(binance_docs)

In [9]:
query = "How do I sign a Binance Spot API request?"
text_results = text_index.search(query, num_results=5)
text_results

[{'id': '170',
  'chunk': '',
  'title': '',
  'description': '',
  'filename': 'binance-spot-api-docs-master/fix-api.md',
  'section': '## General API Information\n\n* FIX connections require TLS encryption. Please either use native TCP+TLS connection or set up a local proxy such as [stunnel](https://www.stunnel.org/) to handle TLS encryption.\n* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)\n  * This does not always mean that the request failed in the Matching Engine.\n  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.\n* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.\n* To ensure uninterrupted connectivity, please make sure that your client sends **SNI (Server Name Indication)** during the TLS handshake and performs certificate validation against the intended hostname. <br>\nClients that do not send SNI may receive an unexpected certificate, which can result in TLS handshake or hostname verification failures.\n\n<details>\n<summary>Example implementations</summary>\n\n### NodeJS\nIf you are using Node.js and connecting via raw TLS sockets (`tls.connect()`), you must explicitly set the servername option. Please refer to the sample below:\n\n```javascript\n  const tls = require("tls");\n  const hostname = "fix-dc.binance.com"; //EXAMPLE\n\n  const options = {\n     host: hostname,\n     port: 9002,\n     servername: hostname                // enables SNI\n   };\n```\n\nNote that: NodeJS doesn\'t enable SNI by default for TLS (See [https://nodejs.org/api/tls.html#tlsconnectoptions-callback](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)). <br>\nIf you are using standard HTTPS libraries in Node.js (e.g., `https.request()`, `axios`, `fetch`), these typically set SNI automatically when connecting via a hostname/URL.\n\n### Other languages/custom TLS implementations\nWhen using custom TLS agents / TLS APIs, ensure you set the equivalent field (often named `server_hostname`, `hostname`, or `ServerName`) to the endpoint hostname so SNI is sent.\n</details>\n\n**FIX sessions only support Ed25519 keys.** </br>\n\nPlease refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)\non how to set up an Ed25519 key pair.\n\n### FIX API Order Entry sessions\n\n* Endpoint is: `tcp+tls://fix-oe.binance.com:9000`\n* Supports placing orders, canceling orders, and querying current limit usage.\n* Supports receiving all of the account\'s [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).\n* Only API keys with `FIX_API` are allowed to connect.\n* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).\n\n### FIX API Drop Copy sessions\n\n* Endpoint is: `tcp+tls://fix-dc.binance.com:9000`\n* Supports receiving all of the account\'s [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).\n* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.\n* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).\n* Data in Drop Copy sessions is delayed by 1 second.\n\n### FIX API Market Data sessions\n\n* Endpoint is: `tcp+tls://fix-md.binance.com:9000`\n* Supports market data streams and active instruments queries.\n* Does not support placing or canceling orders.\n* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.\n* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml).\n\n### FIX Connection Lifecycle\n\n* All FIX API sessions will remain open for as long as possible, on a best-effort basis.\n* There is no minimum connection time guarantee; a server can enter maintenance at any time.\n  * When a server enters maintenance, a [News `<B>`](#news) message will be sent to clients **every 10 seconds for 10 minutes**, prompting clients to reconnect. Upon receiving this message, a client is expected to establish a new session and close the old one. If the client does not close the old session within the time frame, the server will proceed to log it out and close the session.\n* After connecting, the client must send a Logon `<A>` request. For more information please refer to [How to sign a Logon request](#signaturecomputation).\n* The client should send a Logout `<5>` message to close the session before disconnecting. Failure to send the logout message will result in the session’s `SenderCompID (49)` being unusable for new session establishment for a duration of 2x the `HeartInt (108)` interval.\n* The system allows negotiation of the `HeartInt (108)` value during the logon process. Accepted values range between 5 and 60 seconds.\n  * If the server has not sent any messages within a `HeartInt (108)` interval, a [HeartBeat `<0>`](#heartbeat)  will be sent.\n  * If the server has not received any messages within a `HeartInt (108)` interval, a [TestRequest `<1>`](#testrequest) will be sent. If the server does not receive a HeartBeat `<0>` containing the expected `TestReqID (112)` from the client within `HeartInt (108)` seconds, the server will send a Logout `<5>` message and close the connection.\n  * If the client has not received any messages within a `HeartInt (108)` interval, the client is responsible for sending a TestRequest `<1>` to ensure the connection is healthy. Upon receiving such a TestRequest `<1>`, the server will respond with a Heartbeat `<0>` containing the expected `TestReqID (112)`. If the client does not receive the server’s response within a `HeartInt (108)` interval, the client should close the session and connection and establish new ones.\n\n### API Key Permissions\n\nTo access the FIX API order entry sessions, your API key must be configured with the `FIX_API` permission.\n\nTo access the FIX Drop Copy sessions, your API key must be configured with either `FIX_API_READ_ONLY` or `FIX_API` permission.\n\nTo access the FIX Market Data sessions, your API key must be configured with either `FIX_API` or `FIX_API_READ_ONLY` permission.\n\n**FIX sessions only support Ed25519 keys.**\n\nPlease refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)\non how to set up an Ed25519 key pair.\n\n<a id="orderedmode"></a>\n\n### On message processing order\n\nThe `MessageHandling (25035)` field required in the initial [Logon`<A>`](#logon-request) message controls whether messages from the client may be reordered before they are processed by the Matching Engine.\n\n| Mode            | Description                                                                                |\n|-----------------|--------------------------------------------------------------------------------------------|\n| `UNORDERED(1)`  | Messages from the client are allowed to be sent to the matching engine in any order.       |\n| `SEQUENTIAL(2)` | Messages from the client are always sent to the matching engine in `MsgSeqNum (34)` order. |\n\nIn all modes, the client\'s `MsgSeqNum (34)` must increase monotonically, with each subsequent message having a sequence number that is exactly 1 greater than the previous message.\n\n> [!TIP]\n> `UNORDERED(1)` should offer better performance when there are multiple messages in flight from the client to the server.\n\n<a id="responsemode"></a>\n\n### Response Mode\n\nBy default, all concurrent order entry sessions receive all of the account\'s\nsuccessful [ExecutionReport`<8>`](#executionreport) and [ListStatus`<N>`](#liststatus) messages,\nincluding those in response to orders placed from other FIX sessions and via non-FIX APIs.\n\nUse the `ResponseMode (25036)` field in the initial [Logon`<A>`](#logon-request) message\nto change this behavior.\n\n- `EVERYTHING(1)`: The default mode.\n- `ONLY_ACKS(2)`: Receive only ACK messages whether operation succeeded or failed. Disables ExecutionReport push.\n\n<a id="timingsecurity"></a>\n\n### Timing Security\n\n* All requests require a `SendingTime(52)` field which should be the current timestamp.\n* An additional optional field, `RecvWindow(25000)`, specifies for how long the request stays valid in milliseconds.\n  * `RecvWindow(25000)` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.\n  * If `RecvWindow(25000)` is not specified, it defaults to 5000 milliseconds only for the Logon`<A>` request. For other requests if unset, the RecvWindow check is not executed.\n  * Maximum `RecvWindow(25000)` is 60000 milliseconds.\n* Request processing logic is as follows:\n\n```javascript\nserverTime = getCurrentTime()\nif (SendingTime < (serverTime + 1 second) && (serverTime - SendingTime) <= RecvWindow) {\n  // begin processing request\n  serverTime = getCurrentTime()\n  if (serverTime - SendingTime) <= RecvWindow {\n    // forward request to Matching Engine\n  } else {\n    // reject request\n  }\n  // finish processing request\n} else {\n  // reject request\n}\n```\n\n<a id="signaturecomputation"></a>\n\n### How to sign Logon `<A>` request\n\nThe [Logon`<A>`](#logon-main) message authenticates your connection to the FIX API.\nThis must be the first message sent by the client.\n\n* The `Username (553)` field is required to contain the API key.\n* The `RawData (96)` field is required to contain a valid signature made with the API key.\n\nThe signature payload is a text string constructed by concatenating the values of the following fields in this exact order,\nseparated by the SOH character:\n\n1. `MsgType (35)`\n2. `SenderCompId (49)`\n3. `TargetCompId (56)`\n4. `MsgSeqNum (34)`\n5. `SendingTime (52)`\n\n\nSign the payload using your private key.\nEncode the signature with **base64**.\nThe resulting text string is the value of the `RawData (96)` field.\n\nHere is a sample Python code implementing the signature algorithm:\n\n````python\nimport base64\n\nfrom cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey\nfrom cryptography.hazmat.primitives.serialization import load_pem_private_key\n\ndef logon_raw_data(private_key: Ed25519PrivateKey,\n                   sender_comp_id: str,\n                   target_comp_id: str,\n                   msg_seq_num: str,\n                   sending_time: str):\n    """\n    Computes the value of RawData (96) field in Logon<A> message.\n    """\n    payload = chr(1).join([\n        \'A\',\n        sender_comp_id,\n        target_comp_id,\n        msg_seq_num,\n        sending_time,\n    ])\n    signature = private_key.sign(payload.encode(\'ASCII\'))\n    return base64.b64encode(signature).decode(\'ASCII\')\n\n\nwith open(\'private_key.pem\', \'rb\') as f:\n    private_key = load_pem_private_key(data=f.read(),\n                                       password=None)\n\nraw_data = logon_raw_data(private_key,\n                          sender_comp_id=\'5JQmUOsm\',\n                          target_comp_id=\'SPOT\',\n                          msg_seq_num=\'1\',\n                          sending_time=\'20240612-08:52:21.613\')\n````\n\nThe values presented below can be used to validate the correctness of the signature computation implementation:\n\n| Field             | Value                   |\n|-------------------|-------------------------|\n| MsgType (35)      | `A`                     |\n| SenderCompID (49) | `EXAMPLE`               |\n| TargetCompID (56) | `SPOT`                  |\n| MsgSeqNum (34)    | `1`                     |\n| SendingTime (52)  | `20240627-11:17:25.223` |\n\nThe Ed25519 private key used in the example computation is shown below:\n\n> [!CAUTION]\n> The following secret key is provided solely for illustrative purposes. Do not use this key in any real-world application as it is not secure and may compromise your cryptographic implementation. Always generate your own unique and secure keys for actual use.\n\n```\n-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIIJEYWtGBrhACmb9Dvy+qa8WEf0lQOl1s4CLIAB9m89u\n-----END PRIVATE KEY-----\n```\n\nComputed signature:\n```\n4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==\n```\n\nResulting Logon `<A>` message:\n```\n8=FIX.4.4|9=247|35=A|34=1|49=EXAMPLE|52=20240627-11:17:25.223|56=SPOT|95=88|96=4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==|98=0|108=30|141=Y|553=sBRXrJx2DsOraMXOaUovEhgVRcjOvCtQwnWj8VxkOh1xqboS02SPGfKi2h8spZJb|25035=2|10=227|\n```'},
 {'id': '193',
  'chunk': '',
  'title': '',
  'description': '',
  'filename': 'binance-spot-api-docs-master/rest-api.md',
  'section': '## General endpoints\n\n### Test connectivity\n```\nGET /api/v3/ping\n```\nTest connectivity to the Rest API.\n\n**Weight:**\n1\n\n**Parameters:**\nNONE\n\n**Data Source:**\nMemory\n\n**Response:**\n```javascript\n{}\n```\n\n### Check server time\n```\nGET /api/v3/time\n```\nTest connectivity to the Rest API and get the current server time.\n\n**Weight:**\n1\n\n**Parameters:**\nNONE\n\n**Data Source:**\nMemory\n\n**Response:**\n```javascript\n{\n    "serverTime": 1499827319559\n}\n```\n\n<a id="exchangeInfo"></a>\n\n### Exchange information\n```\nGET /api/v3/exchangeInfo\n```\nCurrent exchange trading rules and symbol information\n\n**Weight:**\n20\n\n**Parameters:**\n\nName | Type | Mandatory | Description\n------------ | ------------ | ------------ | ------------\nsymbol |STRING| No| Example: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"\nsymbols |ARRAY OF STRING|No| Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbols=%5B%22BNBBTC%22,%22BTCUSDT%22%5D" <br/> or <br/> curl -g -X  GET \'https://api.binance.com/api/v3/exchangeInfo?symbols=["BTCUSDT","BNBBTC"]\'\npermissions |ENUM|No|Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=SPOT" <br/> or <br/> curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=%5B%22MARGIN%22%2C%22LEVERAGED%22%5D" <br/> or <br/> curl -g -X GET \'https://api.binance.com/api/v3/exchangeInfo?permissions=["MARGIN","LEVERAGED"]\' |\nshowPermissionSets|BOOLEAN|No|Controls whether the content of the `permissionSets` field is populated or not. Defaults to `true`\nsymbolStatus|ENUM|No|Filters for symbols that have this `tradingStatus`. Valid values: `TRADING`, `HALT`, `BREAK` <br> Cannot be used in combination with `symbols` or `symbol`.|\n\n**Notes:**\n* If the value provided to `symbol` or `symbols` do not exist, the endpoint will throw an error saying the symbol is invalid.\n* All parameters are optional.\n* `permissions` can support single or multiple values (e.g. `SPOT`, `["MARGIN","LEVERAGED"]`). This cannot be used in combination with `symbol` or `symbols`.\n* If `permissions` parameter not provided, all symbols that have either `SPOT`, `MARGIN`, or `LEVERAGED` permission will be exposed.\n  * To display symbols with any permission you need to specify them explicitly in `permissions`: (e.g. `["SPOT","MARGIN",...]`.). See [Account and Symbol Permissions](enums.md#account-and-symbol-permissions) for the full list.\n\n<a id="examples-of-symbol-permissions-interpretation-from-the-response"></a>\n\n**Examples of Symbol Permissions Interpretation from the Response:**\n\n* `[["A","B"]]` means you may place an order if your account has either permission "A" **or** permission "B".\n* `[["A"],["B"]]` means you can place an order if your account has permission "A" **and** permission "B".\n* `[["A"],["B","C"]]` means you can place an order if your account has permission "A" **and** permission "B" or permission "C". (Inclusive or is applied here, not exclusive or, so your account may have both permission "B" and permission "C".)\n\n**Data Source:**\nMemory\n\n**Response:**\n```javascript\n{\n    "timezone": "UTC",\n    "serverTime": 1565246363776,\n    "rateLimits": [\n        {\n            // These are defined in the `ENUM definitions` section under `Rate Limiters (rateLimitType)`.\n            // All limits are optional\n        }\n    ],\n    "exchangeFilters": [\n        // These are the defined filters in the `Filters` section.\n        // All filters are optional.\n    ],\n    "symbols": [\n        {\n            "symbol": "ETHBTC",\n            "status": "TRADING",\n            "baseAsset": "ETH",\n            "baseAssetPrecision": 8,\n            "quoteAsset": "BTC",\n            "quotePrecision": 8,     // will be removed in future api versions (v4+)\n            "quoteAssetPrecision": 8,\n            "baseCommissionPrecision": 8,\n            "quoteCommissionPrecision": 8,\n            "orderTypes": [\n                "LIMIT",\n                "LIMIT_MAKER",\n                "MARKET",\n                "STOP_LOSS",\n                "STOP_LOSS_LIMIT",\n                "TAKE_PROFIT",\n                "TAKE_PROFIT_LIMIT"\n            ],\n            "icebergAllowed": true,\n            "ocoAllowed": true,\n            "otoAllowed": true,\n            "opoAllowed": true,\n            "quoteOrderQtyMarketAllowed": true,\n            "allowTrailingStop": false,\n            "cancelReplaceAllowed": false,\n            "amendAllowed": false,\n            "pegInstructionsAllowed": true,\n            "isSpotTradingAllowed": true,\n            "isMarginTradingAllowed": true,\n            "filters": [\n                // These are defined in the Filters section.\n                // All filters are optional\n            ],\n            "permissions": [],\n            "permissionSets": [["SPOT", "MARGIN"]],\n            "defaultSelfTradePreventionMode": "NONE",\n            "allowedSelfTradePreventionModes": ["NONE"]\n        }\n    ],\n    // Optional field. Present only when SOR is available.\n    // https://github.com/binance/binance-spot-api-docs/blob/master/faqs/sor_faq.md\n    "sors": [\n        {\n            "baseAsset": "BTC",\n            "symbols": ["BTCUSDT", "BTCUSDC"]\n        }\n    ]\n}\n```\n\n### Query Execution Rules\n\n```\nGET /api/v3/executionRules\n```\n\n**Weight**\n\nParameter | Weight|\n---        | ---\n`symbol`  | 2\n`symbols` | 2 for each `symbol`, capped at a max of 40|\n`symbolStatus` |40|\nNone            |40|\n\n**Parameters:**\n\nName | Type | Mandatory | Description\n------------ | ------------ | ------------ | ------------\n`symbol`   | STRING| No      | Query for specified symbol\n`symbols`  | STRING | No     | Query for multiple symbols\n`symbolStatus` |ENUM| Query for all symbols with the specified status. Supported values: `TRADING`, `HALT`, `BREAK`\n\n\n**Note:** No combination of multiple parameters is allowed.\n\n**Data Source:** Memory\n\n**Response:**\n\n```javascript\n{\n    "symbolRules": [\n        {\n            "symbol": "BAZUSD",\n            "rules": [\n                {\n                    "ruleType": "PRICE_RANGE",\n                    "bidLimitMultUp": "1.0001",\n                    "bidLimitMultDown": "0.9999",\n                    "askLimitMultUp": "1.0001",\n                    "askLimitMultDown": "0.9999"\n                }\n            ]\n        }\n    ]\n}\n```'},
 {'id': '186',
  'chunk': '',
  'title': '',
  'description': '',
  'filename': 'binance-spot-api-docs-master/rest-api.md',

In [10]:
def preview_results(results, max_chars=300):
    for i, r in enumerate(results, 1):
        print(f"\nResult #{i}")
        print("title:      ", r.get("title", ""))
        print("section:    ", r.get("section", ""))
        print("filename:   ", r.get("filename", ""))
        print("chunk:      ", r.get("chunk", "")[:max_chars])
        print("-" * 80)

In [11]:
preview_results(text_results)

Result #1
title:
section:     ## General API Information

* FIX connections require TLS encryption. Please either use native TCP+TLS connection or set up a local proxy such as [stunnel](https://www.stunnel.org/) to handle TLS encryption.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* To ensure uninterrupted connectivity, please make sure that your client sends **SNI (Server Name Indication)** during the TLS handshake and performs certificate validation against the intended hostname. <br>
Clients that do not send SNI may receive an unexpected certificate, which can result in TLS handshake or hostname verification failures.

<details>
<summary>Example implementations</summary>

### NodeJS
If you are using Node.js and connecting via raw TLS sockets (`tls.connect()`), you must explicitly set the servername option. Please refer to the sample below:

```javascript
  const tls = require("tls");
  const hostname = "fix-dc.binance.com"; //EXAMPLE

  const options = {
     host: hostname,
     port: 9002,
     servername: hostname                // enables SNI
   };
```

Note that: NodeJS doesn't enable SNI by default for TLS (See [https://nodejs.org/api/tls.html#tlsconnectoptions-callback](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)). <br>
If you are using standard HTTPS libraries in Node.js (e.g., `https.request()`, `axios`, `fetch`), these typically set SNI automatically when connecting via a hostname/URL.

### Other languages/custom TLS implementations
When using custom TLS agents / TLS APIs, ensure you set the equivalent field (often named `server_hostname`, `hostname`, or `ServerName`) to the endpoint hostname so SNI is sent.
</details>

**FIX sessions only support Ed25519 keys.** </br>

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

### FIX API Order Entry sessions

* Endpoint is: `tcp+tls://fix-oe.binance.com:9000`
* Supports placing orders, canceling orders, and querying current limit usage.
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).

### FIX API Drop Copy sessions

* Endpoint is: `tcp+tls://fix-dc.binance.com:9000`
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).
* Data in Drop Copy sessions is delayed by 1 second.

### FIX API Market Data sessions

* Endpoint is: `tcp+tls://fix-md.binance.com:9000`
* Supports market data streams and active instruments queries.
* Does not support placing or canceling orders.
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml).

### FIX Connection Lifecycle

* All FIX API sessions will remain open for as long as possible, on a best-effort basis.
* There is no minimum connection time guarantee; a server can enter maintenance at any time.
  * When a server enters maintenance, a [News `<B>`](#news) message will be sent to clients **every 10 seconds for 10 minutes**, prompting clients to reconnect. Upon receiving this message, a client is expected to establish a new session and close the old one. If the client does not close the old session within the time frame, the server will proceed to log it out and close the session.
* After connecting, the client must send a Logon `<A>` request. For more information please refer to [How to sign a Logon request](#signaturecomputation).
* The client should send a Logout `<5>` message to close the session before disconnecting. Failure to send the logout message will result in the session’s `SenderCompID (49)` being unusable for new session establishment for a duration of 2x the `HeartInt (108)` interval.
* The system allows negotiation of the `HeartInt (108)` value during the logon process. Accepted values range between 5 and 60 seconds.
  * If the server has not sent any messages within a `HeartInt (108)` interval, a [HeartBeat `<0>`](#heartbeat)  will be sent.
  * If the server has not received any messages within a `HeartInt (108)` interval, a [TestRequest `<1>`](#testrequest) will be sent. If the server does not receive a HeartBeat `<0>` containing the expected `TestReqID (112)` from the client within `HeartInt (108)` seconds, the server will send a Logout `<5>` message and close the connection.
  * If the client has not received any messages within a `HeartInt (108)` interval, the client is responsible for sending a TestRequest `<1>` to ensure the connection is healthy. Upon receiving such a TestRequest `<1>`, the server will respond with a Heartbeat `<0>` containing the expected `TestReqID (112)`. If the client does not receive the server’s response within a `HeartInt (108)` interval, the client should close the session and connection and establish new ones.

### API Key Permissions

To access the FIX API order entry sessions, your API key must be configured with the `FIX_API` permission.

To access the FIX Drop Copy sessions, your API key must be configured with either `FIX_API_READ_ONLY` or `FIX_API` permission.

To access the FIX Market Data sessions, your API key must be configured with either `FIX_API` or `FIX_API_READ_ONLY` permission.

**FIX sessions only support Ed25519 keys.**

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

<a id="orderedmode"></a>

### On message processing order

The `MessageHandling (25035)` field required in the initial [Logon`<A>`](#logon-request) message controls whether messages from the client may be reordered before they are processed by the Matching Engine.

| Mode            | Description                                                                                |
|-----------------|--------------------------------------------------------------------------------------------|
| `UNORDERED(1)`  | Messages from the client are allowed to be sent to the matching engine in any order.       |
| `SEQUENTIAL(2)` | Messages from the client are always sent to the matching engine in `MsgSeqNum (34)` order. |

In all modes, the client's `MsgSeqNum (34)` must increase monotonically, with each subsequent message having a sequence number that is exactly 1 greater than the previous message.

> [!TIP]
> `UNORDERED(1)` should offer better performance when there are multiple messages in flight from the client to the server.

<a id="responsemode"></a>

### Response Mode

By default, all concurrent order entry sessions receive all of the account's
successful [ExecutionReport`<8>`](#executionreport) and [ListStatus`<N>`](#liststatus) messages,
including those in response to orders placed from other FIX sessions and via non-FIX APIs.

Use the `ResponseMode (25036)` field in the initial [Logon`<A>`](#logon-request) message
to change this behavior.

- `EVERYTHING(1)`: The default mode.
- `ONLY_ACKS(2)`: Receive only ACK messages whether operation succeeded or failed. Disables ExecutionReport push.

<a id="timingsecurity"></a>

### Timing Security

* All requests require a `SendingTime(52)` field which should be the current timestamp.
* An additional optional field, `RecvWindow(25000)`, specifies for how long the request stays valid in milliseconds.
  * `RecvWindow(25000)` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.
  * If `RecvWindow(25000)` is not specified, it defaults to 5000 milliseconds only for the Logon`<A>` request. For other requests if unset, the RecvWindow check is not executed.
  * Maximum `RecvWindow(25000)` is 60000 milliseconds.
* Request processing logic is as follows:

```javascript
serverTime = getCurrentTime()
if (SendingTime < (serverTime + 1 second) && (serverTime - SendingTime) <= RecvWindow) {
  // begin processing request
  serverTime = getCurrentTime()
  if (serverTime - SendingTime) <= RecvWindow {
    // forward request to Matching Engine
  } else {
    // reject request
  }
  // finish processing request
} else {
  // reject request
}
```

<a id="signaturecomputation"></a>

### How to sign Logon `<A>` request

The [Logon`<A>`](#logon-main) message authenticates your connection to the FIX API.
This must be the first message sent by the client.

* The `Username (553)` field is required to contain the API key.
* The `RawData (96)` field is required to contain a valid signature made with the API key.

The signature payload is a text string constructed by concatenating the values of the following fields in this exact order,
separated by the SOH character:

1. `MsgType (35)`
2. `SenderCompId (49)`
3. `TargetCompId (56)`
4. `MsgSeqNum (34)`
5. `SendingTime (52)`


Sign the payload using your private key.
Encode the signature with **base64**.
The resulting text string is the value of the `RawData (96)` field.

Here is a sample Python code implementing the signature algorithm:

````python
import base64

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import load_pem_private_key

def logon_raw_data(private_key: Ed25519PrivateKey,
                   sender_comp_id: str,
                   target_comp_id: str,
                   msg_seq_num: str,
                   sending_time: str):
    """
    Computes the value of RawData (96) field in Logon<A> message.
    """
    payload = chr(1).join([
        'A',
        sender_comp_id,
        target_comp_id,
        msg_seq_num,
        sending_time,
    ])
    signature = private_key.sign(payload.encode('ASCII'))
    return base64.b64encode(signature).decode('ASCII')


with open('private_key.pem', 'rb') as f:
    private_key = load_pem_private_key(data=f.read(),
                                       password=None)

raw_data = logon_raw_data(private_key,
                          sender_comp_id='5JQmUOsm',
                          target_comp_id='SPOT',
                          msg_seq_num='1',
                          sending_time='20240612-08:52:21.613')
````

The values presented below can be used to validate the correctness of the signature computation implementation:

| Field             | Value                   |
|-------------------|-------------------------|
| MsgType (35)      | `A`                     |
| SenderCompID (49) | `EXAMPLE`               |
| TargetCompID (56) | `SPOT`                  |
| MsgSeqNum (34)    | `1`                     |
| SendingTime (52)  | `20240627-11:17:25.223` |

The Ed25519 private key used in the example computation is shown below:

> [!CAUTION]
> The following secret key is provided solely for illustrative purposes. Do not use this key in any real-world application as it is not secure and may compromise your cryptographic implementation. Always generate your own unique and secure keys for actual use.

```
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIIJEYWtGBrhACmb9Dvy+qa8WEf0lQOl1s4CLIAB9m89u
-----END PRIVATE KEY-----
```

Computed signature:
```
4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==
```

Resulting Logon `<A>` message:
```
8=FIX.4.4|9=247|35=A|34=1|49=EXAMPLE|52=20240627-11:17:25.223|56=SPOT|95=88|96=4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==|98=0|108=30|141=Y|553=sBRXrJx2DsOraMXOaUovEhgVRcjOvCtQwnWj8VxkOh1xqboS02SPGfKi2h8spZJb|25035=2|10=227|
```
filename:    binance-spot-api-docs-master/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## General endpoints

### Test connectivity
```
GET /api/v3/ping
```
Test connectivity to the Rest API.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{}
```

### Check server time
```
GET /api/v3/time
```
Test connectivity to the Rest API and get the current server time.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{
    "serverTime": 1499827319559
}
```

<a id="exchangeInfo"></a>

### Exchange information
```
GET /api/v3/exchangeInfo
```
Current exchange trading rules and symbol information

**Weight:**
20

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
symbol |STRING| No| Example: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"
symbols |ARRAY OF STRING|No| Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbols=%5B%22BNBBTC%22,%22BTCUSDT%22%5D" <br/> or <br/> curl -g -X  GET 'https://api.binance.com/api/v3/exchangeInfo?symbols=["BTCUSDT","BNBBTC"]'
permissions |ENUM|No|Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=SPOT" <br/> or <br/> curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=%5B%22MARGIN%22%2C%22LEVERAGED%22%5D" <br/> or <br/> curl -g -X GET 'https://api.binance.com/api/v3/exchangeInfo?permissions=["MARGIN","LEVERAGED"]' |
showPermissionSets|BOOLEAN|No|Controls whether the content of the `permissionSets` field is populated or not. Defaults to `true`
symbolStatus|ENUM|No|Filters for symbols that have this `tradingStatus`. Valid values: `TRADING`, `HALT`, `BREAK` <br> Cannot be used in combination with `symbols` or `symbol`.|

**Notes:**
* If the value provided to `symbol` or `symbols` do not exist, the endpoint will throw an error saying the symbol is invalid.
* All parameters are optional.
* `permissions` can support single or multiple values (e.g. `SPOT`, `["MARGIN","LEVERAGED"]`). This cannot be used in combination with `symbol` or `symbols`.
* If `permissions` parameter not provided, all symbols that have either `SPOT`, `MARGIN`, or `LEVERAGED` permission will be exposed.
  * To display symbols with any permission you need to specify them explicitly in `permissions`: (e.g. `["SPOT","MARGIN",...]`.). See [Account and Symbol Permissions](enums.md#account-and-symbol-permissions) for the full list.

<a id="examples-of-symbol-permissions-interpretation-from-the-response"></a>

**Examples of Symbol Permissions Interpretation from the Response:**

* `[["A","B"]]` means you may place an order if your account has either permission "A" **or** permission "B".
* `[["A"],["B"]]` means you can place an order if your account has permission "A" **and** permission "B".
* `[["A"],["B","C"]]` means you can place an order if your account has permission "A" **and** permission "B" or permission "C". (Inclusive or is applied here, not exclusive or, so your account may have both permission "B" and permission "C".)

**Data Source:**
Memory

**Response:**
```javascript
{
    "timezone": "UTC",
    "serverTime": 1565246363776,
    "rateLimits": [
        {
            // These are defined in the `ENUM definitions` section under `Rate Limiters (rateLimitType)`.
            // All limits are optional
        }
    ],
    "exchangeFilters": [
        // These are the defined filters in the `Filters` section.
        // All filters are optional.
    ],
    "symbols": [
        {
            "symbol": "ETHBTC",
            "status": "TRADING",
            "baseAsset": "ETH",
            "baseAssetPrecision": 8,
            "quoteAsset": "BTC",
            "quotePrecision": 8,     // will be removed in future api versions (v4+)
            "quoteAssetPrecision": 8,
            "baseCommissionPrecision": 8,
            "quoteCommissionPrecision": 8,
            "orderTypes": [
                "LIMIT",
                "LIMIT_MAKER",
                "MARKET",
                "STOP_LOSS",
                "STOP_LOSS_LIMIT",
                "TAKE_PROFIT",
                "TAKE_PROFIT_LIMIT"
            ],
            "icebergAllowed": true,
            "ocoAllowed": true,
            "otoAllowed": true,
            "opoAllowed": true,
            "quoteOrderQtyMarketAllowed": true,
            "allowTrailingStop": false,
            "cancelReplaceAllowed": false,
            "amendAllowed": false,
            "pegInstructionsAllowed": true,
            "isSpotTradingAllowed": true,
            "isMarginTradingAllowed": true,
            "filters": [
                // These are defined in the Filters section.
                // All filters are optional
            ],
            "permissions": [],
            "permissionSets": [["SPOT", "MARGIN"]],
            "defaultSelfTradePreventionMode": "NONE",
            "allowedSelfTradePreventionModes": ["NONE"]
        }
    ],
    // Optional field. Present only when SOR is available.
    // https://github.com/binance/binance-spot-api-docs/blob/master/faqs/sor_faq.md
    "sors": [
        {
            "baseAsset": "BTC",
            "symbols": ["BTCUSDT", "BTCUSDC"]
        }
    ]
}
```

### Query Execution Rules

```
GET /api/v3/executionRules
```

**Weight**

Parameter | Weight|
---        | ---
`symbol`  | 2
`symbols` | 2 for each `symbol`, capped at a max of 40|
`symbolStatus` |40|
None            |40|

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
`symbol`   | STRING| No      | Query for specified symbol
`symbols`  | STRING | No     | Query for multiple symbols
`symbolStatus` |ENUM| Query for all symbols with the specified status. Supported values: `TRADING`, `HALT`, `BREAK`


**Note:** No combination of multiple parameters is allowed.

**Data Source:** Memory

**Response:**

```javascript
{
    "symbolRules": [
        {
            "symbol": "BAZUSD",
            "rules": [
                {
                    "ruleType": "PRICE_RANGE",
                    "bidLimitMultUp": "1.0001",
                    "bidLimitMultDown": "0.9999",
                    "askLimitMultUp": "1.0001",
                    "askLimitMultDown": "0.9999"
                }
            ]
        }
    ]
}
```
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## General API Information

* The following base endpoints are available. Please use whichever works best for your setup:
  * **https://api.binance.com**
  * **https://api-gcp.binance.com**
  * **https://api1.binance.com**
  * **https://api2.binance.com**
  * **https://api3.binance.com**
  * **https://api4.binance.com**
* The last 4 endpoints in the point above (`api1`-`api4`) should give better performance but have less stability.
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](./faqs/sbe_faq.md) page.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.

In [12]:
embedding_model = SentenceTransformer("multi-qa-distilbert-cos-v1")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

In [13]:
binance_embeddings = []

for d in tqdm(binance_docs):
    v = embedding_model.encode(d["chunk"])
    binance_embeddings.append(v)

binance_embeddings = np.array(binance_embeddings)
binance_embeddings.shape

  0%|          | 0/367 [00:00<?, ?it/s]

(367, 768)

In [14]:
vector_index = VectorSearch()
vector_index.fit(binance_embeddings, binance_docs)

In [15]:
query = "How can I authenticate a private Binance API endpoint?"
q = embedding_model.encode(query)

vector_results = vector_index.search(q, num_results=5)
preview_results(vector_results)

Result #1
title:
section:     ## 如何正确在本地维护一个order book副本

1. 打开与 `wss://stream.binance.com:9443/ws/bnbbtc@depth` 的 WebSocket 连接。
2. 开始缓存收到的event。请记录您收到的第一个event的 `U`值。
3. 访问 `https://api.binance.com/api/v3/depth?symbol=BNBBTC&limit=5000` 获取深度快照。
4. 如果快照中的 `lastUpdateId` 小于等于步骤 2 中的 `U` 值，请返回步骤 3。
5. 在收到的event中，丢弃快照中 `u` <= `lastUpdateId` 的所有event。现在第一个event的 `lastUpdateId` 应该在 `[U;u]` 范围以内。
6. 将本地order book设置为快照。它的更新ID 为 `lastUpdateId`。
7. 更新所有缓存的event，以及后续的所有event。

要将一个event应用于您的本地order book，请遵循以下更新过程：
1. 判断是否需要处理event：
    * 如果event的最后一次更新ID（`u`）小于本地order book的更新ID，忽略该event。
    * 如果event的首次更新ID（`U`）大于本地order book的更新ID加1，说明你错过了一些events。<br>请丢弃您的本地order book并从头开始重新同步。
    * 通常，下一event的`U`等于上一event的`u + 1`。
1. 对买价（`b`）和卖价（`a`）中的每个价位，设置order book中的新数量：
    * 如果该价位在order book中不存在，则插入该价位及其数量。
    * 如果数量为零，则从order book中删除此价位。
1. 将order book的更新ID设置为已处理event的最后一次更新ID（`u`）。

> [!NOTE]
> 由于从 API 检索的深度快照对价位的数量有限制（每侧最多 5000 个），因此除非它们发生变化，否则您将无法了解初始快照之外的价位数量。<br>
> 因此，在使用这些级别的信息时要小心，因为它们可能无法反映订单簿的完整视图。<br>
> 但是，对于大多数场景，可以每侧看到 5000 个价位就足以了解市场并进行有效交易。
filename:    binance-spot-api-docs-master/web-socket-streams_CN.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## Average Price

Average price streams push changes in the average price over a fixed time interval.

**Stream Name:** \<symbol\>@avgPrice

**Update Speed:** 1000ms

**Payload:**

```javascript
{
    "e": "avgPrice",           // Event type
    "E": 1693907033000,        // Event time
    "s": "BTCUSDT",            // Symbol
    "i": "5m",                 // Average price interval
    "w": "25776.86000000",     // Average price
    "T": 1693907032213         // Last trade time
}
```
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## Partial Book Depth Streams

Top **\<levels\>** bids and asks, pushed every second. Valid **\<levels\>** are 5, 10, or 20.

**Stream Names:** \<symbol\>@depth\<levels\> OR \<symbol\>@depth\<levels\>@100ms

**Update Speed:** 1000ms or 100ms

**Payload:**
```javascript
{
    "lastUpdateId": 160,     // Last update ID
    "bids": [                // Bids to be updated
        [
            "0.0024",        // Price level to be updated
            "10"             // Quantity
        ]
    ],
    "asks": [                // Asks to be updated
        [
            "0.0026",        // Price level to be updated
            "100"            // Quantity
        ]
    ]
}
```
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## Diff. Depth Stream

Order book price and quantity depth updates used to locally manage an order book.

**Stream Name:** \<symbol\>@depth OR \<symbol\>@depth@100ms

**Update Speed:** 1000ms or 100ms

**Payload:**
```javascript
{
    "e": "depthUpdate",     // Event type
    "E": 1672515782136,     // Event time
    "s": "BNBBTC",          // Symbol
    "U": 157,               // First update ID in event
    "u": 160,               // Final update ID in event
    "b": [                  // Bids to be updated
        [
            "0.0024",       // Price level to be updated
            "10"            // Quantity
        ]
    ],
    "a": [                  // Asks to be updated
        [
            "0.0026",       // Price level to be updated
            "100"           // Quantity
        ]
    ]
}
```
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## How to manage a local order book correctly

1. Open a WebSocket connection to `wss://stream.binance.com:9443/ws/bnbbtc@depth`.
1. Buffer the events received from the stream. Note the `U` of the first event you received.
1. Get a depth snapshot from `https://api.binance.com/api/v3/depth?symbol=BNBBTC&limit=5000`.
1. If the `lastUpdateId` from the snapshot is strictly less than the `U` from step 2, go back to step 3.
1. In the buffered events, discard any event where `u` is <= `lastUpdateId` of the snapshot. The first buffered event should now have `lastUpdateId` within its `[U;u]` range.
1. Set your local order book to the snapshot. Its update ID is `lastUpdateId`.
1. Apply the update procedure below to all buffered events, and then to all subsequent events received.

To apply an event to your local order book, follow this update procedure:
1. Decide whether the update event can be applied:
    * If the event last update ID (`u`) is less than the update ID of your local order book,
      ignore the event.
    * If the event first update ID (`U`) is greater than the update ID of your local order book + 1,
      you have missed some events. <br> Discard your local order book and restart the process from the beginning.
    * Normally, `U` of the next event is equal to `u + 1` of the previous event.
1. For each price level in bids (`b`) and asks (`a`), set the new quantity in the order book:
    * If the price level does not exist in the order book, insert it with new quantity.
    * If the quantity is zero, remove the price level from the order book.
1. Set the order book update ID to the last update ID (`u`) in the processed event.

> [!NOTE]
> Since depth snapshots retrieved from the API have a limit on the number of price levels (5000 on each side maximum), you won't learn the quantities for the levels outside of the initial snapshot unless they change. <br>
> So be careful when using the information for those levels, since they might not reflect the full view of the order book. <br>
> However, for most use cases, seeing 5000 levels on each side is enough to understand the market and trade effectively.
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

In [16]:
def text_search(query, num_results=5):
    return text_index.search(query, num_results=num_results)


def vector_search(query, num_results=5):
    q = embedding_model.encode(query)
    return vector_index.search(q, num_results=num_results)

In [17]:
def hybrid_search(query, num_results=5):
    text_results = text_search(query, num_results=num_results)
    vector_results = vector_search(query, num_results=num_results)

    seen_ids = set()
    combined_results = []

    for result in text_results + vector_results:
        if result["id"] not in seen_ids:
            seen_ids.add(result["id"])
            combined_results.append(result)

    return combined_results[:num_results]

In [18]:
query = "What does recvWindow mean in Binance API requests?"
hybrid_results = hybrid_search(query, num_results=5)
preview_results(hybrid_results)

Result #1
title:
section:     ## General API Information

* The following base endpoints are available. Please use whichever works best for your setup:
  * **https://api.binance.com**
  * **https://api-gcp.binance.com**
  * **https://api1.binance.com**
  * **https://api2.binance.com**
  * **https://api3.binance.com**
  * **https://api4.binance.com**
* The last 4 endpoints in the point above (`api1`-`api4`) should give better performance but have less stability.
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](./faqs/sbe_faq.md) page.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* Some endpoints may return asset and/or symbol names containing non-ASCII characters encoded in UTF-8 even if the request did not contain non-ASCII characters.
* Data is returned in **chronological order**, unless noted otherwise.
  * Without `startTime` or `endTime`, returns the most recent items up to the limit.
  * With `startTime`, returns oldest items from `startTime` up to the limit.
  * With `endTime`, returns most recent items up to `endTime` and the limit.
  * With both, behaves like `startTime` but does not exceed `endTime`.
* All time and timestamp related fields in the JSON responses are in **milliseconds by default.** To receive the information in microseconds, please add the header `X-MBX-TIME-UNIT:MICROSECOND` or `X-MBX-TIME-UNIT:microsecond`.
* We support HMAC, RSA, and Ed25519 keys. For more information, please see [API Key types](faqs/api_key_types.md).
* Timestamp parameters (e.g. `startTime`, `endTime`, `timestamp`) can be passed in milliseconds or microseconds.
* For APIs that only send public market data, please use the base endpoint **https://data-api.binance.vision**. Please refer to [Market Data Only](./faqs/market_data_only.md) page.
* If there are enums or terms you want clarification on, please see the [SPOT Glossary](faqs/spot_glossary.md) for more information.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* **Please avoid SQL keywords in requests** as they may trigger a security block by a WAF (Web Application Firewall) rule. See https://www.binance.com/en/support/faq/detail/360004492232 for more details.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* Some endpoints may return asset and/or symbol names containing non-ASCII characters encoded in UTF-8 even if the request did not contain non-ASCII characters.
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## General API Information

* The base endpoint is: **`wss://ws-api.binance.com:443/ws-api/v3`**.
  * If you experience issues with the standard 443 port, alternative port 9443 is also available.
  * The base endpoint for [testnet](https://testnet.binance.vision/) is: `wss://ws-api.testnet.binance.vision/ws-api/v3`
* A single connection to the API is only valid for 24 hours; expect to be disconnected after the 24-hour mark.
* Before a disconnection either due to maintenance or after 24 hours, a [`serverShutdown`](#server-shutdown) event will be sent. Please reconnect as soon as possible to prevent stream interruption.
* We support HMAC, RSA, and Ed25519 keys. For more information, please see [API Key types](faqs/api_key_types.md).
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](faqs/sbe_faq.md) page.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* Some methods may return asset and/or symbol names containing non-ASCII characters encoded in UTF-8 even if the request did not contain non-ASCII characters.
* The WebSocket server will send a `ping frame` every 20 seconds.
  * If the WebSocket server does not receive a `pong frame` back from the connection within a minute the connection will be disconnected.
  * When you receive a ping, you must send a pong with a copy of ping's payload as soon as possible.
  * Unsolicited `pong frames` are allowed, but will not prevent disconnection. **It is recommended that the payload for these pong frames are empty.**
* Data is returned in **chronological order**, unless noted otherwise.
  * Without `startTime` or `endTime`, returns the most recent items up to the limit.
  * With `startTime`, returns oldest items from `startTime` up to the limit.
  * With `endTime`, returns most recent items up to `endTime` and the limit.
  * With both, behaves like `startTime` but does not exceed `endTime`.
* All timestamps in the JSON responses are in **milliseconds in UTC by default**. To receive the information in microseconds, please add the parameter `timeUnit=MICROSECOND` or `timeUnit=microsecond` in the URL.
* Timestamp parameters (e.g. `startTime`, `endTime`, `timestamp`) can be passed in milliseconds or microseconds.
* All field names and values are **case-sensitive**, unless noted otherwise.
* If there are enums or terms you want clarification on, please see [SPOT Glossary](faqs/spot_glossary.md) for more information.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* **Please avoid SQL keywords in requests** as they may trigger a security block by a WAF (Web Application Firewall) rule. See https://www.binance.com/en/support/faq/detail/360004492232 for more details.
filename:    binance-spot-api-docs-master/web-socket-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## Session Authentication

**Note:** Only _Ed25519_ keys are supported for this feature.

If you do not want to specify `apiKey` and `signature` in each individual request,
you can authenticate your API key for the active WebSocket session.

Once authenticated, you no longer have to specify `apiKey` and `signature` for those requests that need them.
Requests will be performed on behalf of the account owning the authenticated API key.

**Note:** You still have to specify the `timestamp` parameter for `SIGNED` requests.

### Authenticate after connection

You can authenticate an already established connection using session authentication requests:

* [`session.logon`](#log-in-with-api-key-signed) – authenticate, or change the API key associated with the connection
* [`session.status`](#query-session-status) – check connection status and the current API key
* [`session.logout`](#log-out-of-the-session) – forget the API key associated with the connection

**Regarding API key revocation:**

If during an active session the API key becomes invalid for _any reason_ (e.g. IP address is not whitelisted, API key was deleted, API key doesn't have correct permissions, etc), after the next request the session will be revoked with the following error message:

```javascript
{
    "id": null,
    "status": 401,
    "error": {
        "code": -2015,
        "msg": "Invalid API-key, IP, or permissions for action."
    }
}
```

### Authorize _ad hoc_ requests

Only one API key can be authenticated with the WebSocket connection.
The authenticated API key is used by default for requests that require an `apiKey` parameter.
However, you can always specify the `apiKey` and `signature` explicitly for individual requests,
overriding the authenticated API key and using a different one to authorize a specific request.

For example, you might want to authenticate your `USER_DATA` key to be used by default,
but specify the `TRADE` key with an explicit signature when placing orders.
filename:    binance-spot-api-docs-master/web-socket-api.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## Request security

* Each method has a security type indicating required API key permissions, shown next to the method name (e.g., [Place new order (TRADE)](#place-new-order-trade)).
* If unspecified, the security type is `NONE`.
* Except for `NONE`, all methods with a security type are considered `SIGNED` requests (i.e. including a `signature`), except for [listenKey management](#user-data-stream-requests).
* Secure methods require a valid API key to be specified and authenticated.
  * API keys can be created on the [API Management](https://www.binance.com/en/support/faq/360002502072) page of your Binance account.
  * **Both API key and secret key are sensitive.** Never share them with anyone.
    If you notice unusual activity in your account, immediately revoke all the keys and contact Binance support.
* API keys can be configured to allow access only to certain types of secure methods.
  * For example, you can have an API key with `TRADE` permission for trading,
    while using a separate API key with `USER_DATA` permission to monitor your order status.
  * By default, an API key cannot `TRADE`. You need to enable trading in API Management first.

Security type |  Description
------------- | ------------
`NONE`        | Public market data
`TRADE`       | Trading on the exchange, placing and canceling orders
`USER_DATA`   | Private account information, such as order status and your trading history
`USER_STREAM` | Managing User Data Stream subscriptions

### SIGNED request security

* `SIGNED` requests require an additional parameter: `signature`, authorizing the request.

#### Signature Case Sensitivity

* **HMAC:** Signatures generated using HMAC are **not case-sensitive**. This means the signature string can be verified regardless of letter casing.
* **RSA:** Signatures generated using RSA are **case-sensitive**.
* **Ed25519:** Signatures generated using ED25519 are also **case-sensitive**

Please consult [SIGNED request example (HMAC)](#signed-request-example-hmac), [SIGNED request example (RSA)](#signed-request-example-rsa), and [SIGNED request example (Ed25519)](#signed-request-example-ed25519) on how to compute signature, depending on which API key type you are using.

<a id="timingsecurity"></a>

### Timing security

* `SIGNED` requests also require a `timestamp` parameter which should be the current timestamp either in milliseconds or microseconds. (See [General API Information](#general-api-information))
* An additional optional parameter, `recvWindow`, specifies for how long the request stays valid and may only be specified in milliseconds.
  * `recvWindow` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.
  * If `recvWindow` is not sent, **it defaults to 5000 milliseconds**.
  * Maximum `recvWindow` is 60000 milliseconds.
* Request processing logic is as follows:

```javascript
serverTime = getCurrentTime()
if (timestamp < (serverTime + 1 second) && (serverTime - timestamp) <= recvWindow) {
  // begin processing request
  serverTime = getCurrentTime()
  if (serverTime - timestamp) <= recvWindow {
    // forward request to Matching Engine
  } else {
    // reject request
  }
  // finish processing request
} else {
  // reject request
}
  ```

**Serious trading is about timing.** Networks can be unstable and unreliable,
which can lead to requests taking varying amounts of time to reach the
servers. With `recvWindow`, you can specify that the request must be
processed within a certain number of milliseconds or be rejected by the
server.

**It is recommended to use a small `recvWindow` of 5000 or less!**

### SIGNED request example (HMAC)

Here is a step-by-step guide on how to sign requests using an HMAC secret key.

Example API key and secret key:

Key          | Value
------------ | ------------
`apiKey`       | `vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A`
`secretKey`    | `NhqPtmdSJYdKjVHjA7PZj4Mge3R5YNiP1e3UZjInClVN65XAbvqqM6A7H5fATj0j`

**WARNING: DO NOT SHARE YOUR API KEY AND SECRET KEY WITH ANYONE.**

The example keys are provided here only for illustrative purposes.

Example of request with a symbol name comprised entirely of ASCII characters:

```json
{
    "id": "4885f793-e5ad-4c3b-8f6c-55d891472b71",
    "method": "order.place",
    "params": {
        "symbol": "BTCUSDT",
        "side": "SELL",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": "0.01000000",
        "price": "52000.00",
        "recvWindow": 100,
        "timestamp": 1645423376532,
        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",
        "signature": "------ FILL ME ------"
    }
}
```

Example of a request with a symbol name containing non-ASCII characters:

```json
{
    "id": "4885f793-e5ad-4c3b-8f6c-55d891472b71",
    "method": "order.place",
    "params": {
        "symbol": "１２３４５６",
        "side": "BUY",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": "0.01000000",
        "price": "0.10000000",
        "recvWindow": 5000,
        "timestamp": 1645423376532,
        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",
        "signature": "------ FILL ME ------"
    }
}
```

As you can see, the `signature` parameter is currently missing.

**Step 1: Construct the signature payload**

Take all request `params` except `signature` and **sort them in alphabetical order by parameter name**:

For the first set of example parameters (ASCII only):

Parameter        | Value
---------------- | ------------
`apiKey`           | vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
`price`            | 52000.00
`quantity`         | 0.01000000
`recvWindow`       | 100
`side`             | SELL
`symbol`           | BTCUSDT
`timeInForce`      | GTC
`timestamp`        | 1645423376532
`type`             | LIMIT

For the second set of example parameters (some non-ASCII characters):

Parameter | Value
------------ | ------------
`apiKey` | vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
`price` | 0.10000000
`quantity` | 1.00000000
`recvWindow` | 5000
`side` | BUY
`symbol` | １２３４５６
`timeInForce` | GTC
`timestamp` | 1645423376532
`type` | LIMIT

Format parameters as `parameter=value` pairs separated by `&`. Values need to be encoded in UTF-8.

For the first set of example parameters (ASCII only), the signature payload should look like this:

```console
apiKey=vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A&price=52000.00&quantity=0.01000000&recvWindow=100&side=SELL&symbol=BTCUSDT&timeInForce=GTC&timestamp=1645423376532&type=LIMIT
```

For the second set of example parameters (some non-ASCII characters), the signature payload should look like this:

```console
apiKey=vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A&price=0.10000000&quantity=1.00000000&recvWindow=5000&side=BUY&symbol=１２３４５６&timeInForce=GTC&timestamp=1645423376532&type=LIMIT
```

**Step 2: Compute the signature**

1. Use the `secretKey` of your API key as the signing key for the HMAC-SHA-256 algorithm.
2. Sign the UTF-8 bytes of the signature payload constructed in Step 1.
3. Encode the HMAC-SHA-256 output as a hex string.

Note that `apiKey`, `secretKey`, and the payload are **case-sensitive**, while the resulting signature value is case-insensitive.

You can cross-check your signature algorithm implementation with OpenSSL:

For the first set of example parameters (ASCII only):

```console
$ echo -n 'apiKey=vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A&price=52000.00&quantity=0.01000000&recvWindow=100&side=SELL&symbol=BTCUSDT&timeInForce=GTC&timestamp=1645423376532&type=LIMIT' \
  | openssl dgst -hex -sha256 -hmac 'NhqPtmdSJYdKjVHjA7PZj4Mge3R5YNiP1e3UZjInClVN65XAbvqqM6A7H5fATj0j'

aa1b5712c094bc4e57c05a1a5c1fd8d88dcd628338ea863fec7b88e59fe2db24
```

For the second set of example parameters (some non-ASCII characters):

```console
$ echo -n 'apiKey=vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A&price=0.10000000&quantity=1.00000000&recvWindow=5000&side=BUY&symbol=１２３４５６&timeInForce=GTC&timestamp=1645423376532&type=LIMIT' \
  | openssl dgst -hex -sha256 -hmac 'NhqPtmdSJYdKjVHjA7PZj4Mge3R5YNiP1e3UZjInClVN65XAbvqqM6A7H5fATj0j'

b33892ae8e687c939f4468c6268ddd4c40ac1af18ad19a064864c47bae0752cd
```

**Step 3: Add `signature` to request `params`**

Complete the request by adding the `signature` parameter with the signature string.

For the first set of example parameters (ASCII only):

```json
{
    "id": "4885f793-e5ad-4c3b-8f6c-55d891472b71",
    "method": "order.place",
    "params": {
        "symbol": "BTCUSDT",
        "side": "SELL",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": "0.01000000",
        "price": "52000.00",
        "recvWindow": 100,
        "timestamp": 1645423376532,
        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",
        "signature": "aa1b5712c094bc4e57c05a1a5c1fd8d88dcd628338ea863fec7b88e59fe2db24"
    }
}
```

For the second set of example parameters (some non-ASCII characters):

```json
{
    "id": "4885f793-e5ad-4c3b-8f6c-55d891472b71",
    "method": "order.place",
    "params": {
        "symbol": "１２３４５６",
        "side": "BUY",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": "1.00000000",
        "price": "0.10000000",
        "recvWindow": 5000,
        "timestamp": 1645423376532,
        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",
        "signature": "b33892ae8e687c939f4468c6268ddd4c40ac1af18ad19a064864c47bae0752cd"
    }
}
```

### SIGNED request example (RSA)

Here is a step-by-step guide on how to sign requests using an RSA private key.

Key          | Value
------------ | ------------
`apiKey`       | `CAvIjXy3F44yW6Pou5k8Dy1swsYDWJZLeoK2r8G4cFDnE9nosRppc2eKc1T8TRTQ`

These examples assume the private key is stored in the file `test-rsa-prv.pem`.

**WARNING: DO NOT SHARE YOUR API KEY AND PRIVATE KEY WITH ANYONE.**

The example keys are provided here only for illustrative purposes.

Example of request with a symbol name comprised entirely of ASCII characters:

```json
{
    "id": "4885f793-e5ad-4c3b-8f6c-55d891472b71",
    "method": "order.place",
    "params": {
        "symbol": "BTCUSDT",
        "side": "SELL",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": "0.01000000",
        "price": "52000.00",
        "recvWindow": 100,
        "timestamp": 1645423376532,
        "apiKey": "CAvIjXy3F44yW6Pou5k8Dy1swsYDWJZLeoK2r8G4cFDnE9nosRppc2eKc1T8TRTQ",
        "signature": "------ FILL ME ------"
    }
}
```

Example of a request with a symbol name containing non-ASCII characters:

```json
{
    "id": "4885f793-e5ad-4c3b-8f6c-55d891472b71",
    "method": "order.place",
    "params": {
        "symbol": "１２３４５６",
        "side": "BUY",
        "type": "LIMIT",
        "timeInForce": "GTC",
        "quantity": "0.01000000",
        "price": "0.10000000",
        "recvWindow": 5000,
        "timestamp": 1645423376532,

In [19]:
test_queries = [
    "How do I sign a Binance Spot API request?",
    "What does recvWindow mean?",
    "Why am I getting timestamp error?",
    "How do I place a market order?",
    "How can I authenticate a private endpoint?",
    "What are the rate limits?",
    "How do I get exchange info?"
]

for query in test_queries:
    print("\n" + "=" * 100)
    print("QUERY:", query)
    results = hybrid_search(query, num_results=3)
    preview_results(results, max_chars=220)

====================================================================================================
QUERY: How do I sign a Binance Spot API request?

Result #1
title:
section:     ## General API Information

* FIX connections require TLS encryption. Please either use native TCP+TLS connection or set up a local proxy such as [stunnel](https://www.stunnel.org/) to handle TLS encryption.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* To ensure uninterrupted connectivity, please make sure that your client sends **SNI (Server Name Indication)** during the TLS handshake and performs certificate validation against the intended hostname. <br>
Clients that do not send SNI may receive an unexpected certificate, which can result in TLS handshake or hostname verification failures.

<details>
<summary>Example implementations</summary>

### NodeJS
If you are using Node.js and connecting via raw TLS sockets (`tls.connect()`), you must explicitly set the servername option. Please refer to the sample below:

```javascript
  const tls = require("tls");
  const hostname = "fix-dc.binance.com"; //EXAMPLE

  const options = {
     host: hostname,
     port: 9002,
     servername: hostname                // enables SNI
   };
```

Note that: NodeJS doesn't enable SNI by default for TLS (See [https://nodejs.org/api/tls.html#tlsconnectoptions-callback](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)). <br>
If you are using standard HTTPS libraries in Node.js (e.g., `https.request()`, `axios`, `fetch`), these typically set SNI automatically when connecting via a hostname/URL.

### Other languages/custom TLS implementations
When using custom TLS agents / TLS APIs, ensure you set the equivalent field (often named `server_hostname`, `hostname`, or `ServerName`) to the endpoint hostname so SNI is sent.
</details>

**FIX sessions only support Ed25519 keys.** </br>

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

### FIX API Order Entry sessions

* Endpoint is: `tcp+tls://fix-oe.binance.com:9000`
* Supports placing orders, canceling orders, and querying current limit usage.
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).

### FIX API Drop Copy sessions

* Endpoint is: `tcp+tls://fix-dc.binance.com:9000`
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).
* Data in Drop Copy sessions is delayed by 1 second.

### FIX API Market Data sessions

* Endpoint is: `tcp+tls://fix-md.binance.com:9000`
* Supports market data streams and active instruments queries.
* Does not support placing or canceling orders.
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml).

### FIX Connection Lifecycle

* All FIX API sessions will remain open for as long as possible, on a best-effort basis.
* There is no minimum connection time guarantee; a server can enter maintenance at any time.
  * When a server enters maintenance, a [News `<B>`](#news) message will be sent to clients **every 10 seconds for 10 minutes**, prompting clients to reconnect. Upon receiving this message, a client is expected to establish a new session and close the old one. If the client does not close the old session within the time frame, the server will proceed to log it out and close the session.
* After connecting, the client must send a Logon `<A>` request. For more information please refer to [How to sign a Logon request](#signaturecomputation).
* The client should send a Logout `<5>` message to close the session before disconnecting. Failure to send the logout message will result in the session’s `SenderCompID (49)` being unusable for new session establishment for a duration of 2x the `HeartInt (108)` interval.
* The system allows negotiation of the `HeartInt (108)` value during the logon process. Accepted values range between 5 and 60 seconds.
  * If the server has not sent any messages within a `HeartInt (108)` interval, a [HeartBeat `<0>`](#heartbeat)  will be sent.
  * If the server has not received any messages within a `HeartInt (108)` interval, a [TestRequest `<1>`](#testrequest) will be sent. If the server does not receive a HeartBeat `<0>` containing the expected `TestReqID (112)` from the client within `HeartInt (108)` seconds, the server will send a Logout `<5>` message and close the connection.
  * If the client has not received any messages within a `HeartInt (108)` interval, the client is responsible for sending a TestRequest `<1>` to ensure the connection is healthy. Upon receiving such a TestRequest `<1>`, the server will respond with a Heartbeat `<0>` containing the expected `TestReqID (112)`. If the client does not receive the server’s response within a `HeartInt (108)` interval, the client should close the session and connection and establish new ones.

### API Key Permissions

To access the FIX API order entry sessions, your API key must be configured with the `FIX_API` permission.

To access the FIX Drop Copy sessions, your API key must be configured with either `FIX_API_READ_ONLY` or `FIX_API` permission.

To access the FIX Market Data sessions, your API key must be configured with either `FIX_API` or `FIX_API_READ_ONLY` permission.

**FIX sessions only support Ed25519 keys.**

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

<a id="orderedmode"></a>

### On message processing order

The `MessageHandling (25035)` field required in the initial [Logon`<A>`](#logon-request) message controls whether messages from the client may be reordered before they are processed by the Matching Engine.

| Mode            | Description                                                                                |
|-----------------|--------------------------------------------------------------------------------------------|
| `UNORDERED(1)`  | Messages from the client are allowed to be sent to the matching engine in any order.       |
| `SEQUENTIAL(2)` | Messages from the client are always sent to the matching engine in `MsgSeqNum (34)` order. |

In all modes, the client's `MsgSeqNum (34)` must increase monotonically, with each subsequent message having a sequence number that is exactly 1 greater than the previous message.

> [!TIP]
> `UNORDERED(1)` should offer better performance when there are multiple messages in flight from the client to the server.

<a id="responsemode"></a>

### Response Mode

By default, all concurrent order entry sessions receive all of the account's
successful [ExecutionReport`<8>`](#executionreport) and [ListStatus`<N>`](#liststatus) messages,
including those in response to orders placed from other FIX sessions and via non-FIX APIs.

Use the `ResponseMode (25036)` field in the initial [Logon`<A>`](#logon-request) message
to change this behavior.

- `EVERYTHING(1)`: The default mode.
- `ONLY_ACKS(2)`: Receive only ACK messages whether operation succeeded or failed. Disables ExecutionReport push.

<a id="timingsecurity"></a>

### Timing Security

* All requests require a `SendingTime(52)` field which should be the current timestamp.
* An additional optional field, `RecvWindow(25000)`, specifies for how long the request stays valid in milliseconds.
  * `RecvWindow(25000)` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.
  * If `RecvWindow(25000)` is not specified, it defaults to 5000 milliseconds only for the Logon`<A>` request. For other requests if unset, the RecvWindow check is not executed.
  * Maximum `RecvWindow(25000)` is 60000 milliseconds.
* Request processing logic is as follows:

```javascript
serverTime = getCurrentTime()
if (SendingTime < (serverTime + 1 second) && (serverTime - SendingTime) <= RecvWindow) {
  // begin processing request
  serverTime = getCurrentTime()
  if (serverTime - SendingTime) <= RecvWindow {
    // forward request to Matching Engine
  } else {
    // reject request
  }
  // finish processing request
} else {
  // reject request
}
```

<a id="signaturecomputation"></a>

### How to sign Logon `<A>` request

The [Logon`<A>`](#logon-main) message authenticates your connection to the FIX API.
This must be the first message sent by the client.

* The `Username (553)` field is required to contain the API key.
* The `RawData (96)` field is required to contain a valid signature made with the API key.

The signature payload is a text string constructed by concatenating the values of the following fields in this exact order,
separated by the SOH character:

1. `MsgType (35)`
2. `SenderCompId (49)`
3. `TargetCompId (56)`
4. `MsgSeqNum (34)`
5. `SendingTime (52)`


Sign the payload using your private key.
Encode the signature with **base64**.
The resulting text string is the value of the `RawData (96)` field.

Here is a sample Python code implementing the signature algorithm:

````python
import base64

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import load_pem_private_key

def logon_raw_data(private_key: Ed25519PrivateKey,
                   sender_comp_id: str,
                   target_comp_id: str,
                   msg_seq_num: str,
                   sending_time: str):
    """
    Computes the value of RawData (96) field in Logon<A> message.
    """
    payload = chr(1).join([
        'A',
        sender_comp_id,
        target_comp_id,
        msg_seq_num,
        sending_time,
    ])
    signature = private_key.sign(payload.encode('ASCII'))
    return base64.b64encode(signature).decode('ASCII')


with open('private_key.pem', 'rb') as f:
    private_key = load_pem_private_key(data=f.read(),
                                       password=None)

raw_data = logon_raw_data(private_key,
                          sender_comp_id='5JQmUOsm',
                          target_comp_id='SPOT',
                          msg_seq_num='1',
                          sending_time='20240612-08:52:21.613')
````

The values presented below can be used to validate the correctness of the signature computation implementation:

| Field             | Value                   |
|-------------------|-------------------------|
| MsgType (35)      | `A`                     |
| SenderCompID (49) | `EXAMPLE`               |
| TargetCompID (56) | `SPOT`                  |
| MsgSeqNum (34)    | `1`                     |
| SendingTime (52)  | `20240627-11:17:25.223` |

The Ed25519 private key used in the example computation is shown below:

> [!CAUTION]
> The following secret key is provided solely for illustrative purposes. Do not use this key in any real-world application as it is not secure and may compromise your cryptographic implementation. Always generate your own unique and secure keys for actual use.

```
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIIJEYWtGBrhACmb9Dvy+qa8WEf0lQOl1s4CLIAB9m89u
-----END PRIVATE KEY-----
```

Computed signature:
```
4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==
```

Resulting Logon `<A>` message:
```
8=FIX.4.4|9=247|35=A|34=1|49=EXAMPLE|52=20240627-11:17:25.223|56=SPOT|95=88|96=4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==|98=0|108=30|141=Y|553=sBRXrJx2DsOraMXOaUovEhgVRcjOvCtQwnWj8VxkOh1xqboS02SPGfKi2h8spZJb|25035=2|10=227|
```
filename:    binance-spot-api-docs-master/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## General endpoints

### Test connectivity
```
GET /api/v3/ping
```
Test connectivity to the Rest API.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{}
```

### Check server time
```
GET /api/v3/time
```
Test connectivity to the Rest API and get the current server time.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{
    "serverTime": 1499827319559
}
```

<a id="exchangeInfo"></a>

### Exchange information
```
GET /api/v3/exchangeInfo
```
Current exchange trading rules and symbol information

**Weight:**
20

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
symbol |STRING| No| Example: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"
symbols |ARRAY OF STRING|No| Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbols=%5B%22BNBBTC%22,%22BTCUSDT%22%5D" <br/> or <br/> curl -g -X  GET 'https://api.binance.com/api/v3/exchangeInfo?symbols=["BTCUSDT","BNBBTC"]'
permissions |ENUM|No|Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=SPOT" <br/> or <br/> curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=%5B%22MARGIN%22%2C%22LEVERAGED%22%5D" <br/> or <br/> curl -g -X GET 'https://api.binance.com/api/v3/exchangeInfo?permissions=["MARGIN","LEVERAGED"]' |
showPermissionSets|BOOLEAN|No|Controls whether the content of the `permissionSets` field is populated or not. Defaults to `true`
symbolStatus|ENUM|No|Filters for symbols that have this `tradingStatus`. Valid values: `TRADING`, `HALT`, `BREAK` <br> Cannot be used in combination with `symbols` or `symbol`.|

**Notes:**
* If the value provided to `symbol` or `symbols` do not exist, the endpoint will throw an error saying the symbol is invalid.
* All parameters are optional.
* `permissions` can support single or multiple values (e.g. `SPOT`, `["MARGIN","LEVERAGED"]`). This cannot be used in combination with `symbol` or `symbols`.
* If `permissions` parameter not provided, all symbols that have either `SPOT`, `MARGIN`, or `LEVERAGED` permission will be exposed.
  * To display symbols with any permission you need to specify them explicitly in `permissions`: (e.g. `["SPOT","MARGIN",...]`.). See [Account and Symbol Permissions](enums.md#account-and-symbol-permissions) for the full list.

<a id="examples-of-symbol-permissions-interpretation-from-the-response"></a>

**Examples of Symbol Permissions Interpretation from the Response:**

* `[["A","B"]]` means you may place an order if your account has either permission "A" **or** permission "B".
* `[["A"],["B"]]` means you can place an order if your account has permission "A" **and** permission "B".
* `[["A"],["B","C"]]` means you can place an order if your account has permission "A" **and** permission "B" or permission "C". (Inclusive or is applied here, not exclusive or, so your account may have both permission "B" and permission "C".)

**Data Source:**
Memory

**Response:**
```javascript
{
    "timezone": "UTC",
    "serverTime": 1565246363776,
    "rateLimits": [
        {
            // These are defined in the `ENUM definitions` section under `Rate Limiters (rateLimitType)`.
            // All limits are optional
        }
    ],
    "exchangeFilters": [
        // These are the defined filters in the `Filters` section.
        // All filters are optional.
    ],
    "symbols": [
        {
            "symbol": "ETHBTC",
            "status": "TRADING",
            "baseAsset": "ETH",
            "baseAssetPrecision": 8,
            "quoteAsset": "BTC",
            "quotePrecision": 8,     // will be removed in future api versions (v4+)
            "quoteAssetPrecision": 8,
            "baseCommissionPrecision": 8,
            "quoteCommissionPrecision": 8,
            "orderTypes": [
                "LIMIT",
                "LIMIT_MAKER",
                "MARKET",
                "STOP_LOSS",
                "STOP_LOSS_LIMIT",
                "TAKE_PROFIT",
                "TAKE_PROFIT_LIMIT"
            ],
            "icebergAllowed": true,
            "ocoAllowed": true,
            "otoAllowed": true,
            "opoAllowed": true,
            "quoteOrderQtyMarketAllowed": true,
            "allowTrailingStop": false,
            "cancelReplaceAllowed": false,
            "amendAllowed": false,
            "pegInstructionsAllowed": true,
            "isSpotTradingAllowed": true,
            "isMarginTradingAllowed": true,
            "filters": [
                // These are defined in the Filters section.
                // All filters are optional
            ],
            "permissions": [],
            "permissionSets": [["SPOT", "MARGIN"]],
            "defaultSelfTradePreventionMode": "NONE",
            "allowedSelfTradePreventionModes": ["NONE"]
        }
    ],
    // Optional field. Present only when SOR is available.
    // https://github.com/binance/binance-spot-api-docs/blob/master/faqs/sor_faq.md
    "sors": [
        {
            "baseAsset": "BTC",
            "symbols": ["BTCUSDT", "BTCUSDC"]
        }
    ]
}
```

### Query Execution Rules

```
GET /api/v3/executionRules
```

**Weight**

Parameter | Weight|
---        | ---
`symbol`  | 2
`symbols` | 2 for each `symbol`, capped at a max of 40|
`symbolStatus` |40|
None            |40|

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
`symbol`   | STRING| No      | Query for specified symbol
`symbols`  | STRING | No     | Query for multiple symbols
`symbolStatus` |ENUM| Query for all symbols with the specified status. Supported values: `TRADING`, `HALT`, `BREAK`


**Note:** No combination of multiple parameters is allowed.

**Data Source:** Memory

**Response:**

```javascript
{
    "symbolRules": [
        {
            "symbol": "BAZUSD",
            "rules": [
                {
                    "ruleType": "PRICE_RANGE",
                    "bidLimitMultUp": "1.0001",
                    "bidLimitMultDown": "0.9999",
                    "askLimitMultUp": "1.0001",
                    "askLimitMultDown": "0.9999"
                }
            ]
        }
    ]
}
```
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## General API Information

* The following base endpoints are available. Please use whichever works best for your setup:
  * **https://api.binance.com**
  * **https://api-gcp.binance.com**
  * **https://api1.binance.com**
  * **https://api2.binance.com**
  * **https://api3.binance.com**
  * **https://api4.binance.com**
* The last 4 endpoints in the point above (`api1`-`api4`) should give better performance but have less stability.
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](./faqs/sbe_faq.md) page.

In [20]:
len(my_chunks_sections)

367

In [21]:
preview_results(text_search("What does recvWindow mean?"))

Result #1
title:
section:     ## In the API response, there's a field called `workingFloor`. What does that field mean?

This is a term used to determine where the order's last activity occurred (filling, expiring, or being placed as new, etc.).

If the `workingFloor` is `SOR`, this means your order interacted with other eligible order books in the SOR configuration.

If the `workingFloor` is `EXCHANGE`, this means your order interacted on the order book that you sent that order to.
filename:    binance-spot-api-docs-master/faqs/sor_faq.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## What does the Price Range Execution Rule do?

This rule ensures that trades may only be executed at prices within and equal to a price range around a reference price.
filename:    binance-spot-api-docs-master/faqs/price_range_execution_rules.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## In the API response, `fills` contain fields `matchType` and `allocId`. What do they mean?

`matchType` field indicates a non-standard order fill.

When your order is filled by SOR, you will see `matchType: ONE_PARTY_TRADE_REPORT`, indicating that you did not trade directly on the exchange (`tradeId: -1`). Instead your order is filled by _allocations_.

`allocId` field identifies the allocation so that you can query it later.
filename:    binance-spot-api-docs-master/faqs/sor_faq.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## Which time zone does `"interval":"DAY"` use?

UTC
filename:    binance-spot-api-docs-master/faqs/order_count_decrement.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## What happens if my amend request does not succeed?

If the request fails for any reason (e.g. fails the filters, permissions, account restrictions, etc), then the order amend request is rejected and the order remains unchanged.
filename:    binance-spot-api-docs-master/faqs/order_amend_keep_priority.md
chunk:
--------------------------------------------------------------------------------

In [22]:
preview_results(vector_search("How do I authenticate a private endpoint?"))

Result #1
title:
section:     ## 如何正确在本地维护一个order book副本

1. 打开与 `wss://stream.binance.com:9443/ws/bnbbtc@depth` 的 WebSocket 连接。
2. 开始缓存收到的event。请记录您收到的第一个event的 `U`值。
3. 访问 `https://api.binance.com/api/v3/depth?symbol=BNBBTC&limit=5000` 获取深度快照。
4. 如果快照中的 `lastUpdateId` 小于等于步骤 2 中的 `U` 值，请返回步骤 3。
5. 在收到的event中，丢弃快照中 `u` <= `lastUpdateId` 的所有event。现在第一个event的 `lastUpdateId` 应该在 `[U;u]` 范围以内。
6. 将本地order book设置为快照。它的更新ID 为 `lastUpdateId`。
7. 更新所有缓存的event，以及后续的所有event。

要将一个event应用于您的本地order book，请遵循以下更新过程：
1. 判断是否需要处理event：
    * 如果event的最后一次更新ID（`u`）小于本地order book的更新ID，忽略该event。
    * 如果event的首次更新ID（`U`）大于本地order book的更新ID加1，说明你错过了一些events。<br>请丢弃您的本地order book并从头开始重新同步。
    * 通常，下一event的`U`等于上一event的`u + 1`。
1. 对买价（`b`）和卖价（`a`）中的每个价位，设置order book中的新数量：
    * 如果该价位在order book中不存在，则插入该价位及其数量。
    * 如果数量为零，则从order book中删除此价位。
1. 将order book的更新ID设置为已处理event的最后一次更新ID（`u`）。

> [!NOTE]
> 由于从 API 检索的深度快照对价位的数量有限制（每侧最多 5000 个），因此除非它们发生变化，否则您将无法了解初始快照之外的价位数量。<br>
> 因此，在使用这些级别的信息时要小心，因为它们可能无法反映订单簿的完整视图。<br>
> 但是，对于大多数场景，可以每侧看到 5000 个价位就足以了解市场并进行有效交易。
filename:    binance-spot-api-docs-master/web-socket-streams_CN.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## Limits

### Message Limits

* Each connection has a limit on **how many messages can be sent to the exchange**.
* The message limit **does not count the messages sent in response to the client**.
* Breaching the message limit results in immediate [Logout `<5>`](#logout) and disconnection.
* To understand current limits and usage, please send a [LimitQuery`<XLQ>`](#limitquery) message.
  A [LimitResponse`<XLR>`](#limitresponse) message will be sent in response, containing information about Order Rate
  Limits and Message Limits.
* FIX Order entry sessions have a limit of 10,000 messages every 10 seconds.
* FIX Drop Copy sessions have a limit of 60 messages every 60 seconds.
* FIX Market Data sessions have a limit of 2000 messages every 60 seconds.

<a id="connection-limits"></a>

### Connection Limits

* Each Account has a limit on how many TCP connections can be established at the same time.
* The limit is reduced when the TCP connection is closed. If the reduction of connections is not immediate, please wait up to twice the value of `HeartBtInt (108)` for the change to take effect.
  For example, if the current value of `HeartBtInt` is 5, please wait up to 10 seconds.
* Upon breaching the limit a [Reject `<3>`](#reject) will be sent containing information about the connection limit
  breach and the current limit.
* FIX Order Entry limits:
   * 15 connection attempts within 30 seconds
   * Maximum of 10 concurrent TCP connections per account
* FIX Drop Copy limits:
    * 15 connection attempts within 30 seconds
    * Maximum of 10 concurrent TCP connections per account
* FIX Market Data limits
  * 300 connection attempts within 300 seconds
  * Maximum of 100 concurrent TCP connections per account
  * A single connection can listen to a maximum of 1000 streams.

### Unfilled Order Count

* To understand how many orders you have placed within a certain time interval, please send a [LimitQuery`<XLQ>`](#limitquery) message.
  A [LimitResponse`<XLR>`](#limitresponse) message will be sent in response, containing information about Unfilled Order Count and Message Limits.
* **Please note that if your orders are consistently filled by trades, you can continuously place orders on the API**. For more information, please see [Spot Unfilled Order Count Rules](../faqs/order_count_decrement.md).
* If you exceed the unfilled order count your message will be rejected, and information will be transferred back to you in a reject message specific to that endpoint.
* **The number of unfilled orders is tracked for each account.**
filename:    binance-spot-api-docs-master/testnet/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## LIMITS

### General Info on Limits
* The following `intervalLetter` values for headers:
    * SECOND => S
    * MINUTE => M
    * HOUR => H
    * DAY => D
* `intervalNum` describes the amount of the interval. For example, `intervalNum` 5 with `intervalLetter` M means "Every 5 minutes".
* The `/api/v3/exchangeInfo` `rateLimits` array contains objects related to the exchange's `RAW_REQUESTS`, `REQUEST_WEIGHT`, and `ORDERS` rate limits. These are further defined in the `ENUM definitions` section under `Rate limiters (rateLimitType)`.
* Requests fail with HTTP status code 429 when you exceed the request rate limit.

### IP Limits
* Every request will contain `X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter)` in the response headers which has the current used weight for the IP for all request rate limiters defined.
* Each route has a `weight` which determines for the number of requests each endpoint counts for. Heavier endpoints and endpoints that do operations on multiple symbols will have a heavier `weight`.
* When a 429 is received, it's your obligation as an API to back off and not spam the API.
* **Repeatedly violating rate limits and/or failing to back off after receiving 429s will result in an automated IP ban (HTTP status 418).**
* IP bans are tracked and **scale in duration** for repeat offenders, **from 2 minutes to 3 days**.
* A `Retry-After` header is sent with a 418 or 429 responses and will give the **number of seconds** required to wait, in the case of a 429, to prevent a ban, or, in the case of a 418, until the ban is over.
* **The limits on the API are based on the IPs, not the API keys.**

### Unfilled Order Count
* Every successful order response will contain a `X-MBX-ORDER-COUNT-(intervalNum)(intervalLetter)` header indicating how many orders you have placed for that interval. <br></br> To monitor this, refer to [`GET api/v3/rateLimit/order`](#query-unfilled-order-count).
* Rejected/unsuccessful orders are not guaranteed to have `X-MBX-ORDER-COUNT-**` headers in the response.
* If you have exceeded this, you will receive a 429 error with the `Retry-After` header.
* **Please note that if your orders are consistently filled by trades, you can continuously place orders on the API**. For more information, please see [Spot Unfilled Order Count Rules](../faqs/order_count_decrement.md).
* **The number of unfilled orders is tracked for each account.**
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## General Information on Endpoints

* For `GET` endpoints, parameters must be sent as a `query string`.
* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a
  `query string` or in the `request body` with content type
  `application/x-www-form-urlencoded`. You may mix parameters between both the
  `query string` and `request body` if you wish to do so.
* Parameters may be sent in any order.
* If a parameter sent in both the `query string` and `request body`, the
  `query string` parameter will be used.
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## Error Codes

* Any endpoint can return an ERROR

Sample Payload below:
```javascript
{
    "code": -1121,
    "msg": "Invalid symbol."
}
```
* Specific error codes and messages are defined in [Errors Codes](./errors.md).
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

In [23]:
preview_results(hybrid_search("Why am I getting timestamp error?"))

Result #1
title:
section:     ## Error Codes

* Any endpoint can return an ERROR

Sample Payload below:
```javascript
{
    "code": -1121,
    "msg": "Invalid symbol."
}
```
* Specific error codes and messages are defined in [Errors Codes](./errors.md).
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## Error Codes

* Any endpoint can return an ERROR

Sample Payload below:
```javascript
{
    "code": -1121,
    "msg": "Invalid symbol."
}
```
* Specific error codes and messages are defined in [Errors Codes](./errors.md).
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## 追踪止盈止损下单示例

假设当前最新价是40,000.

下一个追踪止损(`STOP_LOSS_LIMIT`)的买单, 设置价格为42,000, 追踪价差（`trailingDelta`)为5%.

```bash
# 不设置止损价(stop price)
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=42000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'

# 设置止损价(stop price)43,000
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=42000&stopPrice=43000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'
```

下一个追踪止损(`STOP_LOSS_LIMIT`)的卖单, 设置价格为37,500, 追踪价差（`trailingDelta`)为2.5%.

```bash
# 不设置止损价(stop price)
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=37500&trailingDelta=250&timestamp=<timestamp>&signature=<signature>'

# 设置止损价(stop price)39,000
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=37500&stopPrice=39000&trailingDelta=250&timestamp=<timestamp>&signature=<signature>'
```

下一个追踪止盈(`TAKE_PROFIT_LIMIT`)的买单, 设置价格为38,000, 追踪价差（`trailingDelta`)为5%.

```bash
# 不设置止盈价(stop price)
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=38000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'

# 设置止盈价(stop price)36,000
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=38000&stopPrice=36000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'
```

下一个追踪止盈(`TAKE_PROFIT_LIMIT`)的卖单, 设置价格为41,500, 追踪价差（`trailingDelta`)为1.75%.

```bash
# 不设置止盈价(stop price)
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=41500&trailingDelta=175&timestamp=<timestamp>&signature=<signature>'

# 设置止盈价(stop price) 42,500
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=41500&stopPrice=42500&trailingDelta=175&timestamp=<timestamp>&signature=<signature>'
```
filename:    binance-spot-api-docs-master/faqs/trailing-stop-faq_CN.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## Trailing Stop Order Examples

Assuming a last price of 40,000.

Placing a trailing stop `STOP_LOSS_LIMIT BUY` order, with a price of 42,000.0 and a trailing stop of 5%.
```bash
# Excluding stop price
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=42000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'

# Including stop price of 43,000
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=42000&stopPrice=43000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'
```

Placing a trailing stop `STOP_LOSS_LIMIT SELL` order, with a price of 37,500.0 and a trailing stop of 2.5%.
```bash
# Excluding stop price
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=37500&trailingDelta=250&timestamp=<timestamp>&signature=<signature>'

# Including stop price of 39,000
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=STOP_LOSS_LIMIT&timeInForce=GTC&quantity=0.01&price=37500&stopPrice=39000&trailingDelta=250&timestamp=<timestamp>&signature=<signature>'
```

Placing a trailing stop `TAKE_PROFIT_LIMIT BUY` order, with a price of 38,000.0 and a trailing stop of 5%.

```bash
# Excluding stop price
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=38000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'

# Including stop price of 36,000
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=BUY&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=38000&stopPrice=36000&trailingDelta=500&timestamp=<timestamp>&signature=<signature>'
```

Placing a trailing stop `TAKE_PROFIT_LIMIT SELL` order, with a price of 41,500.0 and a trailing stop of 1.75%.
```bash
# Excluding stop price
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=41500&trailingDelta=175&timestamp=<timestamp>&signature=<signature>'

# Including stop price of 42,500
POST 'https://api.binance.com/api/v3/order?symbol=BTCUSDT&side=SELL&type=TAKE_PROFIT_LIMIT&timeInForce=GTC&quantity=0.01&price=41500&stopPrice=42500&trailingDelta=175&timestamp=<timestamp>&signature=<signature>'
```
filename:    binance-spot-api-docs-master/faqs/trailing-stop-faq.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## Error Handling

Client messages that contain syntax errors, missing required fields, or refer to unknown symbols will be rejected by the server with a [Reject `<3>`](#reject) message.

If a valid message cannot be processed and is rejected, an appropriate reject response will be sent.
Please refer to the individual message documentation for possible responses.

Please refer to the `Text (58)` and `ErrorCode (25016)` fields in responses for the reject reason.

The list of error codes can be found on the [Error codes](errors.md) page.
filename:    binance-spot-api-docs-master/testnet/fix-api.md
chunk:
--------------------------------------------------------------------------------

In [24]:
#Text search works well for exact Binance terms like recvWindow, timestamp, and endpoint names.
#TVector search helps when the question is paraphrased.
#THybrid search is the safest overall.
#TFor this project, I would start with text search and keep hybrid as the stronger production option.

In [25]:
print([name for name in dir() if "search" in name.lower()])

['VectorSearch', 'hybrid_search', 'text_search', 'vector_search']

In [26]:
import inspect

print(inspect.signature(text_search))
print(inspect.signature(vector_search))
print(inspect.signature(hybrid_search))

(query, num_results=5)
(query, num_results=5)
(query, num_results=5)

In [27]:
def hybrid_search(query: str, num_results: int = 5):
    text_results = text_search(query)
    vector_results = vector_search(query, num_results=num_results)

    seen_ids = set()
    combined = []

    for r in text_results + vector_results:
        if isinstance(r, dict):
            rid = r.get("id") or r.get("chunk_id") or str(r)
        else:
            rid = str(r)

        if rid not in seen_ids:
            seen_ids.add(rid)
            combined.append(r)

    return combined[:num_results]

In [28]:
print(hybrid_search("authentication"))

[{'id': '297', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/user-data-stream.md', 'section': '## Event Stream Terminated\n\n`eventStreamTerminated` is sent when:\n* [A listen token subscription](https://developers.binance.com/docs/margin_trading/trade-data-stream/Listen-Token-Websocket-API#subscribe-to-user-data-stream-using-listentoken-user_stream) expires due to token expiration.\n* A [logon subscription](https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/authentication-requests#log-in-with-api-key-signed) ends after sending [`session.logout`](https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/authentication-requests#log-out-of-the-session) method.\n* The subscription is stopped via the [`userDataStream.unsubscribe`](https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/user-data-stream-requests#unsubscribe-from-user-data-stream) method.\n\n**Payload:**\n\n```javascript\n{\n    "subscriptionId": 0,\n    "event": {\n        "e": "eventStreamTerminated",     // Event Type\n        "E": 1728973001334                // Event Time\n    }\n}\n```'}, {'id': '301', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/user-data-stream_CN.md', 'section': '## 事件流已终止\n\n此事件仅在订阅 WebSocket API 时显示。\n\n`eventStreamTerminated` 会在以下情况下发送：\n\n* 当 [Listen Token 订阅](https://developers.binance.com/docs/zh-CN/margin_trading/trade-data-stream/Listen-Token-Websocket-API) 因 Token 过期而失效时。\n* 在发送 [`session.logout`](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/websocket-api/authentication-requests#%E9%80%80%E5%87%BA%E4%BC%9A%E8%AF%9D) 方法后，[登录订阅](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/websocket-api/authentication-requests#%E7%94%A8api-key%E7%99%BB%E5%BD%95-signed) 结束时。\n* 通过 [`userDataStream.unsubscribe`](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/websocket-api/user-data-stream-requests#%E5%8F%96%E6%B6%88%E8%AE%A2%E9%98%85%E7%94%A8%E6%88%B7%E6%95%B0%E6%8D%AE%E6%B5%81) 方法终止订阅时。\n\n**Payload:**\n\n```javascript\n{\n    "subscriptionId": 0,\n    "event": {\n        "e": "eventStreamTerminated",     // 事件类型\n        "E": 1728973001334                // 事件时间\n    }\n}\n```'}, {'id': '269', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/testnet/web-socket-api.md', 'section': '## Session Authentication\n\n**Note:** Only _Ed25519_ keys are supported for this feature.\n\nIf you do not want to specify `apiKey` and `signature` in each individual request,\nyou can authenticate your API key for the active WebSocket session.\n\nOnce authenticated, you no longer have to specify `apiKey` and `signature` for those requests that need them.\nRequests will be performed on behalf of the account owning the authenticated API key.\n\n**Note:** You still have to specify the `timestamp` parameter for `SIGNED` requests.\n\n### Authenticate after connection\n\nYou can authenticate an already established connection using session authentication requests:\n\n* [`session.logon`](#log-in-with-api-key-signed) – authenticate, or change the API key associated with the connection\n* [`session.status`](#query-session-status) – check connection status and the current API key\n* [`session.logout`](#log-out-of-the-session) – forget the API key associated with the connection\n\n**Regarding API key revocation:**\n\nIf during an active session the API key becomes invalid for _any reason_ (e.g. IP address is not whitelisted, API key was deleted, API key doesn\'t have correct permissions, etc), after the next request the session will be revoked with the following error message:\n\n```javascript\n{\n    "id": null,\n    "status": 401,\n    "error": {\n        "code": -2015,\n        "msg": "Invalid API-key, IP, or permissions for action."\n    }\n}\n```\n\n### Authorize _ad hoc_ requests\n\nOnly one API key can be authenticated with the WebSocket connection.\nThe authenticated API key is used by default for requests that require an `apiKey` parameter.\nHowever, you can always specify the `apiKey` and `signature` explicitly for individual requests,\noverriding the authenticated API key and using a different one to authorize a specific request.\n\nFor example, you might want to authenticate your `USER_DATA` key to be used by default,\nbut specify the `TRADE` key with an explicit signature when placing orders.'}, {'id': '309', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/web-socket-api.md', 'section': '## Session Authentication\n\n**Note:** Only _Ed25519_ keys are supported for this feature.\n\nIf you do not want to specify `apiKey` and `signature` in each individual request,\nyou can authenticate your API key for the active WebSocket session.\n\nOnce authenticated, you no longer have to specify `apiKey` and `signature` for those requests that need them.\nRequests will be performed on behalf of the account owning the authenticated API key.\n\n**Note:** You still have to specify the `timestamp` parameter for `SIGNED` requests.\n\n### Authenticate after connection\n\nYou can authenticate an already established connection using session authentication requests:\n\n* [`session.logon`](#log-in-with-api-key-signed) – authenticate, or change the API key associated with the connection\n* [`session.status`](#query-session-status) – check connection status and the current API key\n* [`session.logout`](#log-out-of-the-session) – forget the API key associated with the connection\n\n**Regarding API key revocation:**\n\nIf during an active session the API key becomes invalid for _any reason_ (e.g. IP address is not whitelisted, API key was deleted, API key doesn\'t have correct permissions, etc), after the next request the session will be revoked with the following error message:\n\n```javascript\n{\n    "id": null,\n    "status": 401,\n    "error": {\n        "code": -2015,\n        "msg": "Invalid API-key, IP, or permissions for action."\n    }\n}\n```\n\n### Authorize _ad hoc_ requests\n\nOnly one API key can be authenticated with the WebSocket connection.\nThe authenticated API key is used by default for requests that require an `apiKey` parameter.\nHowever, you can always specify the `apiKey` and `signature` explicitly for individual requests,\noverriding the authenticated API key and using a different one to authorize a specific request.\n\nFor example, you might want to authenticate your `USER_DATA` key to be used by default,\nbut specify the `TRADE` key with an explicit signature when placing orders.'}, {'id': '313', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/web-socket-api.md', 'section': '## Authentication requests\n\n**Note:** Only _Ed25519_ keys are supported for this feature.\n\n<a id="session-logon"></a>\n\n### Log in with API key (SIGNED)\n\n```javascript\n{\n    "id": "c174a2b1-3f51-4580-b200-8528bd237cb7",\n    "method": "session.logon",\n    "params": {\n        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",\n        "signature": "1cf54395b336b0a9727ef27d5d98987962bc47aca6e13fe978612d0adee066ed",\n        "timestamp": 1649729878532\n    }\n}\n```\n\nAuthenticate WebSocket connection using the provided API key.\n\nAfter calling `session.logon`, you can omit `apiKey` and `signature` parameters for future requests that require them.\n\nNote that only one API key can be authenticated.\nCalling `session.logon` multiple times changes the current authenticated API key.\n\n**Weight:**\n2\n\n**Parameters:**\n\nName          | Type    | Mandatory | Description\n------------- | ------- | --------- | ------------\n`apiKey`      | STRING  | YES       |\n`recvWindow`  | DECIMAL | NO        | The value cannot be greater than `60000`. <br> Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.\n`signature`   | STRING  | YES       |\n`timestamp`   | LONG    | YES       |\n\n**Data Source:**\nMemory\n\n**Response:**\n\n```javascript\n{\n    "id": "c174a2b1-3f51-4580-b200-8528bd237cb7",\n    "status": 200,\n    "result": {\n        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",\n        "authorizedSince": 1649729878532,\n        "connectedSince": 1649729873021,\n        "returnRateLimits": false,\n        "serverTime": 1649729878630,\n        "userDataStream": false // is User Data Stream subscription active?\n    }\n}\n```\n\n<a id="session-status"></a>\n\n### Query session status\n\n```javascript\n{\n    "id": "b50c16cd-62c9-4e29-89e4-37f10111f5bf",\n    "method": "session.status"\n}\n```\n\nQuery the status of the WebSocket connection,\ninspecting which API key (if any) is used to authorize requests.\n\n**Weight:**\n2\n\n**Parameters:**\nNONE\n\n**Data Source:**\nMemory\n\n**Response:**\n\n```javascript\n{\n    "id": "b50c16cd-62c9-4e29-89e4-37f10111f5bf",\n    "status": 200,\n    "result": {\n        // if the connection is not authenticated, "apiKey" and "authorizedSince" will be shown as null\n        "apiKey": "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",\n        "authorizedSince": 1649729878532,\n        "connectedSince": 1649729873021,\n        "returnRateLimits": false,\n        "serverTime": 1649730611671,\n        "userDataStream": true     // is User Data Stream subscription active?\n    }\n}\n```\n\n### Log out of the session\n\n```javascript\n{\n    "id": "c174a2b1-3f51-4580-b200-8528bd237cb7",\n    "method": "session.logout"\n}\n```\n\nForget the API key previously authenticated.\nIf the connection is not authenticated, this request does nothing.\n\nNote that the WebSocket connection stays open after `session.logout` request.\nYou can continue using the connection,\nbut now you will have to explicitly provide the `apiKey` and `signature` parameters where needed.\n\n**Weight:**\n2\n\n**Parameters:**\nNONE\n\n**Data Source:**\nMemory\n\n**Response:**\n\n```javascript\n{\n    "id": "c174a2b1-3f51-4580-b200-8528bd237cb7",\n    "status": 200,\n    "result": {\n        "apiKey": null,\n        "authorizedSince": null,\n        "connectedSince": 1649729873021,\n        "returnRateLimits": false,\n        "serverTime": 1649730611671,\n        "userDataStream": false // is User Data Stream subscription active?\n    }\n}\n```'}]

In [29]:
def search_docs(query: str) -> str:
    """
    Search the Binance documentation using hybrid search.
    """
    results = hybrid_search(query, num_results=5)

    formatted = []
    for i, r in enumerate(results, 1):
        if isinstance(r, dict):
            text = r.get("text") or r.get("content") or str(r)
        else:
            text = str(r)
        formatted.append(f"Result {i}:\n{text}\n")

    return "\n".join(formatted)

In [30]:
from pydantic_ai import Agent

system_prompt_v1 = """
You are a Binance documentation assistant.

Always use the search_docs tool before answering questions.
Base your answer only on the retrieved documentation.
If the answer is not found, say that clearly.
Do not guess.
"""

agent_v1 = Agent(
    name="binance_agent_v1",
    instructions=system_prompt_v1,
    tools=[search_docs],
    model="gpt-4o-mini"
)

In [31]:
from pydantic_ai import Agent

system_prompt_v2 = """
You are a Binance documentation assistant.

Always use the search_docs tool before answering questions.
Base your answer on the retrieved Binance documentation.
Do not guess when the retrieved results are weak or unclear.

When answering:
- give a direct answer first
- mention important parameters or requirements
- mention authentication/signing requirements if relevant
- cite the filename or section used
""".strip()

agent_v2 = Agent(
    name="binance_agent_v2",
    instructions=system_prompt_v2,
    tools=[search_docs],
    model="gpt-4o-mini"
)

In [32]:
question = "How do I authenticate API requests?"

result_v1 = await agent_v1.run(question)
print("V1:\n", result_v1.output)

result_v2 = await agent_v2.run(question)
print("\nV2:\n", result_v2.output)

V1:
 To authenticate API requests on Binance, you need to follow these key steps:

1. **API Keys**: You need an API key and secret. These can be obtained from your Binance account.

2. **Signature**: For secured API endpoints, you must create a signature using your API secret. This signature is a hashed value created based on the parameters sent in the request, along with a timestamp.

3. **Authenticated Requests**: For authenticated requests, you must include the following parameters in your API call:
   - `apiKey`: Your public API key.
   - `signature`: The generated signature.
   - `timestamp`: The current timestamp (in milliseconds).

4. **Using WebSocket**: If you are using the WebSocket API, you can authenticate your API key after the connection is established. You can do so with the `session.logon` method. After authentication, you can omit the `apiKey` and `signature` for future requests that require them.

5. **Revoke API Key**: If your API key becomes invalid for any reason (such as permissions issues or IP not whitelisted), the session will be revoked, and errors will occur on further requests.

For more details, refer to the specific sections in the Binance API documentation regarding authentication and session management.

V2:
 To authenticate API requests to the Binance API, you primarily need to use an `apiKey` and a `signature`, along with a `timestamp`.

### Key Requirements:
1. **Parameters**:
   - `apiKey`: Your API key (mandatory).
   - `signature`: A generated signature for the request (mandatory).
   - `timestamp`: A timestamp of the request (mandatory, in milliseconds since Unix epoch).
   - Optionally, you may also use `recvWindow`, which specifies the allowed time for the request to be processed (defaults to 5000 ms but should not exceed 60000 ms).

2. **Generation of Signature**:
   - The signature should be generated using HMAC SHA256 on your request query string (i.e., concatenating all parameters in the format `key1=value1&key2=value2...`).

3. **Authentication Flow**:
   - For session-based authentication in WebSocket connections, you can first authenticate by executing `session.logon`, which allows you to omit `apiKey` and `signature` for future requests within that session.

4. **Error Handling**:
   - If authentication fails (e.g., due to permission issues or an invalid API key), you'll receive a response with an error code -2015 indicating invalid credentials.

### Authentication Example:
When using the REST API, a typical request for logging in might look like this:

```plaintext
GET /api/v3/account?timestamp=1632027906000&signature=YOUR_GENERATED_SIGNATURE
```

### Authentication URL:
- **Base URL**: All endpoints should be called using the base URL for the Binance API: `https://api.binance.com`.

### Authentication mechanism used:
- Ensure that your API key has the necessary permissions based on the operations you wish to perform (SPOT, MARGIN, etc.).

For more details, refer to the section on General endpoints in the Binance REST API documentation (filename: `binance-spot-api-docs-master/rest-api.md`).

In [102]:
%%writefile logging_utils.py
import json
import secrets
from pathlib import Path
from datetime import datetime
from pydantic_ai.messages import ModelMessagesTypeAdapter

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

def serializer(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")

def log_entry(agent, messages, source="user", version=None):
    tools = []
    for ts in agent.toolsets:
        tools.extend(ts.tools.keys())

    dict_messages = ModelMessagesTypeAdapter.dump_python(messages)

    return {
        "agent_name": agent.name,
        "agent_version": version,
        "system_prompt": agent._instructions,
        "provider": agent.model.system,
        "model": agent.model.model_name,
        "tools": tools,
        "messages": dict_messages,
        "source": source,
    }

def log_interaction_to_file(agent, messages, source="user", version=None):
    entry = log_entry(agent, messages, source, version)

    ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    rand_hex = secrets.token_hex(3)

    filename = f"{agent.name}_{ts_str}_{rand_hex}.json"
    filepath = LOG_DIR / filename

    with filepath.open("w", encoding="utf-8") as f_out:
        json.dump(entry, f_out, indent=2, default=serializer)

    return filepath

Overwriting logging_utils.py

In [103]:
from importlib import reload
import logging_utils

reload(logging_utils)
from logging_utils import log_interaction_to_file

print("logging_utils reloaded")

logging_utils reloaded

In [35]:
eval_questions = [
    "How do I authenticate API requests?",
    "How do I place a market order?",
    "What parameters are needed to create an order?",
    "How do I check exchange information?",
    "What are Binance API rate limits?",
    "How do I get account balances?",
    "How do I retrieve recent trades for a symbol?",
    "Which endpoints require signed requests?",
    "What is the difference between limit and market order?",
    "How do I cancel an order?"
]

In [36]:
for q in eval_questions:
    print("\n" + "=" * 80)
    print("QUESTION:", q)

    # Run v1
    result_v1 = await agent_v1.run(q)
    print("\nV1 ANSWER:")
    print(result_v1.output)

    log_file_v1 = log_interaction_to_file(
        agent_v1,
        result_v1.new_messages(),
        source="user",
        version="v1"
    )
    print("Saved V1 log:", log_file_v1)

    # Run v2
    result_v2 = await agent_v2.run(q)
    print("\nV2 ANSWER:")
    print(result_v2.output)

    log_file_v2 = log_interaction_to_file(
        agent_v2,
        result_v2.new_messages(),
        source="user",
        version="v2"
    )
    print("Saved V2 log:", log_file_v2)

================================================================================
QUESTION: How do I authenticate API requests?

V1 ANSWER:
To authenticate API requests on Binance, you can use the following method:

1. **API Key and Signature**: For most requests, you will need to include your API key and a signature that is generated based on your API secret.

2. **Session Authentication for WebSocket**:
   - If you are using WebSocket, you can authenticate your API key for an active WebSocket session. After authentication, you don't need to include the `apiKey` and `signature` with each request.
   - You authenticate by sending a session logon request:
     ```javascript
     {
         "id": "your-request-id",
         "method": "session.logon",
         "params": {
             "apiKey": "your-api-key",
             "signature": "your-generated-signature",
             "timestamp": your-current-timestamp
         }
     }
     ```
   - After calling `session.logon`, you can omit `apiKey` and `signature` parameters for subsequent requests.

3. **Session Management**:
   - To check your connection status and the current API key, you can use:
     ```javascript
     {
         "id": "your-request-id",
         "method": "session.status"
     }
     ```
   - To log out and forget the authenticated API key, you can send:
     ```javascript
     {
         "id": "your-request-id",
         "method": "session.logout"
     }
     ```

4. **Important Notes**:
   - Make sure that the `timestamp` parameter is included in all signed requests.
   - If your API key becomes invalid during a session, the session will be revoked, and subsequent requests will result in an error.

For detailed examples and parameters, refer to the documentation on session authentication and general request authentication methods.
Saved V1 log: logs/binance_agent_v1_20260328_013249_2e2397.json

V2 ANSWER:
To authenticate API requests on Binance, you will primarily need to use the following methods:

1. **API Key and Signature**: Most API requests that require authentication must include an `apiKey` and a `signature`. The `signature` is generated by HMAC SHA256 signing the query string with your secret key.

   - Important parameters:
     - `apiKey`: Your unique API key.
     - `timestamp`: The timestamp of the request (in milliseconds).
     - `signature`: The computed signature as per your secret key.

2. **Using Session Authentication for WebSocket**: You can authenticate your API key for active WebSocket sessions, which allows you to avoid specifying `apiKey` and `signature` in each individual request after the initial login.

   - Required requests for session authentication:
     - `session.logon`: Used to authenticate your API key.
     - You will still need to send the `timestamp` parameter for signed requests.

   Here’s an example of the `session.logon` request:

   ```json
   {
       "id": "your-id",
       "method": "session.logon",
       "params": {
           "apiKey": "your-api-key",
           "signature": "your-signature",
           "timestamp": 1649729878532
       }
   }
   ```

   After successfully logging in, you can omit the `apiKey` and `signature` in subsequent requests until you log out or your session expires.

### Authentication Requirements
- **Authentication Type**: Must include `apiKey` and `signature` for each signed request.
- **Session Management**: For sessions, proper handling of `session.logon`, `session.status`, and `session.logout` is necessary.
- **Signature Generation**: Ensure to generate the signature properly, using your secret key with the respective API request parameters.

### Documentation Reference
- The information is sourced from the WebSocket API documentation (sections on Session Authentication and Authentication requests) in the Binance API documentation provided [here](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md).
Saved V2 log: logs/binance_agent_v2_20260328_013309_443f93.json

================================================================================
QUESTION: How do I place a market order?

V1 ANSWER:
The search did not return any relevant information on how to place a market order on Binance. Therefore, I cannot provide you with an answer based on the documentation.
Saved V1 log: logs/binance_agent_v1_20260328_013310_06c4bb.json

V2 ANSWER:
To place a market order on Binance via the API, you can follow the steps below.

### Direct Approach:
1. **Endpoint:** Use the `POST /api/v3/order` endpoint.
2. **Parameters:**
   - **symbol:** Required (string) - Specify the trading pair (e.g., `BTCUSDT`).
   - **side:** Required (enum) - Must be `BUY` or `SELL`.
   - **type:** Required (enum) - Set to `MARKET`.
   - **quantity:** Required (decimal) - The amount of the asset you want to buy/sell. You can alternatively specify `quoteOrderQty` (amount in quote currency) instead of `quantity`, but not both.
3. **Optional Parameters:** Additional parameters may include `newClientOrderId`, `timeInForce`, and `selfTradePreventionMode`.
4. **Authentication:** You need to sign the request with a valid API key, and include a `timestamp` parameter.

### Example of a Request:
Here’s a JSON body example for a market buy order of `0.5 BTC`:
```json
{
  "symbol": "BTCUSDT",
  "side": "BUY",
  "type": "MARKET",
  "quantity": "0.5",
  "timestamp": "YOUR_CURRENT_TIMESTAMP"
}
```

### Authentication Note:
- Each API request must include a valid API key in the `X-MBX-APIKEY` header.
- The request must also be signed with the proper signature based on your API key.

### Rate Limits:
Be aware of the API’s rate limits when making requests. Keep track of the `weight` assigned to each request to avoid hitting rate limits.

For detailed implementation, refer to [the Binance API documentation on Orders](https://binance-docs.github.io/apidocs/spot/en/#new-order).

**Cited From:** General Endpoints and Trading Endpoints sections from the Binance API documentation (filename: 'binance-spot-api-docs-master/rest-api.md').
Saved V2 log: logs/binance_agent_v2_20260328_013342_d5c32d.json

================================================================================
QUESTION: What parameters are needed to create an order?

V1 ANSWER:
To create an order on Binance, you need the following parameters:

1. **symbol** (STRING) - (Mandatory) The market to which the order corresponds (e.g., "BTCUSDT").
2. **side** (ENUM) - (Mandatory) The side of the order, which can be either BUY or SELL.
3. **type** (ENUM) - (Mandatory) The type of order. Common types include LIMIT, MARKET, etc.
4. **quantity** (DECIMAL) - (Optional) The amount of the asset you want to buy or sell.
5. **quoteOrderQty** (DECIMAL) - (Optional) The total amount of quote asset to spend or receive.
6. **price** (DECIMAL) - (Optional) The price at which to buy or sell. Required if the order type is LIMIT.
7. **timeInForce** (ENUM) - (Optional) How long the order will remain active. Can be GTC (Good Till Cancelled), IOC (Immediate Or Cancel), or FOK (Fill Or Kill).
8. **newClientOrderId** (STRING) - (Optional) A unique order ID among open orders.
9. **stopPrice** (DECIMAL) - (Optional) Used for STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.
10. **icebergQty** (DECIMAL) - (Optional) Used to create an iceberg order with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT.
11. **newOrderRespType** (ENUM) - (Optional) Set the response JSON format: ACK, RESULT, or FULL.
12. **selfTradePreventionMode** (ENUM) - (Optional) The allowed enums depend on what is configured on the symbol.
13. **recvWindow** (DECIMAL) - (Optional) The value cannot exceed 60000. This parameter supports milliseconds to define the request time window.
14. **timestamp** (LONG) - (Mandatory) The timestamp of the request in milliseconds.

Certain additional parameters are required based on the order type you choose, such as those specific to LIMIT or MARKET orders.

For full details, see the [New Order API documentation](https://binance-docs.github.io/apidocs/spot/en/#new-order) for exact parameter specifications and constraints.
Saved V1 log: logs/binance_agent_v1_20260328_013415_e5fa55.json

V2 ANSWER:
To create an order on Binance, the following parameters are required:

### Mandatory Parameters
1. **symbol**: The trading pair to trade (e.g., "BTCUSDT").
2. **side**: The side of the order, which can be either "BUY" or "SELL".
3. **type**: The order type (e.g., "LIMIT", "MARKET").
4. **timestamp**: Current time in milliseconds since epoch (mandatory for signing the request).

### Optional Parameters
1. **timeInForce**: This parameter is only mandatory for LIMIT orders. Possible values are "GTC" (Good Till Canceled), "IOC" (Immediate or Cancel), and "FOK" (Fill or Kill).
2. **quantity**: The amount of the asset to buy/sell.
3. **price**: Price for the order (mandatory for LIMIT orders).
4. **newClientOrderId**: An optional unique identifier for the order.
5. **stopPrice**: Required for stop-limit and stop loss orders.
6. **icebergQty**: This creates an iceberg order specified as a quantity visible to the exchange.
7. **quoteOrderQty**: The amount to spend or receive in the quote asset.
8. **newOrderRespType**: Determines the response format (ACK, RESULT, FULL).

### Authentication/Signing Requirements
- The request must be signed using your API secret. The signature is computed based on the request parameters, excluding the `signature` field itself.
- You must include the `timestamp` parameter, which should match the server’s time within a reasonable window specified by `recvWindow` (default is 5000ms).

For additional details, you can reference the "New Order (TRADE)" section in the Binance API documentation (filename: `rest-api.md`, section: "### New order (TRADE)").
Saved V2 log: logs/binance_agent_v2_20260328_013441_4159f5.json

================================================================================
QUESTION: How do I check exchange information?

V1 ANSWER:
The search did not yield specific instructions on how to check exchange information. It mentioned that exchange information can be found in the context of order amendments but did not provide a direct method for accessing this data. If you need detailed guidelines or steps, please let me know!
Saved V1 log: logs/binance_agent_v1_20260328_013444_d06064.json

V2 ANSWER:
To check exchange information on Binance, you can use the relevant API endpoints provided in their documentation. Specifically, the exchange information includes details like supported trading pairs, order types, filters, and limits.

### Key Parameters:
- The API endpoint you would typically use is `GET /api/v3/exchangeInfo`.
- This endpoint returns data on trading pairs, including their status, filters, and other relevant details.

### Authentication:
- Depending on the specifics of your request, you may need to include a valid API key for authenticated endpoints.

For more details, you may refer to the corresponding section in the Binance API documentation if you need exact endpoint usage: typically found under exchange information or market data sections. Unfortunately, specific details on retrieving exchange information weren't retrieved directly in the search results, but you can find this information in the comprehensive API docs.
Saved V2 log: logs/binance_agent_v2_20260328_013447_bc8e7f.json

================================================================================
QUESTION: What are Binance API rate limits?

V1 ANSWER:
Binance API rate limits are characterized by several key points:

1. **Connection Limits**: There is a limit of **300 connections per attempt every 5 minutes** per IP address.

2. **Rate Limits Description**:
   - There are multiple types of rate limits across various intervals (e.g., per second, minute, hour, day).
   - You can use the `exchangeInfo` request to query the current API rate limits.
   - Requests that exceed the rate limits will fail with an HTTP status code `429`.

3. **Rate Limits Type**:
   - Rate limits are described in a `rateLimits` array in the response which contains:
     - `rateLimitType`: type of the limit (e.g., `REQUEST_WEIGHT`, `ORDERS`).
     - `interval`: time unit of the limit (e.g., `SECOND`, `MINUTE`).
     - `intervalNum`: frequency of the interval.
     - `limit`: maximum allowed requests within the interval.
     - `count`: current usage within the interval.

4. **Weights**:
   - Every request has a specific weight, and when combined with all requests from an IP, it counts towards your limit.
   - If the weight limit is exceeded, requests fail with a `429` error.

5. **IP Limits**:
   - The rate limits are applied per IP address and not per API key. If you repeatedly violate the rate limits, there's a risk of an automated IP ban.

6. **Unfilled Order Count**:
   - There are limits on how many unfilled orders can be placed, with responses providing information about the current count and limits.

7. **Ban Duration**:
   - If you are banned for violating rate limits, the duration scales from **2 minutes to up to 3 days** based on repeated offenses.

For more detailed information, you can refer to the specific API documentation.
Saved V1 log: logs/binance_agent_v1_20260328_013458_6e6639.json

V2 ANSWER:
Binance API has defined rate limits to manage overall traffic and ensure optimal performance. Here are the key aspects:

1. **Connection Limits**:
   - There is a limit of **300 connections per attempt every 5 minutes** for each IP address.

2. **Rate Limit Types**:
   - Various rate limit types exist, including `REQUEST_WEIGHT` and `ORDERS`. You can query the current limits using the `exchangeInfo` request.

3. **General Rate Limit Rules**:
   - Requests can fail with a status code `429` if rate limits are exceeded.
   - Responses may include a `rateLimits` field detailing the usage and limits.
   - The rate limit intervals can be per second, minute, hour, or day.

4. **Weightage for Requests**:
   - Each API request has an associated weight, which is summed up per IP address.
   - If the weight limit is exceeded, requests will again fail with a status `429`.

5. **Unfilled Order Count**:
   - There are also limits on the number of unfilled orders you can place. Exceeding these can lead to a `429` status as well.

6. **IP Banning**:
   - Repeated violations of requests can lead to an automated IP ban, which lasts from 2 minutes to 3 days based on the severity of the offense.

7. **Necessary Authentication**:
   - Authentication might be required for certain endpoints depending on the API keys used.

For a comprehensive understanding, you may refer to the Binance API documentation, specifically the section on [Rate Limits](https://binance-docs.github.io/apidocs/spot/en/#limits) (found in binance-spot-api-docs-master/web-socket-api.md).
Saved V2 log: logs/binance_agent_v2_20260328_013506_600f09.json

================================================================================
QUESTION: How do I get account balances?

V1 ANSWER:
To get your account balances on Binance, you can use the following API endpoint:

```
GET /api/v3/account
```

### Description:
This endpoint allows you to check your account information, including all asset balances and whether they are free, locked, or in a pending state.

### Weight:
The weight for this request is 10.

### Parameters:
This endpoint does not require any parameters.

### Sample Response:
The response will include detailed information about your account's balances:
```json
{
    "makerCommission": 15,
    "takerCommission": 15,
    "buyerCommission": 0,
    "sellerCommission": 0,
    "canTrade": true,
    "canWithdraw": true,
    "canDeposit": true,
    "updateTime": 1570662192902,
    "accountType": "SPOT",
    "balances": [
        {
            "asset": "BTC",
            "free": "0.00000000",
            "locked": "0.00000000"
        },
        {
            "asset": "ETH",
            "free": "0.00000000",
            "locked": "0.00000000"
        },
        // Other assets...
    ],
    // Other metadata...
}
```

Make sure to authenticate your request using your API key and secret.
Saved V1 log: logs/binance_agent_v1_20260328_013525_c50e57.json

V2 ANSWER:
To get your account balances on Binance, you can use the following REST API endpoint:

**Endpoint:**
```
GET /api/v3/account
```

### Important Parameters:
- **symbol**: (Optional) If you want to get data for a specific symbol.
- **omitZeroBalances**: (Optional) If set to `true`, it will hide all assets with zero balances.

### Authentication Requirements:
- This endpoint requires an API key and must be signed. You will need to set up your headers to include your API key and a signature.

### Example of Response:
The response will include details about your account such as:
- `balances`: This is an array containing objects that provide information about each asset, including `asset`, `free` (amount available for trading), and `locked` (amount that is currently locked).

Example response structure:
```json
{
    "makerCommission": 15,
    "takerCommission": 15,
    "buyerCommission": 0,
    "sellerCommission": 0,
    "canTrade": true,
    "canWithdraw": true,
    "canDeposit": true,
    "updateTime": 1568900723076,
    "accountType": "SPOT",
    "balances": [
        {
            "asset": "BTC",
            "free": "0.001",
            "locked": "0.000"
        },
        {
            "asset": "ETH",
            "free": "0.000",
            "locked": "0.000"
        }
    ]
}
```

### Documentation Reference:
For more details, please refer to the Binance API documentation under the section for account information: [Account Information](https://developers.binance.com/docs/binance-spot-api-docs/reference/account/account).

Additionally, make sure that your API key has the required permissions enabled to access account data.
Saved V2 log: logs/binance_agent_v2_20260328_013552_b47ac4.json

================================================================================
QUESTION: How do I retrieve recent trades for a symbol?

Traceback (most recent call last):
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 740, in _completions_create
    return await self.client.chat.completions.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/openai/resources/chat/completions/completions.py", line 2714, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1884, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1669, in request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3745, in run_code
    await eval(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_69518/2331500512.py", line 6, in <module>
    result_v1 = await agent_v1.run(q)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/agent/abstract.py", line 330, in run
    node = await agent_run.next(node)  # pyright: ignore[reportArgumentType]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/run.py", line 356, in next
    return await self._run_node_with_hooks(node, self._advance_graph)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/run.py", line 282, in _run_node_with_hooks
    return await self._wrap_and_advance(run_context, node, step_fn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/run.py", line 262, in _wrap_and_advance
    result = await cap.on_node_run_error(run_context, node=node, error=e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/capabilities/combined.py", line 215, in on_node_run_error
    raise error
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/run.py", line 260, in _wrap_and_advance
    result = await cap.wrap_node_run(run_context, node=node, handler=step_fn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/capabilities/combined.py", line 201, in wrap_node_run
    return await chain(node)
           ^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/run.py", line 238, in _advance_graph
    task = await self._graph_run.next(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_graph/beta/graph.py", line 497, in next
    return await anext(self)
           ^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_graph/beta/graph.py", line 471, in __anext__
    self._next = await self._iterator.asend(self._next)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_graph/beta/graph.py", line 580, in iter_graph
    raise task_result.error
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_graph/beta/graph.py", line 754, in _run_tracked_task
    result = await self._run_task(t_)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_graph/beta/graph.py", line 795, in _run_task
    output = await node.call(step_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_graph/beta/step.py", line 253, in _call_node
    return await node.run(GraphRunContext(state=ctx.state, deps=ctx.deps))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 494, in run
    return await self._make_request(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 666, in _make_request
    model_response = await ctx.deps.root_capability.on_model_request_error(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/capabilities/combined.py", line 276, in on_model_request_error
    raise error
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 658, in _make_request
    model_response = await ctx.deps.root_capability.wrap_model_request(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/capabilities/combined.py", line 262, in wrap_model_request
    return await chain(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 648, in model_handler
    return await ctx.deps.model.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 640, in request
    response = await self._completions_create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 775, in _completions_create
    raise ModelHTTPError(status_code=status_code, model_name=self.model_name, body=e.body) from e
pydantic_ai.exceptions.ModelHTTPError: status_code: 429, model_name: gpt-4o-mini, body: {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}

In [38]:
%%writefile evals.py
import json
from pydantic import BaseModel
from pydantic_ai import Agent


class EvaluationCheck(BaseModel):
    check_name: str
    justification: str
    check_pass: bool


class EvaluationChecklist(BaseModel):
    checklist: list[EvaluationCheck]
    summary: str


evaluation_prompt = """
Use this checklist to evaluate the quality of an AI agent's answer (<ANSWER>)
to a user question (<QUESTION>).
We also include the full interaction log (<LOG>) for analysis.

For each item, check if the condition is met.

Checklist:
- instructions_follow: The agent followed the system instructions
- answer_relevant: The response directly answers the user's question
- answer_clear: The answer is easy to understand and technically correct
- answer_citations: The answer includes references or source filenames/sections when appropriate
- completeness: The answer covers the key parts of the user's request
- tool_call_search: The search_docs tool was used before answering

Output true/false for each check and provide a short explanation.
""".strip()


eval_agent = Agent(
    name="binance_eval_agent",
    model="gpt-4o-mini",
    instructions=evaluation_prompt,
    output_type=EvaluationChecklist,
)


def load_log_file(log_file):
    with open(log_file, "r", encoding="utf-8") as f_in:
        log_data = json.load(f_in)
    log_data["log_file"] = str(log_file)
    return log_data


def simplify_log_messages(messages):
    log_simplified = []

    for m in messages:
        parts = []

        for original_part in m["parts"]:
            part = original_part.copy()
            kind = part["part_kind"]

            if kind == "user-prompt" and "timestamp" in part:
                del part["timestamp"]

            if kind == "tool-call" and "tool_call_id" in part:
                del part["tool_call_id"]

            if kind == "tool-return":
                if "tool_call_id" in part:
                    del part["tool_call_id"]
                if "metadata" in part:
                    del part["metadata"]
                if "timestamp" in part:
                    del part["timestamp"]
                part["content"] = "RETURN_RESULTS_REDACTED"

            if kind == "text" and "id" in part:
                del part["id"]

            parts.append(part)

        log_simplified.append({
            "kind": m["kind"],
            "parts": parts
        })

    return log_simplified


user_prompt_format = """
<INSTRUCTIONS>{instructions}</INSTRUCTIONS>
<QUESTION>{question}</QUESTION>
<ANSWER>{answer}</ANSWER>
<LOG>{log}</LOG>
""".strip()


async def evaluate_log_record(log_record):
    messages = log_record["messages"]
    instructions = log_record["system_prompt"]
    question = messages[0]["parts"][0]["content"]
    answer = messages[-1]["parts"][0]["content"]

    log_simplified = simplify_log_messages(messages)
    log_json = json.dumps(log_simplified)

    user_prompt = user_prompt_format.format(
        instructions=instructions,
        question=question,
        answer=answer,
        log=log_json,
    )

    result = await eval_agent.run(user_prompt)
    return result.output

Overwriting evals.py

In [39]:
from evals import load_log_file, evaluate_log_record
from pathlib import Path

LOG_DIR = Path("logs")
print("evals ready")

evals ready

In [44]:
log_files = list(LOG_DIR.glob("*.json"))[:5]

eval_results = []

for log_file in log_files:
    log_record = load_log_file(log_file)
    eval_result = await evaluate_log_record(log_record)
    eval_results.append((log_record, eval_result))

print("Done:", len(eval_results))

Done: 5

In [45]:
log_record = load_log_file(log_files[0])
eval_result = await evaluate_log_record(log_record)

print(eval_result.summary)
for check in eval_result.checklist:
    print(check.check_name, "=>", check.check_pass)
    print("reason:", check.justification)
    print()

The agent's response met all the quality checks, providing a complete and accurate answer to the user's question.
instructions_follow => True
reason: The agent followed the system instructions by using the search_docs tool to retrieve documentation before answering the question.

answer_relevant => True
reason: The response directly answers the user's question about the parameters needed to create an order.

answer_clear => True
reason: The answer is clearly structured, easy to understand, and technically correct regarding the parameters.

answer_citations => True
reason: The answer includes a reference to the New Order API documentation link for further details.

completeness => True
reason: The answer includes a comprehensive list of parameters, covering both mandatory and optional parameters, along with their descriptions.

tool_call_search => True
reason: The search_docs tool was used multiple times to find relevant information before providing an answer, as required.

In [109]:
eval_results = []
failed_logs = []

for log_file in list(LOG_DIR.glob("*.json")):
    try:
        log_record = load_log_file(log_file)
        eval_result = await evaluate_log_record(log_record)
        eval_results.append((log_record, eval_result))
        print("Evaluated:", log_file.name)
    except Exception as e:
        failed_logs.append((log_file.name, str(e)))
        print("Failed:", log_file.name, e)

print("Success:", len(eval_results))
print("Failed:", len(failed_logs))

Evaluated: binance_agent_v1_20260328_013415_e5fa55.json
Evaluated: binance_agent_v2_20260328_013447_bc8e7f.json
Evaluated: binance_agent_v2_20260328_013342_d5c32d.json
Evaluated: binance_agent_v2_20260328_013441_4159f5.json
Evaluated: binance_agent_v2_20260328_013552_b47ac4.json
Evaluated: binance_agent_v1_20260328_013249_2e2397.json
Evaluated: binance_agent_v1_20260328_013444_d06064.json
Evaluated: binance_agent_v1_20260328_013310_06c4bb.json
Evaluated: binance_agent_v2_20260328_020037_def460.json
Evaluated: binance_agent_v2_20260328_015913_e6d64c.json
Evaluated: binance_agent_v2_20260328_015849_f4e2d8.json
Evaluated: binance_agent_v2_20260328_015957_21d203.json
Evaluated: binance_agent_v2_20260328_020033_667c72.json
Evaluated: binance_agent_v1_20260328_013525_c50e57.json
Evaluated: binance_agent_v1_20260328_013458_6e6639.json
Evaluated: binance_agent_v2_20260328_013309_443f93.json
Evaluated: binance_agent_v2_20260328_020011_347f4d.json
Evaluated: binance_agent_v2_20260328_015934_cec8e1.json
Evaluated: binance_agent_v2_20260328_015948_348301.json
Evaluated: binance_agent_v2_20260328_015853_dddd03.json
Evaluated: binance_agent_v2_20260328_013506_600f09.json
Evaluated: binance_agent_v2_20260328_015901_689049.json
Success: 22
Failed: 0

In [110]:
from pathlib import Path
import pandas as pd

rows = []

for log_record, eval_result in eval_results:
    messages = log_record["messages"]

    row = {
        "file": Path(log_record["log_file"]).name,
        "agent_name": log_record.get("agent_name"),
        "agent_version": log_record.get("agent_version"),
        "source": log_record.get("source"),
        "question": messages[0]["parts"][0]["content"],
        "answer": messages[-1]["parts"][0]["content"],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)
    rows.append(row)

df = pd.DataFrame(rows)
df.to_csv("evaluation_results.csv", index=False)

print("saved evaluation_results.csv")
print(df["source"].value_counts())

saved evaluation_results.csv
source
user            12
ai-generated    10
Name: count, dtype: int64

In [111]:
df_user = df[df["source"] == "user"]
df_ai = df[df["source"] == "ai-generated"]

print("User questions:")
print(df_user.mean(numeric_only=True))

print("\nAI-generated questions:")
print(df_ai.mean(numeric_only=True))

User questions:
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.583333
completeness           0.750000
tool_call_search       1.000000
dtype: float64

AI-generated questions:
instructions_follow    1.0
answer_relevant        1.0
answer_clear           1.0
answer_citations       1.0
completeness           1.0
tool_call_search       1.0
dtype: float64

In [112]:
%%writefile logging_utils.py
import json
import secrets
from pathlib import Path
from datetime import datetime
from pydantic_ai.messages import ModelMessagesTypeAdapter

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

def serializer(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")

def log_entry(agent, messages, source="user"):
    tools = []
    for ts in agent.toolsets:
        tools.extend(ts.tools.keys())

    dict_messages = ModelMessagesTypeAdapter.dump_python(messages)

    return {
        "agent_name": agent.name,
        "system_prompt": agent._instructions,
        "provider": agent.model.system,
        "model": agent.model.model_name,
        "tools": tools,
        "messages": dict_messages,
        "source": source,
    }

def log_interaction_to_file(agent, messages, source="user"):
    entry = log_entry(agent, messages, source)

    ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    rand_hex = secrets.token_hex(3)

    filename = f"{agent.name}_{ts_str}_{rand_hex}.json"
    filepath = LOG_DIR / filename

    with filepath.open("w", encoding="utf-8") as f_out:
        json.dump(entry, f_out, indent=2, default=serializer)

    return filepath

Overwriting logging_utils.py

In [113]:
from importlib import reload
import logging_utils

reload(logging_utils)
from logging_utils import log_interaction_to_file

print("logging utils reloaded")

logging utils reloaded

In [114]:
from pathlib import Path
list(Path("logs").glob("*.json"))

[PosixPath('logs/binance_agent_v1_20260328_013415_e5fa55.json'),
 PosixPath('logs/binance_agent_v2_20260328_013447_bc8e7f.json'),
 PosixPath('logs/binance_agent_v2_20260328_013342_d5c32d.json'),
 PosixPath('logs/binance_agent_v2_20260328_013441_4159f5.json'),
 PosixPath('logs/binance_agent_v2_20260328_013552_b47ac4.json'),
 PosixPath('logs/binance_agent_v1_20260328_013249_2e2397.json'),
 PosixPath('logs/binance_agent_v1_20260328_013444_d06064.json'),
 PosixPath('logs/binance_agent_v1_20260328_013310_06c4bb.json'),
 PosixPath('logs/binance_agent_v2_20260328_020037_def460.json'),
 PosixPath('logs/binance_agent_v2_20260328_015913_e6d64c.json'),
 PosixPath('logs/binance_agent_v2_20260328_015849_f4e2d8.json'),
 PosixPath('logs/binance_agent_v2_20260328_015957_21d203.json'),
 PosixPath('logs/binance_agent_v2_20260328_020033_667c72.json'),
 PosixPath('logs/binance_agent_v1_20260328_013525_c50e57.json'),
 PosixPath('logs/binance_agent_v1_20260328_013458_6e6639.json'),
 PosixPath('logs/binance_agent_v2_20260328_013309_443f93.json'),
 PosixPath('logs/binance_agent_v2_20260328_020011_347f4d.json'),
 PosixPath('logs/binance_agent_v2_20260328_015934_cec8e1.json'),
 PosixPath('logs/binance_agent_v2_20260328_015948_348301.json'),
 PosixPath('logs/binance_agent_v2_20260328_015853_dddd03.json'),
 PosixPath('logs/binance_agent_v2_20260328_013506_600f09.json'),
 PosixPath('logs/binance_agent_v2_20260328_015901_689049.json')]

In [52]:
%%writefile logging_utils.py
import json
import secrets
from pathlib import Path
from datetime import datetime
from pydantic_ai.messages import ModelMessagesTypeAdapter

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

def serializer(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")

def log_entry(agent, messages, source="user"):
    tools = []
    for ts in agent.toolsets:
        tools.extend(ts.tools.keys())

    dict_messages = ModelMessagesTypeAdapter.dump_python(messages)

    return {
        "agent_name": agent.name,
        "system_prompt": agent._instructions,
        "provider": agent.model.system,
        "model": agent.model.model_name,
        "tools": tools,
        "messages": dict_messages,
        "source": source,
    }

def log_interaction_to_file(agent, messages, source="user"):
    entry = log_entry(agent, messages, source)

    ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    rand_hex = secrets.token_hex(3)

    filename = f"{agent.name}_{ts_str}_{rand_hex}.json"
    filepath = LOG_DIR / filename

    with filepath.open("w", encoding="utf-8") as f_out:
        json.dump(entry, f_out, indent=2, default=serializer)

    return filepath

Overwriting logging_utils.py

In [53]:
from evals import load_log_file, evaluate_log_record
from pathlib import Path

LOG_DIR = Path("logs")
print("evals ready")

evals ready

In [58]:
log_files = list(LOG_DIR.glob("*.json"))
log_record = load_log_file(log_files[0])

eval_result = await evaluate_log_record(log_record)

print(eval_result.summary)
for check in eval_result.checklist:
    print(check.check_name, "=>", check.check_pass)

The response is well-structured, directly answers the question, follows instructions, and cites appropriate sources.
instructions_follow => True
answer_relevant => True
answer_clear => True
answer_citations => True
completeness => True
tool_call_search => True

In [62]:
import pandas as pd
from pathlib import Path

rows = []

for log_record, eval_result in eval_results:
    messages = log_record["messages"]

    row = {
        "file": Path(log_record["log_file"]).name,
        "agent_name": log_record.get("agent_name"),
        "agent_version": log_record.get("agent_version"),
        "source": log_record.get("source"),
        "question": messages[0]["parts"][0]["content"],
        "answer": messages[-1]["parts"][0]["content"],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)
    rows.append(row)

df_evals = pd.DataFrame(rows)
df_evals.to_csv("evaluation_results.csv", index=False)
print("saved evaluation_results.csv")

saved evaluation_results.csv

In [65]:
df = pd.DataFrame(rows)
df.to_csv("evaluation_results.csv", index=False)

In [66]:
df.mean(numeric_only=True)

instructions_follow    1.000000
answer_relevant        0.916667
answer_clear           1.000000
answer_citations       0.583333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

In [67]:
from importlib import reload
import logging_utils
import evals

reload(logging_utils)
reload(evals)

from logging_utils import log_interaction_to_file
from evals import load_log_file, evaluate_log_record

print("modules reloaded")

modules reloaded

In [68]:
df_v1 = df_evals[df_evals["agent_version"] == "v1"]
df_v2 = df_evals[df_evals["agent_version"] == "v2"]

print("V1 rows:", len(df_v1))
print("V2 rows:", len(df_v2))

print("\nV1 averages:")
print(df_v1.mean(numeric_only=True))

print("\nV2 averages:")
print(df_v2.mean(numeric_only=True))

V1 rows: 6
V2 rows: 6

V1 averages:
instructions_follow    1.000000
answer_relevant        0.833333
answer_clear           1.000000
answer_citations       0.333333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

V2 averages:
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.833333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

In [69]:
failure_cols = [
    "instructions_follow",
    "answer_relevant",
    "answer_clear",
    "answer_citations",
    "completeness",
    "tool_call_search"
]

failed_rows = df_evals[
    ~(df_evals[failure_cols].all(axis=1))
]

failed_rows[["file", "question"] + failure_cols]

,file,question,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
1,binance_agent_v2_20260328_013447_bc8e7f.json,How do I check exchange information?,True,True,True,False,False,True
5,binance_agent_v1_20260328_013249_2e2397.json,How do I authenticate API requests?,True,True,True,False,True,True
6,binance_agent_v1_20260328_013444_d06064.json,How do I check exchange information?,True,False,True,False,False,True
7,binance_agent_v1_20260328_013310_06c4bb.json,How do I place a market order?,True,True,True,False,True,True
8,binance_agent_v1_20260328_013525_c50e57.json,How do I get account balances?,True,True,True,False,True,True

In [70]:
df_evals[df_evals["answer_citations"] == False][["file", "question", "answer"]]

,file,question,answer
1,binance_agent_v2_20260328_013447_bc8e7f.json,How do I check exchange information?,"To check exchange information on Binance, you ..."
5,binance_agent_v1_20260328_013249_2e2397.json,How do I authenticate API requests?,"To authenticate API requests on Binance, you c..."
6,binance_agent_v1_20260328_013444_d06064.json,How do I check exchange information?,The search did not yield specific instructions...
7,binance_agent_v1_20260328_013310_06c4bb.json,How do I place a market order?,The search did not return any relevant informa...
8,binance_agent_v1_20260328_013525_c50e57.json,How do I get account balances?,"To get your account balances on Binance, you c..."

In [71]:
df_evals[df_evals["completeness"] == False][["file", "question", "answer"]]

,file,question,answer
1,binance_agent_v2_20260328_013447_bc8e7f.json,How do I check exchange information?,"To check exchange information on Binance, you ..."
6,binance_agent_v1_20260328_013444_d06064.json,How do I check exchange information?,The search did not yield specific instructions...

In [72]:
df_v1.to_csv("evaluation_results_v1.csv", index=False)
df_v2.to_csv("evaluation_results_v2.csv", index=False)

In [73]:
print("V1")
print(df_v1.mean(numeric_only=True))

print("V2")
print(df_v2.mean(numeric_only=True))

V1
instructions_follow    1.000000
answer_relevant        0.833333
answer_clear           1.000000
answer_citations       0.333333
completeness           0.833333
tool_call_search       1.000000
dtype: float64
V2
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.833333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

In [74]:
print("\nV1 length:", len(result_v1.output))
print("V2 length:", len(result_v2.output))

V1 length: 1124
V2 length: 1652

In [75]:
from pathlib import Path

Path("evaluation_results.csv").exists()

True

In [76]:
import pandas as pd

df = pd.read_csv("evaluation_results.csv")
df.head()

,file,agent_name,agent_version,source,question,answer,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
0,binance_agent_v1_20260328_013415_e5fa55.json,binance_agent_v1,v1,user,What parameters are needed to create an order?,"To create an order on Binance, you need the fo...",True,True,True,True,True,True
1,binance_agent_v2_20260328_013447_bc8e7f.json,binance_agent_v2,v2,user,How do I check exchange information?,"To check exchange information on Binance, you ...",True,True,True,False,False,True
2,binance_agent_v2_20260328_013342_d5c32d.json,binance_agent_v2,v2,user,How do I place a market order?,To place a market order on Binance via the API...,True,True,True,True,True,True
3,binance_agent_v2_20260328_013441_4159f5.json,binance_agent_v2,v2,user,What parameters are needed to create an order?,"To create an order on Binance, the following p...",True,True,True,True,True,True
4,binance_agent_v2_20260328_013552_b47ac4.json,binance_agent_v2,v2,user,How do I get account balances?,"To get your account balances on Binance, you c...",True,True,True,True,True,True

In [77]:
df.shape

(12, 12)

In [78]:
df_v1 = df[df["agent_version"] == "v1"]
df_v2 = df[df["agent_version"] == "v2"]

print("V1:")
print(df_v1.mean(numeric_only=True))

print("\nV2:")
print(df_v2.mean(numeric_only=True))

V1:
instructions_follow    1.000000
answer_relevant        0.833333
answer_clear           1.000000
answer_citations       0.333333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

V2:
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.833333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

In [79]:
df[df["completeness"] == False]

,file,agent_name,agent_version,source,question,answer,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
1,binance_agent_v2_20260328_013447_bc8e7f.json,binance_agent_v2,v2,user,How do I check exchange information?,"To check exchange information on Binance, you ...",True,True,True,False,False,True
6,binance_agent_v1_20260328_013444_d06064.json,binance_agent_v1,v1,user,How do I check exchange information?,The search did not yield specific instructions...,True,False,True,False,False,True

In [101]:
df_user = df[df["source"] == "user"]
df_ai = df[df["source"] == "ai-generated"]

print("User questions:")
print(df_user.mean(numeric_only=True))

print("\nAI-generated questions:")
print(df_ai.mean(numeric_only=True))

User questions:
instructions_follow       1.000000
answer_relevant           0.916667
answer_clear              1.000000
answer_citations          0.583333
completeness              0.833333
tool_call_search          1.000000
answer_length          1359.333333
dtype: float64

AI-generated questions:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
answer_length         NaN
dtype: float64

In [81]:
df.mean(numeric_only=True)
#spot fake scores

instructions_follow    1.000000
answer_relevant        0.916667
answer_clear           1.000000
answer_citations       0.583333
completeness           0.833333
tool_call_search       1.000000
dtype: float64

In [82]:
import json

with open(list(Path("logs").glob("*.json"))[0]) as f:
    log = json.load(f)

log

{'agent_name': 'binance_agent_v1',
 'agent_version': 'v1',
 'system_prompt': ['\nYou are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.\n'],
 'provider': 'openai',
 'model': 'gpt-4o-mini',
 'tools': ['search_docs'],
 'messages': [{'parts': [{'content': 'What parameters are needed to create an order?',
     'timestamp': '2026-03-28T01:33:42.380963+00:00',
     'part_kind': 'user-prompt'}],
   'timestamp': '2026-03-28T01:33:42.381137+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.',
   'kind': 'request',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"create order parameters"}',
     'tool_call_id': 'call_PIhgEGAtsVqWFv9vuWrzedv1',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 95,
    'cache_write_tokens': 0,
    'cache_read_tokens': 0,
    'output_tokens': 16,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-28T01:33:43.064867+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-28T01:33:42+00:00'},
   'provider_response_id': 'chatcmpl-DOCqU9BePqE1WuiyDNFsCvgXj6eKY',
   'finish_reason': 'tool_call',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'content': "Result 1:\n{'id': '250', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/testnet/rest-api.md', 'section': '## General Information on Endpoints\\n\\n* For `GET` endpoints, parameters must be sent as a `query string`.\\n* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a\\n  `query string` or in the `request body` with content type\\n  `application/x-www-form-urlencoded`. You may mix parameters between both the\\n  `query string` and `request body` if you wish to do so.\\n* Parameters may be sent in any order.\\n* If a parameter sent in both the `query string` and `request body`, the\\n  `query string` parameter will be used.'}\n\nResult 2:\n{'id': '189', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/rest-api.md', 'section': '## General Information on Endpoints\\n\\n* For `GET` endpoints, parameters must be sent as a `query string`.\\n* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a\\n  `query string` or in the `request body` with content type\\n  `application/x-www-form-urlencoded`. You may mix parameters between both the\\n  `query string` and `request body` if you wish to do so.\\n* Parameters may be sent in any order.\\n* If a parameter sent in both the `query string` and `request body`, the\\n  `query string` parameter will be used.'}\n\nResult 3:\n{'id': '92', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/faqs/order_count_decrement.md', 'section': '## How do canceled or expired orders affect the unfilled order count?\\n\\nCanceling an order does not change the unfilled order count.\\n\\nExpired orders also do not change the unfilled order count.\\n\\n**Example:**\\n\\n| Time     | Action                         | Unfilled order count |\\n|:---------|:-------------------------------|:---------------------|\\n| 00:00:00 |                                | 0                    |\\n| 00:00:01 | Place LIMIT order A            | 1 — new order (+1)   |\\n| 00:00:02 | Cancel order A                 | 1                    |\\n| 00:00:02 | Place LIMIT order B            | 2 — new order (+1)   |\\n| 00:00:03 | Place LIMIT FOK order C        | 3 — new order (+1)   |\\n|          | (order C is fully filled)      | 2 — fill (−1)        |\\n| 00:00:05 | Place LIMIT order D            | 3 — new order (+1)   |\\n| 00:00:06 | Place LIMIT FOK order E        | 4 — new order (+1)   |\\n|          | (order E expires with no fill) | 4                    |\\n| 00:00:07 | Cancel order D                 | 4                    |\\n| 00:00:07 | Place LIMIT order F            | 5 — new order (+1)   |'}\n\nResult 4:\n{'id': '91', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/faqs/order_count_decrement.md', 'section': '## How do filled orders affect the unfilled order count?\\n\\nWhen an order is filled for the first time (partially or fully), your unfilled order count is decremented by one order for all intervals of the `ORDERS` rate limit. Effectively, orders that trade do not count towards the rate limit, allowing efficient traders to keep placing new orders. \\n\\nCertain orders provide additional incentive:\\n\\n* **Orders that do not fill immediately (that is, first fill in the maker phase).**   \\n* Orders that fill large quantities.\\n\\nIn these cases the unfilled order count may be decremented by more than one order for each order that starts trading.\\n\\n**Notes:**\\n\\n* **The examples only give a general idea of the behavior.** The 10-second interval is used for simplicity. The actual configuration on the live exchange may be different.  \\n* There is a short delay between the order being filled and the unfilled order count update. Please be careful when your unfilled order count is close to the limit.  \\n* Please refer to [How does unfilled `ORDERS` rate limit work?](#order-rate-limit) to see how you can monitor the unfilled order count depending on the API.\\n\\n**Example 1** — taker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order B        | 2 — new order (+1)           |\\n|          | (order B partially filled) | 1 — first fill as taker (−1) |\\n| 00:00:03 | Place LIMIT order C        | 2 — new order (+1)           |\\n| 00:00:04 | (order B partially filled) | 2                            |\\n| 00:00:04 | (order B filled)           | 2                            |\\n| 00:00:05 | Place MARKET order D       | 3 — new order (+1)           |\\n|          | (order D fully filled)     | 2 — first fill as taker (−1) |\\n\\nNote how for every taker order that immediately trades, the unfilled order count is decremented later, allowing you to keep placing orders.\\n\\n**Example 2** — maker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:01 | Place LIMIT order B        | 2 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order C        | 3 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order D        | 4 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order E        | 5 — new order (+1)           |\\n| 00:00:03 | (order A partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:04 | Place LIMIT order F        | 1 — new order (+1)           |\\n| 00:00:04 | Place LIMIT order G        | 2 — new order (+1)           |\\n| 00:00:05 | (order A partially filled) | 2                            |\\n| 00:00:05 | (order A filled)           | 2                            |\\n| 00:00:05 | (order B partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:06 | Place LIMIT order H        | 1 — new order (+1)           |\\n\\nNote how for every maker order that is filled later, the unfilled order count is decremented by a higher amount, allowing you to place more orders.'}\n\nResult 5:\n{'id': '21', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/enums.md', 'section': '## Time in force (timeInForce)\\n\\nThis sets how long an order will be active before expiration.\\n\\nStatus | Description\\n-----------| --------------\\n`GTC` | Good Til Canceled <br/> An order will be on the book unless the order is canceled.\\n`IOC` | Immediate Or Cancel <br/> An order will try to fill the order as much as it can before the order expires.\\n`FOK`| Fill or Kill <br/> An order will expire if the full order cannot be filled upon execution.'}\n",
     'tool_call_id': 'call_PIhgEGAtsVqWFv9vuWrzedv1',
     'metadata': None,
     'timestamp': '2026-03-28T01:33:43.098539+00:00',
     'outcome': 'success',
     'part_kind': 'tool-return'}],
   'timestamp': '2026-03-28T01:33:43.098991+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.',
   'kind': 'request',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"create order"}',
     'tool_call_id': 'call_oHjDZbhngGwiAmJLzn9ip8Dj',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 1975,
    'cache_write_tokens': 0,
    'cache_read_tokens': 0,
    'output_tokens': 15,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-28T01:33:43.768226+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-28T01:33:43+00:00'},
   'provider_response_id': 'chatcmpl-DOCqVHLRSW1MSnu8Y27uNPmuP298g',
   'finish_reason': 'tool_call',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'content': 'Result 1:\n{\'id\': \'92\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/faqs/order_count_decrement.md\', \'section\': \'## How do canceled or expired orders affect the unfilled order count?\\n\\nCanceling an order does not change the unfilled order count.\\n\\nExpired orders also do not change the unfilled order count.\\n\\n**Example:**\\n\\n| Time     | Action                         | Unfilled order count |\\n|:---------|:-------------------------------|:---------------------|\\n| 00:00:00 |                                | 0                    |\\n| 00:00:01 | Place LIMIT order A            | 1 — new order (+1)   |\\n| 00:00:02 | Cancel order A                 | 1                    |\\n| 00:00:02 | Place LIMIT order B            | 2 — new order (+1)   |\\n| 00:00:03 | Place LIMIT FOK order C        | 3 — new order (+1)   |\\n|          | (order C is fully filled)      | 2 — fill (−1)        |\\n| 00:00:05 | Place LIMIT order D            | 3 — new order (+1)   |\\n| 00:00:06 | Place LIMIT FOK order E        | 4 — new order (+1)   |\\n|          | (order E expires with no fill) | 4                    |\\n| 00:00:07 | Cancel order D                 | 4                    |\\n| 00:00:07 | Place LIMIT order F            | 5 — new order (+1)   |\'}\n\nResult 2:\n{\'id\': \'91\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/faqs/order_count_decrement.md\', \'section\': \'## How do filled orders affect the unfilled order count?\\n\\nWhen an order is filled for the first time (partially or fully), your unfilled order count is decremented by one order for all intervals of the `ORDERS` rate limit. Effectively, orders that trade do not count towards the rate limit, allowing efficient traders to keep placing new orders. \\n\\nCertain orders provide additional incentive:\\n\\n* **Orders that do not fill immediately (that is, first fill in the maker phase).**   \\n* Orders that fill large quantities.\\n\\nIn these cases the unfilled order count may be decremented by more than one order for each order that starts trading.\\n\\n**Notes:**\\n\\n* **The examples only give a general idea of the behavior.** The 10-second interval is used for simplicity. The actual configuration on the live exchange may be different.  \\n* There is a short delay between the order being filled and the unfilled order count update. Please be careful when your unfilled order count is close to the limit.  \\n* Please refer to [How does unfilled `ORDERS` rate limit work?](#order-rate-limit) to see how you can monitor the unfilled order count depending on the API.\\n\\n**Example 1** — taker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order B        | 2 — new order (+1)           |\\n|          | (order B partially filled) | 1 — first fill as taker (−1) |\\n| 00:00:03 | Place LIMIT order C        | 2 — new order (+1)           |\\n| 00:00:04 | (order B partially filled) | 2                            |\\n| 00:00:04 | (order B filled)           | 2                            |\\n| 00:00:05 | Place MARKET order D       | 3 — new order (+1)           |\\n|          | (order D fully filled)     | 2 — first fill as taker (−1) |\\n\\nNote how for every taker order that immediately trades, the unfilled order count is decremented later, allowing you to keep placing orders.\\n\\n**Example 2** — maker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:01 | Place LIMIT order B        | 2 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order C        | 3 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order D        | 4 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order E        | 5 — new order (+1)           |\\n| 00:00:03 | (order A partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:04 | Place LIMIT order F        | 1 — new order (+1)           |\\n| 00:00:04 | Place LIMIT order G        | 2 — new order (+1)           |\\n| 00:00:05 | (order A partially filled) | 2                            |\\n| 00:00:05 | (order A filled)           | 2                            |\\n| 00:00:05 | (order B partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:06 | Place LIMIT order H        | 1 — new order (+1)           |\\n\\nNote how for every maker order that is filled later, the unfilled order count is decremented by a higher amount, allowing you to place more orders.\'}\n\nResult 3:\n{\'id\': \'21\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/enums.md\', \'section\': \'## Time in force (timeInForce)\\n\\nThis sets how long an order will be active before expiration.\\n\\nStatus | Description\\n-----------| --------------\\n`GTC` | Good Til Canceled <br/> An order will be on the book unless the order is canceled.\\n`IOC` | Immediate Or Cancel <br/> An order will try to fill the order as much as it can before the order expires.\\n`FOK`| Fill or Kill <br/> An order will expire if the full order cannot be filled upon execution.\'}\n\nResult 4:\n{\'id\': \'225\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/testnet/enums.md\', \'section\': \'## Time in force (timeInForce)\\n\\nThis sets how long an order will be active before expiration.\\n\\nStatus | Description\\n-----------| --------------\\n`GTC` | Good Til Canceled <br/> An order will be on the book unless the order is canceled.\\n`IOC` | Immediate Or Cancel <br/> An order will try to fill the order as much as it can before the order expires.\\n`FOK`| Fill or Kill <br/> An order will expire if the full order cannot be filled upon execution.\'}\n\nResult 5:\n{\'id\': \'72\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/faqs/order_amend_keep_priority.md\', \'section\': \'## How do I know if my order has been amended?\\n\\nIf the order was amended successfully, the API response contains your order with the updated quantity.\\n\\nOn User Data Stream, you will receive an `"executionReport"` event with execution type `"x": "REPLACED"`.\\n\\nIf the amended order belongs to an order list and the client order ID has changed, you will also receive a "listStatus" event with list status type `"l": "UPDATED"`.\\n\\nYou can also use the following requests to query order modification history:\\n\\n| API | Request |\\n| :---- | :---- |\\n| REST API | `GET /api/v3/order/amendments` |\\n| WebSocket API | `order.amendments` |\'}\n',
     'tool_call_id': 'call_oHjDZbhngGwiAmJLzn9ip8Dj',
     'metadata': None,
     'timestamp': '2026-03-28T01:33:43.801651+00:00',
     'outcome': 'success',
     'part_kind': 'tool-return'}],
   'timestamp': '2026-03-28T01:33:43.802094+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.',
   'kind': 'request',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"create order API parameters"}',
     'tool_call_id': 'call_BBRTDlLxrbG1WP1dhSpgtmA1',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 3858,
    'cache_write_tokens': 0,
    'cache_read_tokens': 1920,
    'output_tokens': 17,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-28T01:33:44.464889+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-28T01:33:43+00:00'},
   'provider_response_id': 'chatcmpl-DOCqVDFPqvdLllZ9hxTlPYSIFvTWy',
   'finish_reason': 'tool_call',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',

In [83]:
import json

with open(list(Path("logs").glob("*.json"))[0]) as f:
    log = json.load(f)

log

{'agent_name': 'binance_agent_v1',
 'agent_version': 'v1',
 'system_prompt': ['\nYou are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.\n'],
 'provider': 'openai',
 'model': 'gpt-4o-mini',
 'tools': ['search_docs'],
 'messages': [{'parts': [{'content': 'What parameters are needed to create an order?',
     'timestamp': '2026-03-28T01:33:42.380963+00:00',
     'part_kind': 'user-prompt'}],
   'timestamp': '2026-03-28T01:33:42.381137+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.',
   'kind': 'request',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"create order parameters"}',
     'tool_call_id': 'call_PIhgEGAtsVqWFv9vuWrzedv1',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 95,
    'cache_write_tokens': 0,
    'cache_read_tokens': 0,
    'output_tokens': 16,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-28T01:33:43.064867+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-28T01:33:42+00:00'},
   'provider_response_id': 'chatcmpl-DOCqU9BePqE1WuiyDNFsCvgXj6eKY',
   'finish_reason': 'tool_call',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'content': "Result 1:\n{'id': '250', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/testnet/rest-api.md', 'section': '## General Information on Endpoints\\n\\n* For `GET` endpoints, parameters must be sent as a `query string`.\\n* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a\\n  `query string` or in the `request body` with content type\\n  `application/x-www-form-urlencoded`. You may mix parameters between both the\\n  `query string` and `request body` if you wish to do so.\\n* Parameters may be sent in any order.\\n* If a parameter sent in both the `query string` and `request body`, the\\n  `query string` parameter will be used.'}\n\nResult 2:\n{'id': '189', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/rest-api.md', 'section': '## General Information on Endpoints\\n\\n* For `GET` endpoints, parameters must be sent as a `query string`.\\n* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a\\n  `query string` or in the `request body` with content type\\n  `application/x-www-form-urlencoded`. You may mix parameters between both the\\n  `query string` and `request body` if you wish to do so.\\n* Parameters may be sent in any order.\\n* If a parameter sent in both the `query string` and `request body`, the\\n  `query string` parameter will be used.'}\n\nResult 3:\n{'id': '92', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/faqs/order_count_decrement.md', 'section': '## How do canceled or expired orders affect the unfilled order count?\\n\\nCanceling an order does not change the unfilled order count.\\n\\nExpired orders also do not change the unfilled order count.\\n\\n**Example:**\\n\\n| Time     | Action                         | Unfilled order count |\\n|:---------|:-------------------------------|:---------------------|\\n| 00:00:00 |                                | 0                    |\\n| 00:00:01 | Place LIMIT order A            | 1 — new order (+1)   |\\n| 00:00:02 | Cancel order A                 | 1                    |\\n| 00:00:02 | Place LIMIT order B            | 2 — new order (+1)   |\\n| 00:00:03 | Place LIMIT FOK order C        | 3 — new order (+1)   |\\n|          | (order C is fully filled)      | 2 — fill (−1)        |\\n| 00:00:05 | Place LIMIT order D            | 3 — new order (+1)   |\\n| 00:00:06 | Place LIMIT FOK order E        | 4 — new order (+1)   |\\n|          | (order E expires with no fill) | 4                    |\\n| 00:00:07 | Cancel order D                 | 4                    |\\n| 00:00:07 | Place LIMIT order F            | 5 — new order (+1)   |'}\n\nResult 4:\n{'id': '91', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/faqs/order_count_decrement.md', 'section': '## How do filled orders affect the unfilled order count?\\n\\nWhen an order is filled for the first time (partially or fully), your unfilled order count is decremented by one order for all intervals of the `ORDERS` rate limit. Effectively, orders that trade do not count towards the rate limit, allowing efficient traders to keep placing new orders. \\n\\nCertain orders provide additional incentive:\\n\\n* **Orders that do not fill immediately (that is, first fill in the maker phase).**   \\n* Orders that fill large quantities.\\n\\nIn these cases the unfilled order count may be decremented by more than one order for each order that starts trading.\\n\\n**Notes:**\\n\\n* **The examples only give a general idea of the behavior.** The 10-second interval is used for simplicity. The actual configuration on the live exchange may be different.  \\n* There is a short delay between the order being filled and the unfilled order count update. Please be careful when your unfilled order count is close to the limit.  \\n* Please refer to [How does unfilled `ORDERS` rate limit work?](#order-rate-limit) to see how you can monitor the unfilled order count depending on the API.\\n\\n**Example 1** — taker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order B        | 2 — new order (+1)           |\\n|          | (order B partially filled) | 1 — first fill as taker (−1) |\\n| 00:00:03 | Place LIMIT order C        | 2 — new order (+1)           |\\n| 00:00:04 | (order B partially filled) | 2                            |\\n| 00:00:04 | (order B filled)           | 2                            |\\n| 00:00:05 | Place MARKET order D       | 3 — new order (+1)           |\\n|          | (order D fully filled)     | 2 — first fill as taker (−1) |\\n\\nNote how for every taker order that immediately trades, the unfilled order count is decremented later, allowing you to keep placing orders.\\n\\n**Example 2** — maker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:01 | Place LIMIT order B        | 2 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order C        | 3 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order D        | 4 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order E        | 5 — new order (+1)           |\\n| 00:00:03 | (order A partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:04 | Place LIMIT order F        | 1 — new order (+1)           |\\n| 00:00:04 | Place LIMIT order G        | 2 — new order (+1)           |\\n| 00:00:05 | (order A partially filled) | 2                            |\\n| 00:00:05 | (order A filled)           | 2                            |\\n| 00:00:05 | (order B partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:06 | Place LIMIT order H        | 1 — new order (+1)           |\\n\\nNote how for every maker order that is filled later, the unfilled order count is decremented by a higher amount, allowing you to place more orders.'}\n\nResult 5:\n{'id': '21', 'chunk': '', 'title': '', 'description': '', 'filename': 'binance-spot-api-docs-master/enums.md', 'section': '## Time in force (timeInForce)\\n\\nThis sets how long an order will be active before expiration.\\n\\nStatus | Description\\n-----------| --------------\\n`GTC` | Good Til Canceled <br/> An order will be on the book unless the order is canceled.\\n`IOC` | Immediate Or Cancel <br/> An order will try to fill the order as much as it can before the order expires.\\n`FOK`| Fill or Kill <br/> An order will expire if the full order cannot be filled upon execution.'}\n",
     'tool_call_id': 'call_PIhgEGAtsVqWFv9vuWrzedv1',
     'metadata': None,
     'timestamp': '2026-03-28T01:33:43.098539+00:00',
     'outcome': 'success',
     'part_kind': 'tool-return'}],
   'timestamp': '2026-03-28T01:33:43.098991+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.',
   'kind': 'request',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"create order"}',
     'tool_call_id': 'call_oHjDZbhngGwiAmJLzn9ip8Dj',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 1975,
    'cache_write_tokens': 0,
    'cache_read_tokens': 0,
    'output_tokens': 15,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-28T01:33:43.768226+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-28T01:33:43+00:00'},
   'provider_response_id': 'chatcmpl-DOCqVHLRSW1MSnu8Y27uNPmuP298g',
   'finish_reason': 'tool_call',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'content': 'Result 1:\n{\'id\': \'92\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/faqs/order_count_decrement.md\', \'section\': \'## How do canceled or expired orders affect the unfilled order count?\\n\\nCanceling an order does not change the unfilled order count.\\n\\nExpired orders also do not change the unfilled order count.\\n\\n**Example:**\\n\\n| Time     | Action                         | Unfilled order count |\\n|:---------|:-------------------------------|:---------------------|\\n| 00:00:00 |                                | 0                    |\\n| 00:00:01 | Place LIMIT order A            | 1 — new order (+1)   |\\n| 00:00:02 | Cancel order A                 | 1                    |\\n| 00:00:02 | Place LIMIT order B            | 2 — new order (+1)   |\\n| 00:00:03 | Place LIMIT FOK order C        | 3 — new order (+1)   |\\n|          | (order C is fully filled)      | 2 — fill (−1)        |\\n| 00:00:05 | Place LIMIT order D            | 3 — new order (+1)   |\\n| 00:00:06 | Place LIMIT FOK order E        | 4 — new order (+1)   |\\n|          | (order E expires with no fill) | 4                    |\\n| 00:00:07 | Cancel order D                 | 4                    |\\n| 00:00:07 | Place LIMIT order F            | 5 — new order (+1)   |\'}\n\nResult 2:\n{\'id\': \'91\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/faqs/order_count_decrement.md\', \'section\': \'## How do filled orders affect the unfilled order count?\\n\\nWhen an order is filled for the first time (partially or fully), your unfilled order count is decremented by one order for all intervals of the `ORDERS` rate limit. Effectively, orders that trade do not count towards the rate limit, allowing efficient traders to keep placing new orders. \\n\\nCertain orders provide additional incentive:\\n\\n* **Orders that do not fill immediately (that is, first fill in the maker phase).**   \\n* Orders that fill large quantities.\\n\\nIn these cases the unfilled order count may be decremented by more than one order for each order that starts trading.\\n\\n**Notes:**\\n\\n* **The examples only give a general idea of the behavior.** The 10-second interval is used for simplicity. The actual configuration on the live exchange may be different.  \\n* There is a short delay between the order being filled and the unfilled order count update. Please be careful when your unfilled order count is close to the limit.  \\n* Please refer to [How does unfilled `ORDERS` rate limit work?](#order-rate-limit) to see how you can monitor the unfilled order count depending on the API.\\n\\n**Example 1** — taker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order B        | 2 — new order (+1)           |\\n|          | (order B partially filled) | 1 — first fill as taker (−1) |\\n| 00:00:03 | Place LIMIT order C        | 2 — new order (+1)           |\\n| 00:00:04 | (order B partially filled) | 2                            |\\n| 00:00:04 | (order B filled)           | 2                            |\\n| 00:00:05 | Place MARKET order D       | 3 — new order (+1)           |\\n|          | (order D fully filled)     | 2 — first fill as taker (−1) |\\n\\nNote how for every taker order that immediately trades, the unfilled order count is decremented later, allowing you to keep placing orders.\\n\\n**Example 2** — maker:\\n\\n| Time     | Action                     | Unfilled order count         |\\n|:---------|:---------------------------|:-----------------------------|\\n| 00:00:00 |                            | 0                            |\\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\\n| 00:00:01 | Place LIMIT order B        | 2 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order C        | 3 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order D        | 4 — new order (+1)           |\\n| 00:00:02 | Place LIMIT order E        | 5 — new order (+1)           |\\n| 00:00:03 | (order A partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:04 | Place LIMIT order F        | 1 — new order (+1)           |\\n| 00:00:04 | Place LIMIT order G        | 2 — new order (+1)           |\\n| 00:00:05 | (order A partially filled) | 2                            |\\n| 00:00:05 | (order A filled)           | 2                            |\\n| 00:00:05 | (order B partially filled) | 0 — first fill as maker (−5) |\\n| 00:00:06 | Place LIMIT order H        | 1 — new order (+1)           |\\n\\nNote how for every maker order that is filled later, the unfilled order count is decremented by a higher amount, allowing you to place more orders.\'}\n\nResult 3:\n{\'id\': \'21\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/enums.md\', \'section\': \'## Time in force (timeInForce)\\n\\nThis sets how long an order will be active before expiration.\\n\\nStatus | Description\\n-----------| --------------\\n`GTC` | Good Til Canceled <br/> An order will be on the book unless the order is canceled.\\n`IOC` | Immediate Or Cancel <br/> An order will try to fill the order as much as it can before the order expires.\\n`FOK`| Fill or Kill <br/> An order will expire if the full order cannot be filled upon execution.\'}\n\nResult 4:\n{\'id\': \'225\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/testnet/enums.md\', \'section\': \'## Time in force (timeInForce)\\n\\nThis sets how long an order will be active before expiration.\\n\\nStatus | Description\\n-----------| --------------\\n`GTC` | Good Til Canceled <br/> An order will be on the book unless the order is canceled.\\n`IOC` | Immediate Or Cancel <br/> An order will try to fill the order as much as it can before the order expires.\\n`FOK`| Fill or Kill <br/> An order will expire if the full order cannot be filled upon execution.\'}\n\nResult 5:\n{\'id\': \'72\', \'chunk\': \'\', \'title\': \'\', \'description\': \'\', \'filename\': \'binance-spot-api-docs-master/faqs/order_amend_keep_priority.md\', \'section\': \'## How do I know if my order has been amended?\\n\\nIf the order was amended successfully, the API response contains your order with the updated quantity.\\n\\nOn User Data Stream, you will receive an `"executionReport"` event with execution type `"x": "REPLACED"`.\\n\\nIf the amended order belongs to an order list and the client order ID has changed, you will also receive a "listStatus" event with list status type `"l": "UPDATED"`.\\n\\nYou can also use the following requests to query order modification history:\\n\\n| API | Request |\\n| :---- | :---- |\\n| REST API | `GET /api/v3/order/amendments` |\\n| WebSocket API | `order.amendments` |\'}\n',
     'tool_call_id': 'call_oHjDZbhngGwiAmJLzn9ip8Dj',
     'metadata': None,
     'timestamp': '2026-03-28T01:33:43.801651+00:00',
     'outcome': 'success',
     'part_kind': 'tool-return'}],
   'timestamp': '2026-03-28T01:33:43.802094+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nAlways use the search_docs tool before answering questions.\nBase your answer only on the retrieved documentation.\nIf the answer is not found, say that clearly.\nDo not guess.',
   'kind': 'request',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"create order API parameters"}',
     'tool_call_id': 'call_BBRTDlLxrbG1WP1dhSpgtmA1',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 3858,
    'cache_write_tokens': 0,
    'cache_read_tokens': 1920,
    'output_tokens': 17,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-28T01:33:44.464889+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-28T01:33:43+00:00'},
   'provider_response_id': 'chatcmpl-DOCqVDFPqvdLllZ9hxTlPYSIFvTWy',
   'finish_reason': 'tool_call',
   'run_id': '7f82b921-1fac-433e-b48d-53436e6d3d43',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',

In [84]:
df["answer_length"] = df["answer"].apply(len)

df_v1 = df[df["agent_version"] == "v1"]
df_v2 = df[df["agent_version"] == "v2"]

print(df_v1["answer_length"].mean())
print(df_v2["answer_length"].mean())

1139.6666666666667
1579.0

In [85]:
df["source"].value_counts(dropna=False)

source
user    12
Name: count, dtype: int64

In [86]:
len(df[df["source"] == "ai-generated"])

0

In [87]:
import json
import random
from pydantic import BaseModel
from pydantic_ai import Agent

In [88]:
class QuestionsList(BaseModel):
    questions: list[str]

In [89]:
question_generation_prompt = """
You are helping create test questions for an AI agent that answers questions about Binance API documentation.

Based on the provided documentation snippets, generate realistic questions that a user might ask.

The questions should:
- be natural and varied
- range from simple to complex
- include authentication, orders, rate limits, account info, market data, and signing
- generate one question per input record
""".strip()

In [90]:
question_generator = Agent(
    name="binance_question_generator",
    instructions=question_generation_prompt,
    model="gpt-4o-mini",
    output_type=QuestionsList,
)

In [91]:
import json
import random

with open("my_chunks_sections.json", "r", encoding="utf-8") as f:
    chunks = json.load(f)

sample = random.sample(chunks, 10)

In [92]:
sample[0]

{'filename': 'binance-spot-api-docs-master/testnet/web-socket-api.md',
 'section': '## User Data Stream requests\n\n### User Data Stream subscription\n\n<a id=general_info_user_data_stream_subscriptions></a>\n**General information:**\n\n* [User Data Stream](user-data-stream.md) subscriptions allow you to receive all the events related to a given account on a WebSocket connection.\n* There are 2 ways to start a subscription:\n  * If you have an authenticated session, then you can subscribe to events for that authenticated account using [`userDataStream.subscribe`](#user-data-stream-subscribe).\n  * In any session, authenticated or not, you can subscribe to events for one or more accounts for which you can provide an API Key signature, using [`userDataStream.subscribe.signature`](#user-data-signature).\n  * You can have only one active subscription for a given account on a given connection.\n* Subscriptions are identified by a `subscriptionId` which is returned when starting the subscription. That `subscriptionId` allows you to map the events you receive to a given subscription.\n  * All active subscriptions for a session can be found using [`session.subscriptions`](#session-subscription).\n* Limits\n  * A single session supports **up to 1,000 active subscriptions** simultaneously.\n    * Attempting to start a new subscription beyond this limit will result in an error.\n    * If your accounts are very active, we suggest not opening too many subscriptions at once, in order to not overload your connection.\n  * A single session can handle a maximum of **65,535 total subscriptions** over its lifetime.\n    * If this limit is reached, you will receive an error and must re-establish a new connection to be able to start new subscriptions.\n* To verify the status of User Data Stream subscriptions, check the `userDataStream` field in [`session.status`](#session-status):\n  * `null` - User Data Stream subscriptions are **not available** on this WebSocket API.\n  * `true` - There is at **least one subscription active** in this session.\n  * `false` - There are **no active subscriptions** in this session.\n\n<a id="user-data-stream-subscribe"></a>\n\n#### Subscribe to User Data Stream (USER_STREAM)\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "method": "userDataStream.subscribe"\n}\n```\n\nSubscribe to the User Data Stream in the current WebSocket connection.\n\n**Notes:**\n\n* This method requires an authenticated WebSocket connection using Ed25519 keys. Please refer to [`session.logon`](#session-logon).\n* To check the subscription status, use [`session.status`](#session-status), see the `userDataStream` flag indicating you have have an active subscription.\n* User Data Stream events are available in both JSON and [SBE](../faqs/sbe_faq.md) sessions.\n  * Please refer to [User Data Streams](user-data-stream.md) for the event format details.\n  * For SBE, only SBE schema 2:1 or later is supported.\n\n**Weight**:\n2\n\n**Parameters**:\nNONE\n\n**Response**:\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "status": 200,\n    "result": {\n        "subscriptionId": 0\n    }\n}\n```\n\n#### Unsubscribe from User Data Stream\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "method": "userDataStream.unsubscribe"\n}\n```\n\nStop listening to the User Data Stream in the current WebSocket connection.\n\nNote that `session.logout` will only close the subscription created with `userDataStream.subscribe` but not subscriptions opened with `userDataStream.subscribe.signature`.\n\n**Weight**:\n2\n\n**Parameters**:\n\n| Name | Type | Mandatory | Description |\n| --- | --- | --- | --- |\n| `subscriptionId` | INT | No | When called with no parameter, this will close all subscriptions. <br>When called with the `subscriptionId` parameter, this will attempt to close the subscription with that subscription id, if it exists. |\n\n**Response**:\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "status": 200,\n    "result": {}\n}\n```\n\n<a id="session-subscription"></a>\n\n#### Listing all subscriptions\n\n```javascript\n{\n    "id": "d3df5a22-88ea-4fe0-9f4e-0fcea5d418b7",\n    "method": "session.subscriptions",\n    "params": {}\n}\n```\n\n**Note:**\n\n* Users are expected to track on their side which subscription corresponds to which account.\n\n**Weight**: 2\n\n**Data Source**: Memory\n\n**Response**:\n\n```javascript\n{\n    "id": "d3df5a22-88ea-4fe0-9f4e-0fcea5d418b7",\n    "status": 200,\n    "result": [\n        {\n            "subscriptionId": 0\n        },\n        {\n            "subscriptionId": 1\n        }\n    ]\n}\n```\n\n<a id="user-data-signature"></a>\n\n#### Subscribe to User Data Stream through signature subscription (USER_STREAM)\n\n```javascript\n{\n    "id": "d3df8a22-98ea-4fe0-9f4e-0fcea5d418b7",\n    "method": "userDataStream.subscribe.signature",\n    "params": {\n        "apiKey": "mjcKCrJzTU6TChLsnPmgnQJJMR616J4yWvdZWDUeXkk6vL6dLyS7rcVOQlADlVjA",\n        "timestamp": 1747385641636,\n        "signature": "yN1vWpXb+qoZ3/dGiFs9vmpNdV7e3FxkA+BstzbezDKwObcijvk/CVkWxIwMCtCJbP270R0OempYwEpS6rDZCQ=="\n    }\n}\n```\n\n**Weight:**\n2\n\n**Parameters**:\n\n| Name | Type | Mandatory | Description |\n| --- | --- | --- | --- |\n| `apiKey` | STRING | Yes |  |\n| `timestamp` | LONG | Yes |  |\n| `signature` | STRING | Yes |  |\n|`recvWindow`|DECIMAL | No|The value cannot be greater than `60000`. <br> Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.|\n\n\n**Data Source:** Memory\n\n**Response:**\n\n```javascript\n{\n    "id": "d3df8a22-98ea-4fe0-9f4e-0fcea5d418b7",\n    "status": 200,\n    "result": {\n        "subscriptionId": 0\n    }\n}\n```'}

In [93]:
def clean_section(text):
    return text.replace("\n", " ").strip()

prompt_docs = [clean_section(d["section"]) for d in sample]

In [94]:
prompt = json.dumps(prompt_docs, ensure_ascii=False)
result = await question_generator.run(prompt)
ai_questions = result.output.questions
ai_questions

['How can I authenticate my session when using the Binance WebSocket API?',
 'What is the maximum number of active User Data Stream subscriptions I can have on a single session?',
 'What should I do if I receive an error while trying to subscribe to the User Data Stream?',
 'How do I subscribe to the User Data Stream using the signature method?',
 'What parameters do I need to consider for signing requests to the Binance API?',
 'What happens if I exceed the rate limit for order submissions on Binance?',
 'How can I check how many active subscriptions I have in my session with the Binance WebSocket API?',
 'What is the response format for the User Data Stream events?',
 'How do the rate limits work for the Binance API?',
 'Can I receive market data without an authenticated session on Binance?']

In [95]:
for q in ai_questions:
    print(q)

How can I authenticate my session when using the Binance WebSocket API?
What is the maximum number of active User Data Stream subscriptions I can have on a single session?
What should I do if I receive an error while trying to subscribe to the User Data Stream?
How do I subscribe to the User Data Stream using the signature method?
What parameters do I need to consider for signing requests to the Binance API?
What happens if I exceed the rate limit for order submissions on Binance?
How can I check how many active subscriptions I have in my session with the Binance WebSocket API?
What is the response format for the User Data Stream events?
How do the rate limits work for the Binance API?
Can I receive market data without an authenticated session on Binance?

In [104]:
for q in ai_questions:
    print("\nAI QUESTION:", q)

    result = await agent_v2.run(q)

    log_file = log_interaction_to_file(
        agent_v2,
        result.new_messages(),
        source="ai-generated",
        version="v2"
    )

    print("Saved:", log_file)

AI QUESTION: How can I authenticate my session when using the Binance WebSocket API?
Saved: logs/binance_agent_v2_20260328_015849_f4e2d8.json

AI QUESTION: What is the maximum number of active User Data Stream subscriptions I can have on a single session?
Saved: logs/binance_agent_v2_20260328_015853_dddd03.json

AI QUESTION: What should I do if I receive an error while trying to subscribe to the User Data Stream?
Saved: logs/binance_agent_v2_20260328_015901_689049.json

AI QUESTION: How do I subscribe to the User Data Stream using the signature method?
Saved: logs/binance_agent_v2_20260328_015913_e6d64c.json

AI QUESTION: What parameters do I need to consider for signing requests to the Binance API?
Saved: logs/binance_agent_v2_20260328_015934_cec8e1.json

AI QUESTION: What happens if I exceed the rate limit for order submissions on Binance?
Saved: logs/binance_agent_v2_20260328_015948_348301.json

AI QUESTION: How can I check how many active subscriptions I have in my session with the Binance WebSocket API?
Saved: logs/binance_agent_v2_20260328_015957_21d203.json

AI QUESTION: What is the response format for the User Data Stream events?
Saved: logs/binance_agent_v2_20260328_020011_347f4d.json

AI QUESTION: How do the rate limits work for the Binance API?
Saved: logs/binance_agent_v2_20260328_020033_667c72.json

AI QUESTION: Can I receive market data without an authenticated session on Binance?
Saved: logs/binance_agent_v2_20260328_020037_def460.json

In [106]:
import json
from pathlib import Path
from collections import Counter

sources = []
for f in Path("logs").glob("*.json"):
    with open(f, "r", encoding="utf-8") as infile:
        sources.append(json.load(infile).get("source"))

Counter(sources)

Counter({'user': 12, 'ai-generated': 10})

In [107]:
df["source"].value_counts()

source
user    12
Name: count, dtype: int64

In [118]:
df_ai = df[df["source"] == "ai-generated"]
df_ai.mean(numeric_only=True)

instructions_follow    1.0
answer_relevant        1.0
answer_clear           1.0
answer_citations       1.0
completeness           1.0
tool_call_search       1.0
dtype: float64

In [117]:
# user questions
df_user = df[df["source"] == "user"]

# AI-generated questions
df_ai = df[df["source"] == "ai-generated"]

# split by version
df_v1 = df[df["agent_version"] == "v1"]
df_v2 = df[df["agent_version"] == "v2"]

In [119]:
print("V1 performance:")
print(df_v1.mean(numeric_only=True))

print("\nV2 performance:")
print(df_v2.mean(numeric_only=True))

V1 performance:
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.333333
completeness           0.666667
tool_call_search       1.000000
dtype: float64

V2 performance:
instructions_follow    1.0000
answer_relevant        1.0000
answer_clear           1.0000
answer_citations       0.9375
completeness           0.9375
tool_call_search       1.0000
dtype: float64

In [120]:
print("User questions:")
print(df_user.mean(numeric_only=True))

print("\nAI-generated questions:")
print(df_ai.mean(numeric_only=True))

User questions:
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.583333
completeness           0.750000
tool_call_search       1.000000
dtype: float64

AI-generated questions:
instructions_follow    1.0
answer_relevant        1.0
answer_clear           1.0
answer_citations       1.0
completeness           1.0
tool_call_search       1.0
dtype: float64