In [1]:
from pathlib import Path
import sys

project_root = Path("..").resolve()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import logging_utils
print(logging_utils.__file__)

/workspaces/buidling_AI_agents/aihero/project/logging_utils.py

In [2]:
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
from pydantic_ai import Agent
from typing import List, Any

In [4]:
import sys
print(sys.executable)

/workspaces/buidling_AI_agents/aihero/project/.venv/bin/python

In [5]:
from pydantic_ai import Agent
print("import works")

import works

In [6]:
from pathlib import Path
import json

project_root = Path("..")
with open(project_root / "my_chunks_sections.json", "r", encoding="utf-8") as f:
    my_chunks_sections = json.load(f)

len(my_chunks_sections)
my_chunks_sections[0]

{'filename': 'binance-spot-api-docs-master/CHANGELOG_CN.md',
 'section': '## REST API\n\n- `POST /api/v3/userDataStream`\n- `PUT /api/v3/userDataStream`\n- `DELETE /api/v3/userDataStream`'}

In [7]:
from minsearch import Index, VectorSearch
from sentence_transformers import SentenceTransformer
from tqdm.auto import tqdm
import numpy as np

print("all imports work")

all imports work

In [8]:
def normalize_binance_chunks(chunks):
    normalized = []

    for i, doc in enumerate(chunks):
        item = dict(doc)

        chunk_text = (
            item.get("chunk")
            or item.get("content")
            or item.get("text")
            or ""
        )

        title = item.get("title", "") or item.get("heading", "") or ""
        filename = (
            item.get("filename", "")
            or item.get("file_path", "")
            or item.get("path", "")
            or item.get("source", "")
            or ""
        )
        section = item.get("section", "") or item.get("header", "") or ""
        description = item.get("description", "") or ""

        normalized.append({
            "id": item.get("id", str(i)),
            "chunk": chunk_text,
            "title": title,
            "filename": filename,
            "section": section,
            "description": description,
            "url": item.get("url", ""),
            "raw": item
        })

    return normalized

In [9]:
binance_docs = []

for i, d in enumerate(my_chunks_sections):
    binance_docs.append({
        "id": str(i),
        "chunk": d.get("chunk", "") if isinstance(d, dict) else "",
        "title": d.get("title", "") if isinstance(d, dict) else "",
        "description": d.get("description", "") if isinstance(d, dict) else "",
        "filename": d.get("filename", "") if isinstance(d, dict) else "",
        "section": d.get("section", "") if isinstance(d, dict) else ""
    })

len(binance_docs)

367

In [10]:
binance_docs[0]

{'id': '0',
 'chunk': '',
 'title': '',
 'description': '',
 'filename': 'binance-spot-api-docs-master/CHANGELOG_CN.md',
 'section': '## REST API\n\n- `POST /api/v3/userDataStream`\n- `PUT /api/v3/userDataStream`\n- `DELETE /api/v3/userDataStream`'}

In [11]:
text_index = Index(
    text_fields=["chunk", "title", "description", "filename", "section"],
    keyword_fields=[]
)

text_index.fit(binance_docs)

In [12]:
query = "How do I sign a Binance Spot API request?"
text_results = text_index.search(query, num_results=5)
text_results

[{'id': '170',
  'chunk': '',
  'title': '',
  'description': '',
  'filename': 'binance-spot-api-docs-master/fix-api.md',
  'section': '## General API Information\n\n* FIX connections require TLS encryption. Please either use native TCP+TLS connection or set up a local proxy such as [stunnel](https://www.stunnel.org/) to handle TLS encryption.\n* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)\n  * This does not always mean that the request failed in the Matching Engine.\n  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.\n* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.\n* To ensure uninterrupted connectivity, please make sure that your client sends **SNI (Server Name Indication)** during the TLS handshake and performs certificate validation against the intended hostname. <br>\nClients that do not send SNI may receive an unexpected certificate, which can result in TLS handshake or hostname verification failures.\n\n<details>\n<summary>Example implementations</summary>\n\n### NodeJS\nIf you are using Node.js and connecting via raw TLS sockets (`tls.connect()`), you must explicitly set the servername option. Please refer to the sample below:\n\n```javascript\n  const tls = require("tls");\n  const hostname = "fix-dc.binance.com"; //EXAMPLE\n\n  const options = {\n     host: hostname,\n     port: 9002,\n     servername: hostname                // enables SNI\n   };\n```\n\nNote that: NodeJS doesn\'t enable SNI by default for TLS (See [https://nodejs.org/api/tls.html#tlsconnectoptions-callback](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)). <br>\nIf you are using standard HTTPS libraries in Node.js (e.g., `https.request()`, `axios`, `fetch`), these typically set SNI automatically when connecting via a hostname/URL.\n\n### Other languages/custom TLS implementations\nWhen using custom TLS agents / TLS APIs, ensure you set the equivalent field (often named `server_hostname`, `hostname`, or `ServerName`) to the endpoint hostname so SNI is sent.\n</details>\n\n**FIX sessions only support Ed25519 keys.** </br>\n\nPlease refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)\non how to set up an Ed25519 key pair.\n\n### FIX API Order Entry sessions\n\n* Endpoint is: `tcp+tls://fix-oe.binance.com:9000`\n* Supports placing orders, canceling orders, and querying current limit usage.\n* Supports receiving all of the account\'s [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).\n* Only API keys with `FIX_API` are allowed to connect.\n* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).\n\n### FIX API Drop Copy sessions\n\n* Endpoint is: `tcp+tls://fix-dc.binance.com:9000`\n* Supports receiving all of the account\'s [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).\n* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.\n* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).\n* Data in Drop Copy sessions is delayed by 1 second.\n\n### FIX API Market Data sessions\n\n* Endpoint is: `tcp+tls://fix-md.binance.com:9000`\n* Supports market data streams and active instruments queries.\n* Does not support placing or canceling orders.\n* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.\n* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml).\n\n### FIX Connection Lifecycle\n\n* All FIX API sessions will remain open for as long as possible, on a best-effort basis.\n* There is no minimum connection time guarantee; a server can enter maintenance at any time.\n  * When a server enters maintenance, a [News `<B>`](#news) message will be sent to clients **every 10 seconds for 10 minutes**, prompting clients to reconnect. Upon receiving this message, a client is expected to establish a new session and close the old one. If the client does not close the old session within the time frame, the server will proceed to log it out and close the session.\n* After connecting, the client must send a Logon `<A>` request. For more information please refer to [How to sign a Logon request](#signaturecomputation).\n* The client should send a Logout `<5>` message to close the session before disconnecting. Failure to send the logout message will result in the session’s `SenderCompID (49)` being unusable for new session establishment for a duration of 2x the `HeartInt (108)` interval.\n* The system allows negotiation of the `HeartInt (108)` value during the logon process. Accepted values range between 5 and 60 seconds.\n  * If the server has not sent any messages within a `HeartInt (108)` interval, a [HeartBeat `<0>`](#heartbeat)  will be sent.\n  * If the server has not received any messages within a `HeartInt (108)` interval, a [TestRequest `<1>`](#testrequest) will be sent. If the server does not receive a HeartBeat `<0>` containing the expected `TestReqID (112)` from the client within `HeartInt (108)` seconds, the server will send a Logout `<5>` message and close the connection.\n  * If the client has not received any messages within a `HeartInt (108)` interval, the client is responsible for sending a TestRequest `<1>` to ensure the connection is healthy. Upon receiving such a TestRequest `<1>`, the server will respond with a Heartbeat `<0>` containing the expected `TestReqID (112)`. If the client does not receive the server’s response within a `HeartInt (108)` interval, the client should close the session and connection and establish new ones.\n\n### API Key Permissions\n\nTo access the FIX API order entry sessions, your API key must be configured with the `FIX_API` permission.\n\nTo access the FIX Drop Copy sessions, your API key must be configured with either `FIX_API_READ_ONLY` or `FIX_API` permission.\n\nTo access the FIX Market Data sessions, your API key must be configured with either `FIX_API` or `FIX_API_READ_ONLY` permission.\n\n**FIX sessions only support Ed25519 keys.**\n\nPlease refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)\non how to set up an Ed25519 key pair.\n\n<a id="orderedmode"></a>\n\n### On message processing order\n\nThe `MessageHandling (25035)` field required in the initial [Logon`<A>`](#logon-request) message controls whether messages from the client may be reordered before they are processed by the Matching Engine.\n\n| Mode            | Description                                                                                |\n|-----------------|--------------------------------------------------------------------------------------------|\n| `UNORDERED(1)`  | Messages from the client are allowed to be sent to the matching engine in any order.       |\n| `SEQUENTIAL(2)` | Messages from the client are always sent to the matching engine in `MsgSeqNum (34)` order. |\n\nIn all modes, the client\'s `MsgSeqNum (34)` must increase monotonically, with each subsequent message having a sequence number that is exactly 1 greater than the previous message.\n\n> [!TIP]\n> `UNORDERED(1)` should offer better performance when there are multiple messages in flight from the client to the server.\n\n<a id="responsemode"></a>\n\n### Response Mode\n\nBy default, all concurrent order entry sessions receive all of the account\'s\nsuccessful [ExecutionReport`<8>`](#executionreport) and [ListStatus`<N>`](#liststatus) messages,\nincluding those in response to orders placed from other FIX sessions and via non-FIX APIs.\n\nUse the `ResponseMode (25036)` field in the initial [Logon`<A>`](#logon-request) message\nto change this behavior.\n\n- `EVERYTHING(1)`: The default mode.\n- `ONLY_ACKS(2)`: Receive only ACK messages whether operation succeeded or failed. Disables ExecutionReport push.\n\n<a id="timingsecurity"></a>\n\n### Timing Security\n\n* All requests require a `SendingTime(52)` field which should be the current timestamp.\n* An additional optional field, `RecvWindow(25000)`, specifies for how long the request stays valid in milliseconds.\n  * `RecvWindow(25000)` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.\n  * If `RecvWindow(25000)` is not specified, it defaults to 5000 milliseconds only for the Logon`<A>` request. For other requests if unset, the RecvWindow check is not executed.\n  * Maximum `RecvWindow(25000)` is 60000 milliseconds.\n* Request processing logic is as follows:\n\n```javascript\nserverTime = getCurrentTime()\nif (SendingTime < (serverTime + 1 second) && (serverTime - SendingTime) <= RecvWindow) {\n  // begin processing request\n  serverTime = getCurrentTime()\n  if (serverTime - SendingTime) <= RecvWindow {\n    // forward request to Matching Engine\n  } else {\n    // reject request\n  }\n  // finish processing request\n} else {\n  // reject request\n}\n```\n\n<a id="signaturecomputation"></a>\n\n### How to sign Logon `<A>` request\n\nThe [Logon`<A>`](#logon-main) message authenticates your connection to the FIX API.\nThis must be the first message sent by the client.\n\n* The `Username (553)` field is required to contain the API key.\n* The `RawData (96)` field is required to contain a valid signature made with the API key.\n\nThe signature payload is a text string constructed by concatenating the values of the following fields in this exact order,\nseparated by the SOH character:\n\n1. `MsgType (35)`\n2. `SenderCompId (49)`\n3. `TargetCompId (56)`\n4. `MsgSeqNum (34)`\n5. `SendingTime (52)`\n\n\nSign the payload using your private key.\nEncode the signature with **base64**.\nThe resulting text string is the value of the `RawData (96)` field.\n\nHere is a sample Python code implementing the signature algorithm:\n\n````python\nimport base64\n\nfrom cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey\nfrom cryptography.hazmat.primitives.serialization import load_pem_private_key\n\ndef logon_raw_data(private_key: Ed25519PrivateKey,\n                   sender_comp_id: str,\n                   target_comp_id: str,\n                   msg_seq_num: str,\n                   sending_time: str):\n    """\n    Computes the value of RawData (96) field in Logon<A> message.\n    """\n    payload = chr(1).join([\n        \'A\',\n        sender_comp_id,\n        target_comp_id,\n        msg_seq_num,\n        sending_time,\n    ])\n    signature = private_key.sign(payload.encode(\'ASCII\'))\n    return base64.b64encode(signature).decode(\'ASCII\')\n\n\nwith open(\'private_key.pem\', \'rb\') as f:\n    private_key = load_pem_private_key(data=f.read(),\n                                       password=None)\n\nraw_data = logon_raw_data(private_key,\n                          sender_comp_id=\'5JQmUOsm\',\n                          target_comp_id=\'SPOT\',\n                          msg_seq_num=\'1\',\n                          sending_time=\'20240612-08:52:21.613\')\n````\n\nThe values presented below can be used to validate the correctness of the signature computation implementation:\n\n| Field             | Value                   |\n|-------------------|-------------------------|\n| MsgType (35)      | `A`                     |\n| SenderCompID (49) | `EXAMPLE`               |\n| TargetCompID (56) | `SPOT`                  |\n| MsgSeqNum (34)    | `1`                     |\n| SendingTime (52)  | `20240627-11:17:25.223` |\n\nThe Ed25519 private key used in the example computation is shown below:\n\n> [!CAUTION]\n> The following secret key is provided solely for illustrative purposes. Do not use this key in any real-world application as it is not secure and may compromise your cryptographic implementation. Always generate your own unique and secure keys for actual use.\n\n```\n-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIIJEYWtGBrhACmb9Dvy+qa8WEf0lQOl1s4CLIAB9m89u\n-----END PRIVATE KEY-----\n```\n\nComputed signature:\n```\n4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==\n```\n\nResulting Logon `<A>` message:\n```\n8=FIX.4.4|9=247|35=A|34=1|49=EXAMPLE|52=20240627-11:17:25.223|56=SPOT|95=88|96=4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==|98=0|108=30|141=Y|553=sBRXrJx2DsOraMXOaUovEhgVRcjOvCtQwnWj8VxkOh1xqboS02SPGfKi2h8spZJb|25035=2|10=227|\n```'},
 {'id': '193',
  'chunk': '',
  'title': '',
  'description': '',
  'filename': 'binance-spot-api-docs-master/rest-api.md',
  'section': '## General endpoints\n\n### Test connectivity\n```\nGET /api/v3/ping\n```\nTest connectivity to the Rest API.\n\n**Weight:**\n1\n\n**Parameters:**\nNONE\n\n**Data Source:**\nMemory\n\n**Response:**\n```javascript\n{}\n```\n\n### Check server time\n```\nGET /api/v3/time\n```\nTest connectivity to the Rest API and get the current server time.\n\n**Weight:**\n1\n\n**Parameters:**\nNONE\n\n**Data Source:**\nMemory\n\n**Response:**\n```javascript\n{\n    "serverTime": 1499827319559\n}\n```\n\n<a id="exchangeInfo"></a>\n\n### Exchange information\n```\nGET /api/v3/exchangeInfo\n```\nCurrent exchange trading rules and symbol information\n\n**Weight:**\n20\n\n**Parameters:**\n\nName | Type | Mandatory | Description\n------------ | ------------ | ------------ | ------------\nsymbol |STRING| No| Example: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"\nsymbols |ARRAY OF STRING|No| Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbols=%5B%22BNBBTC%22,%22BTCUSDT%22%5D" <br/> or <br/> curl -g -X  GET \'https://api.binance.com/api/v3/exchangeInfo?symbols=["BTCUSDT","BNBBTC"]\'\npermissions |ENUM|No|Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=SPOT" <br/> or <br/> curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=%5B%22MARGIN%22%2C%22LEVERAGED%22%5D" <br/> or <br/> curl -g -X GET \'https://api.binance.com/api/v3/exchangeInfo?permissions=["MARGIN","LEVERAGED"]\' |\nshowPermissionSets|BOOLEAN|No|Controls whether the content of the `permissionSets` field is populated or not. Defaults to `true`\nsymbolStatus|ENUM|No|Filters for symbols that have this `tradingStatus`. Valid values: `TRADING`, `HALT`, `BREAK` <br> Cannot be used in combination with `symbols` or `symbol`.|\n\n**Notes:**\n* If the value provided to `symbol` or `symbols` do not exist, the endpoint will throw an error saying the symbol is invalid.\n* All parameters are optional.\n* `permissions` can support single or multiple values (e.g. `SPOT`, `["MARGIN","LEVERAGED"]`). This cannot be used in combination with `symbol` or `symbols`.\n* If `permissions` parameter not provided, all symbols that have either `SPOT`, `MARGIN`, or `LEVERAGED` permission will be exposed.\n  * To display symbols with any permission you need to specify them explicitly in `permissions`: (e.g. `["SPOT","MARGIN",...]`.). See [Account and Symbol Permissions](enums.md#account-and-symbol-permissions) for the full list.\n\n<a id="examples-of-symbol-permissions-interpretation-from-the-response"></a>\n\n**Examples of Symbol Permissions Interpretation from the Response:**\n\n* `[["A","B"]]` means you may place an order if your account has either permission "A" **or** permission "B".\n* `[["A"],["B"]]` means you can place an order if your account has permission "A" **and** permission "B".\n* `[["A"],["B","C"]]` means you can place an order if your account has permission "A" **and** permission "B" or permission "C". (Inclusive or is applied here, not exclusive or, so your account may have both permission "B" and permission "C".)\n\n**Data Source:**\nMemory\n\n**Response:**\n```javascript\n{\n    "timezone": "UTC",\n    "serverTime": 1565246363776,\n    "rateLimits": [\n        {\n            // These are defined in the `ENUM definitions` section under `Rate Limiters (rateLimitType)`.\n            // All limits are optional\n        }\n    ],\n    "exchangeFilters": [\n        // These are the defined filters in the `Filters` section.\n        // All filters are optional.\n    ],\n    "symbols": [\n        {\n            "symbol": "ETHBTC",\n            "status": "TRADING",\n            "baseAsset": "ETH",\n            "baseAssetPrecision": 8,\n            "quoteAsset": "BTC",\n            "quotePrecision": 8,     // will be removed in future api versions (v4+)\n            "quoteAssetPrecision": 8,\n            "baseCommissionPrecision": 8,\n            "quoteCommissionPrecision": 8,\n            "orderTypes": [\n                "LIMIT",\n                "LIMIT_MAKER",\n                "MARKET",\n                "STOP_LOSS",\n                "STOP_LOSS_LIMIT",\n                "TAKE_PROFIT",\n                "TAKE_PROFIT_LIMIT"\n            ],\n            "icebergAllowed": true,\n            "ocoAllowed": true,\n            "otoAllowed": true,\n            "opoAllowed": true,\n            "quoteOrderQtyMarketAllowed": true,\n            "allowTrailingStop": false,\n            "cancelReplaceAllowed": false,\n            "amendAllowed": false,\n            "pegInstructionsAllowed": true,\n            "isSpotTradingAllowed": true,\n            "isMarginTradingAllowed": true,\n            "filters": [\n                // These are defined in the Filters section.\n                // All filters are optional\n            ],\n            "permissions": [],\n            "permissionSets": [["SPOT", "MARGIN"]],\n            "defaultSelfTradePreventionMode": "NONE",\n            "allowedSelfTradePreventionModes": ["NONE"]\n        }\n    ],\n    // Optional field. Present only when SOR is available.\n    // https://github.com/binance/binance-spot-api-docs/blob/master/faqs/sor_faq.md\n    "sors": [\n        {\n            "baseAsset": "BTC",\n            "symbols": ["BTCUSDT", "BTCUSDC"]\n        }\n    ]\n}\n```\n\n### Query Execution Rules\n\n```\nGET /api/v3/executionRules\n```\n\n**Weight**\n\nParameter | Weight|\n---        | ---\n`symbol`  | 2\n`symbols` | 2 for each `symbol`, capped at a max of 40|\n`symbolStatus` |40|\nNone            |40|\n\n**Parameters:**\n\nName | Type | Mandatory | Description\n------------ | ------------ | ------------ | ------------\n`symbol`   | STRING| No      | Query for specified symbol\n`symbols`  | STRING | No     | Query for multiple symbols\n`symbolStatus` |ENUM| Query for all symbols with the specified status. Supported values: `TRADING`, `HALT`, `BREAK`\n\n\n**Note:** No combination of multiple parameters is allowed.\n\n**Data Source:** Memory\n\n**Response:**\n\n```javascript\n{\n    "symbolRules": [\n        {\n            "symbol": "BAZUSD",\n            "rules": [\n                {\n                    "ruleType": "PRICE_RANGE",\n                    "bidLimitMultUp": "1.0001",\n                    "bidLimitMultDown": "0.9999",\n                    "askLimitMultUp": "1.0001",\n                    "askLimitMultDown": "0.9999"\n                }\n            ]\n        }\n    ]\n}\n```'},
 {'id': '186',
  'chunk': '',
  'title': '',
  'description': '',
  'filename': 'binance-spot-api-docs-master/rest-api.md',

In [13]:
def preview_results(results, max_chars=300):
    for i, r in enumerate(results, 1):
        print(f"\nResult #{i}")
        print("title:      ", r.get("title", ""))
        print("section:    ", r.get("section", ""))
        print("filename:   ", r.get("filename", ""))
        print("chunk:      ", r.get("chunk", "")[:max_chars])
        print("-" * 80)

In [14]:
preview_results(text_results)

Result #1
title:
section:     ## General API Information

* FIX connections require TLS encryption. Please either use native TCP+TLS connection or set up a local proxy such as [stunnel](https://www.stunnel.org/) to handle TLS encryption.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* To ensure uninterrupted connectivity, please make sure that your client sends **SNI (Server Name Indication)** during the TLS handshake and performs certificate validation against the intended hostname. <br>
Clients that do not send SNI may receive an unexpected certificate, which can result in TLS handshake or hostname verification failures.

<details>
<summary>Example implementations</summary>

### NodeJS
If you are using Node.js and connecting via raw TLS sockets (`tls.connect()`), you must explicitly set the servername option. Please refer to the sample below:

```javascript
  const tls = require("tls");
  const hostname = "fix-dc.binance.com"; //EXAMPLE

  const options = {
     host: hostname,
     port: 9002,
     servername: hostname                // enables SNI
   };
```

Note that: NodeJS doesn't enable SNI by default for TLS (See [https://nodejs.org/api/tls.html#tlsconnectoptions-callback](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)). <br>
If you are using standard HTTPS libraries in Node.js (e.g., `https.request()`, `axios`, `fetch`), these typically set SNI automatically when connecting via a hostname/URL.

### Other languages/custom TLS implementations
When using custom TLS agents / TLS APIs, ensure you set the equivalent field (often named `server_hostname`, `hostname`, or `ServerName`) to the endpoint hostname so SNI is sent.
</details>

**FIX sessions only support Ed25519 keys.** </br>

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

### FIX API Order Entry sessions

* Endpoint is: `tcp+tls://fix-oe.binance.com:9000`
* Supports placing orders, canceling orders, and querying current limit usage.
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).

### FIX API Drop Copy sessions

* Endpoint is: `tcp+tls://fix-dc.binance.com:9000`
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).
* Data in Drop Copy sessions is delayed by 1 second.

### FIX API Market Data sessions

* Endpoint is: `tcp+tls://fix-md.binance.com:9000`
* Supports market data streams and active instruments queries.
* Does not support placing or canceling orders.
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml).

### FIX Connection Lifecycle

* All FIX API sessions will remain open for as long as possible, on a best-effort basis.
* There is no minimum connection time guarantee; a server can enter maintenance at any time.
  * When a server enters maintenance, a [News `<B>`](#news) message will be sent to clients **every 10 seconds for 10 minutes**, prompting clients to reconnect. Upon receiving this message, a client is expected to establish a new session and close the old one. If the client does not close the old session within the time frame, the server will proceed to log it out and close the session.
* After connecting, the client must send a Logon `<A>` request. For more information please refer to [How to sign a Logon request](#signaturecomputation).
* The client should send a Logout `<5>` message to close the session before disconnecting. Failure to send the logout message will result in the session’s `SenderCompID (49)` being unusable for new session establishment for a duration of 2x the `HeartInt (108)` interval.
* The system allows negotiation of the `HeartInt (108)` value during the logon process. Accepted values range between 5 and 60 seconds.
  * If the server has not sent any messages within a `HeartInt (108)` interval, a [HeartBeat `<0>`](#heartbeat)  will be sent.
  * If the server has not received any messages within a `HeartInt (108)` interval, a [TestRequest `<1>`](#testrequest) will be sent. If the server does not receive a HeartBeat `<0>` containing the expected `TestReqID (112)` from the client within `HeartInt (108)` seconds, the server will send a Logout `<5>` message and close the connection.
  * If the client has not received any messages within a `HeartInt (108)` interval, the client is responsible for sending a TestRequest `<1>` to ensure the connection is healthy. Upon receiving such a TestRequest `<1>`, the server will respond with a Heartbeat `<0>` containing the expected `TestReqID (112)`. If the client does not receive the server’s response within a `HeartInt (108)` interval, the client should close the session and connection and establish new ones.

### API Key Permissions

To access the FIX API order entry sessions, your API key must be configured with the `FIX_API` permission.

To access the FIX Drop Copy sessions, your API key must be configured with either `FIX_API_READ_ONLY` or `FIX_API` permission.

To access the FIX Market Data sessions, your API key must be configured with either `FIX_API` or `FIX_API_READ_ONLY` permission.

**FIX sessions only support Ed25519 keys.**

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

<a id="orderedmode"></a>

### On message processing order

The `MessageHandling (25035)` field required in the initial [Logon`<A>`](#logon-request) message controls whether messages from the client may be reordered before they are processed by the Matching Engine.

| Mode            | Description                                                                                |
|-----------------|--------------------------------------------------------------------------------------------|
| `UNORDERED(1)`  | Messages from the client are allowed to be sent to the matching engine in any order.       |
| `SEQUENTIAL(2)` | Messages from the client are always sent to the matching engine in `MsgSeqNum (34)` order. |

In all modes, the client's `MsgSeqNum (34)` must increase monotonically, with each subsequent message having a sequence number that is exactly 1 greater than the previous message.

> [!TIP]
> `UNORDERED(1)` should offer better performance when there are multiple messages in flight from the client to the server.

<a id="responsemode"></a>

### Response Mode

By default, all concurrent order entry sessions receive all of the account's
successful [ExecutionReport`<8>`](#executionreport) and [ListStatus`<N>`](#liststatus) messages,
including those in response to orders placed from other FIX sessions and via non-FIX APIs.

Use the `ResponseMode (25036)` field in the initial [Logon`<A>`](#logon-request) message
to change this behavior.

- `EVERYTHING(1)`: The default mode.
- `ONLY_ACKS(2)`: Receive only ACK messages whether operation succeeded or failed. Disables ExecutionReport push.

<a id="timingsecurity"></a>

### Timing Security

* All requests require a `SendingTime(52)` field which should be the current timestamp.
* An additional optional field, `RecvWindow(25000)`, specifies for how long the request stays valid in milliseconds.
  * `RecvWindow(25000)` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.
  * If `RecvWindow(25000)` is not specified, it defaults to 5000 milliseconds only for the Logon`<A>` request. For other requests if unset, the RecvWindow check is not executed.
  * Maximum `RecvWindow(25000)` is 60000 milliseconds.
* Request processing logic is as follows:

```javascript
serverTime = getCurrentTime()
if (SendingTime < (serverTime + 1 second) && (serverTime - SendingTime) <= RecvWindow) {
  // begin processing request
  serverTime = getCurrentTime()
  if (serverTime - SendingTime) <= RecvWindow {
    // forward request to Matching Engine
  } else {
    // reject request
  }
  // finish processing request
} else {
  // reject request
}
```

<a id="signaturecomputation"></a>

### How to sign Logon `<A>` request

The [Logon`<A>`](#logon-main) message authenticates your connection to the FIX API.
This must be the first message sent by the client.

* The `Username (553)` field is required to contain the API key.
* The `RawData (96)` field is required to contain a valid signature made with the API key.

The signature payload is a text string constructed by concatenating the values of the following fields in this exact order,
separated by the SOH character:

1. `MsgType (35)`
2. `SenderCompId (49)`
3. `TargetCompId (56)`
4. `MsgSeqNum (34)`
5. `SendingTime (52)`


Sign the payload using your private key.
Encode the signature with **base64**.
The resulting text string is the value of the `RawData (96)` field.

Here is a sample Python code implementing the signature algorithm:

````python
import base64

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import load_pem_private_key

def logon_raw_data(private_key: Ed25519PrivateKey,
                   sender_comp_id: str,
                   target_comp_id: str,
                   msg_seq_num: str,
                   sending_time: str):
    """
    Computes the value of RawData (96) field in Logon<A> message.
    """
    payload = chr(1).join([
        'A',
        sender_comp_id,
        target_comp_id,
        msg_seq_num,
        sending_time,
    ])
    signature = private_key.sign(payload.encode('ASCII'))
    return base64.b64encode(signature).decode('ASCII')


with open('private_key.pem', 'rb') as f:
    private_key = load_pem_private_key(data=f.read(),
                                       password=None)

raw_data = logon_raw_data(private_key,
                          sender_comp_id='5JQmUOsm',
                          target_comp_id='SPOT',
                          msg_seq_num='1',
                          sending_time='20240612-08:52:21.613')
````

The values presented below can be used to validate the correctness of the signature computation implementation:

| Field             | Value                   |
|-------------------|-------------------------|
| MsgType (35)      | `A`                     |
| SenderCompID (49) | `EXAMPLE`               |
| TargetCompID (56) | `SPOT`                  |
| MsgSeqNum (34)    | `1`                     |
| SendingTime (52)  | `20240627-11:17:25.223` |

The Ed25519 private key used in the example computation is shown below:

> [!CAUTION]
> The following secret key is provided solely for illustrative purposes. Do not use this key in any real-world application as it is not secure and may compromise your cryptographic implementation. Always generate your own unique and secure keys for actual use.

```
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIIJEYWtGBrhACmb9Dvy+qa8WEf0lQOl1s4CLIAB9m89u
-----END PRIVATE KEY-----
```

Computed signature:
```
4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==
```

Resulting Logon `<A>` message:
```
8=FIX.4.4|9=247|35=A|34=1|49=EXAMPLE|52=20240627-11:17:25.223|56=SPOT|95=88|96=4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==|98=0|108=30|141=Y|553=sBRXrJx2DsOraMXOaUovEhgVRcjOvCtQwnWj8VxkOh1xqboS02SPGfKi2h8spZJb|25035=2|10=227|
```
filename:    binance-spot-api-docs-master/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## General endpoints

### Test connectivity
```
GET /api/v3/ping
```
Test connectivity to the Rest API.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{}
```

### Check server time
```
GET /api/v3/time
```
Test connectivity to the Rest API and get the current server time.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{
    "serverTime": 1499827319559
}
```

<a id="exchangeInfo"></a>

### Exchange information
```
GET /api/v3/exchangeInfo
```
Current exchange trading rules and symbol information

**Weight:**
20

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
symbol |STRING| No| Example: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"
symbols |ARRAY OF STRING|No| Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbols=%5B%22BNBBTC%22,%22BTCUSDT%22%5D" <br/> or <br/> curl -g -X  GET 'https://api.binance.com/api/v3/exchangeInfo?symbols=["BTCUSDT","BNBBTC"]'
permissions |ENUM|No|Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=SPOT" <br/> or <br/> curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=%5B%22MARGIN%22%2C%22LEVERAGED%22%5D" <br/> or <br/> curl -g -X GET 'https://api.binance.com/api/v3/exchangeInfo?permissions=["MARGIN","LEVERAGED"]' |
showPermissionSets|BOOLEAN|No|Controls whether the content of the `permissionSets` field is populated or not. Defaults to `true`
symbolStatus|ENUM|No|Filters for symbols that have this `tradingStatus`. Valid values: `TRADING`, `HALT`, `BREAK` <br> Cannot be used in combination with `symbols` or `symbol`.|

**Notes:**
* If the value provided to `symbol` or `symbols` do not exist, the endpoint will throw an error saying the symbol is invalid.
* All parameters are optional.
* `permissions` can support single or multiple values (e.g. `SPOT`, `["MARGIN","LEVERAGED"]`). This cannot be used in combination with `symbol` or `symbols`.
* If `permissions` parameter not provided, all symbols that have either `SPOT`, `MARGIN`, or `LEVERAGED` permission will be exposed.
  * To display symbols with any permission you need to specify them explicitly in `permissions`: (e.g. `["SPOT","MARGIN",...]`.). See [Account and Symbol Permissions](enums.md#account-and-symbol-permissions) for the full list.

<a id="examples-of-symbol-permissions-interpretation-from-the-response"></a>

**Examples of Symbol Permissions Interpretation from the Response:**

* `[["A","B"]]` means you may place an order if your account has either permission "A" **or** permission "B".
* `[["A"],["B"]]` means you can place an order if your account has permission "A" **and** permission "B".
* `[["A"],["B","C"]]` means you can place an order if your account has permission "A" **and** permission "B" or permission "C". (Inclusive or is applied here, not exclusive or, so your account may have both permission "B" and permission "C".)

**Data Source:**
Memory

**Response:**
```javascript
{
    "timezone": "UTC",
    "serverTime": 1565246363776,
    "rateLimits": [
        {
            // These are defined in the `ENUM definitions` section under `Rate Limiters (rateLimitType)`.
            // All limits are optional
        }
    ],
    "exchangeFilters": [
        // These are the defined filters in the `Filters` section.
        // All filters are optional.
    ],
    "symbols": [
        {
            "symbol": "ETHBTC",
            "status": "TRADING",
            "baseAsset": "ETH",
            "baseAssetPrecision": 8,
            "quoteAsset": "BTC",
            "quotePrecision": 8,     // will be removed in future api versions (v4+)
            "quoteAssetPrecision": 8,
            "baseCommissionPrecision": 8,
            "quoteCommissionPrecision": 8,
            "orderTypes": [
                "LIMIT",
                "LIMIT_MAKER",
                "MARKET",
                "STOP_LOSS",
                "STOP_LOSS_LIMIT",
                "TAKE_PROFIT",
                "TAKE_PROFIT_LIMIT"
            ],
            "icebergAllowed": true,
            "ocoAllowed": true,
            "otoAllowed": true,
            "opoAllowed": true,
            "quoteOrderQtyMarketAllowed": true,
            "allowTrailingStop": false,
            "cancelReplaceAllowed": false,
            "amendAllowed": false,
            "pegInstructionsAllowed": true,
            "isSpotTradingAllowed": true,
            "isMarginTradingAllowed": true,
            "filters": [
                // These are defined in the Filters section.
                // All filters are optional
            ],
            "permissions": [],
            "permissionSets": [["SPOT", "MARGIN"]],
            "defaultSelfTradePreventionMode": "NONE",
            "allowedSelfTradePreventionModes": ["NONE"]
        }
    ],
    // Optional field. Present only when SOR is available.
    // https://github.com/binance/binance-spot-api-docs/blob/master/faqs/sor_faq.md
    "sors": [
        {
            "baseAsset": "BTC",
            "symbols": ["BTCUSDT", "BTCUSDC"]
        }
    ]
}
```

### Query Execution Rules

```
GET /api/v3/executionRules
```

**Weight**

Parameter | Weight|
---        | ---
`symbol`  | 2
`symbols` | 2 for each `symbol`, capped at a max of 40|
`symbolStatus` |40|
None            |40|

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
`symbol`   | STRING| No      | Query for specified symbol
`symbols`  | STRING | No     | Query for multiple symbols
`symbolStatus` |ENUM| Query for all symbols with the specified status. Supported values: `TRADING`, `HALT`, `BREAK`


**Note:** No combination of multiple parameters is allowed.

**Data Source:** Memory

**Response:**

```javascript
{
    "symbolRules": [
        {
            "symbol": "BAZUSD",
            "rules": [
                {
                    "ruleType": "PRICE_RANGE",
                    "bidLimitMultUp": "1.0001",
                    "bidLimitMultDown": "0.9999",
                    "askLimitMultUp": "1.0001",
                    "askLimitMultDown": "0.9999"
                }
            ]
        }
    ]
}
```
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## General API Information

* The following base endpoints are available. Please use whichever works best for your setup:
  * **https://api.binance.com**
  * **https://api-gcp.binance.com**
  * **https://api1.binance.com**
  * **https://api2.binance.com**
  * **https://api3.binance.com**
  * **https://api4.binance.com**
* The last 4 endpoints in the point above (`api1`-`api4`) should give better performance but have less stability.
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](./faqs/sbe_faq.md) page.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.

In [15]:
def normalize_binance_chunks(chunks):
    normalized = []

    for i, doc in enumerate(chunks):
        item = dict(doc)

        chunk_text = (
            item.get("chunk")
            or item.get("content")
            or item.get("text")
            or ""
        )

        title = item.get("title", "") or item.get("heading", "") or ""
        filename = (
            item.get("filename", "")
            or item.get("file_path", "")
            or item.get("path", "")
            or item.get("source", "")
            or ""
        )
        section = item.get("section", "") or item.get("header", "") or ""
        description = item.get("description", "") or ""

        normalized.append({
            "id": item.get("id", str(i)),
            "chunk": chunk_text,
            "title": title,
            "filename": filename,
            "section": section,
            "description": description,
            "url": item.get("url", ""),
            "raw": item
        })

    return normalized

normalized_chunks = normalize_binance_chunks(my_chunks_sections)

embedding_model = SentenceTransformer("multi-qa-distilbert-cos-v1")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

In [16]:
binance_embeddings = []

for d in tqdm(binance_docs):
    v = embedding_model.encode(d["chunk"])
    binance_embeddings.append(v)

binance_embeddings = np.array(binance_embeddings)
binance_embeddings.shape

  0%|          | 0/367 [00:00<?, ?it/s]

(367, 768)

In [17]:
vector_index = VectorSearch()
vector_index.fit(binance_embeddings, binance_docs)

In [18]:
query = "How can I authenticate a private Binance API endpoint?"
q = embedding_model.encode(query)

vector_results = vector_index.search(q, num_results=5)
preview_results(vector_results)

Result #1
title:
section:     ## 如何正确在本地维护一个order book副本

1. 打开与 `wss://stream.binance.com:9443/ws/bnbbtc@depth` 的 WebSocket 连接。
2. 开始缓存收到的event。请记录您收到的第一个event的 `U`值。
3. 访问 `https://api.binance.com/api/v3/depth?symbol=BNBBTC&limit=5000` 获取深度快照。
4. 如果快照中的 `lastUpdateId` 小于等于步骤 2 中的 `U` 值，请返回步骤 3。
5. 在收到的event中，丢弃快照中 `u` <= `lastUpdateId` 的所有event。现在第一个event的 `lastUpdateId` 应该在 `[U;u]` 范围以内。
6. 将本地order book设置为快照。它的更新ID 为 `lastUpdateId`。
7. 更新所有缓存的event，以及后续的所有event。

要将一个event应用于您的本地order book，请遵循以下更新过程：
1. 判断是否需要处理event：
    * 如果event的最后一次更新ID（`u`）小于本地order book的更新ID，忽略该event。
    * 如果event的首次更新ID（`U`）大于本地order book的更新ID加1，说明你错过了一些events。<br>请丢弃您的本地order book并从头开始重新同步。
    * 通常，下一event的`U`等于上一event的`u + 1`。
1. 对买价（`b`）和卖价（`a`）中的每个价位，设置order book中的新数量：
    * 如果该价位在order book中不存在，则插入该价位及其数量。
    * 如果数量为零，则从order book中删除此价位。
1. 将order book的更新ID设置为已处理event的最后一次更新ID（`u`）。

> [!NOTE]
> 由于从 API 检索的深度快照对价位的数量有限制（每侧最多 5000 个），因此除非它们发生变化，否则您将无法了解初始快照之外的价位数量。<br>
> 因此，在使用这些级别的信息时要小心，因为它们可能无法反映订单簿的完整视图。<br>
> 但是，对于大多数场景，可以每侧看到 5000 个价位就足以了解市场并进行有效交易。
filename:    binance-spot-api-docs-master/web-socket-streams_CN.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## Average Price

Average price streams push changes in the average price over a fixed time interval.

**Stream Name:** \<symbol\>@avgPrice

**Update Speed:** 1000ms

**Payload:**

```javascript
{
    "e": "avgPrice",           // Event type
    "E": 1693907033000,        // Event time
    "s": "BTCUSDT",            // Symbol
    "i": "5m",                 // Average price interval
    "w": "25776.86000000",     // Average price
    "T": 1693907032213         // Last trade time
}
```
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## Partial Book Depth Streams

Top **\<levels\>** bids and asks, pushed every second. Valid **\<levels\>** are 5, 10, or 20.

**Stream Names:** \<symbol\>@depth\<levels\> OR \<symbol\>@depth\<levels\>@100ms

**Update Speed:** 1000ms or 100ms

**Payload:**
```javascript
{
    "lastUpdateId": 160,     // Last update ID
    "bids": [                // Bids to be updated
        [
            "0.0024",        // Price level to be updated
            "10"             // Quantity
        ]
    ],
    "asks": [                // Asks to be updated
        [
            "0.0026",        // Price level to be updated
            "100"            // Quantity
        ]
    ]
}
```
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## Diff. Depth Stream

Order book price and quantity depth updates used to locally manage an order book.

**Stream Name:** \<symbol\>@depth OR \<symbol\>@depth@100ms

**Update Speed:** 1000ms or 100ms

**Payload:**
```javascript
{
    "e": "depthUpdate",     // Event type
    "E": 1672515782136,     // Event time
    "s": "BNBBTC",          // Symbol
    "U": 157,               // First update ID in event
    "u": 160,               // Final update ID in event
    "b": [                  // Bids to be updated
        [
            "0.0024",       // Price level to be updated
            "10"            // Quantity
        ]
    ],
    "a": [                  // Asks to be updated
        [
            "0.0026",       // Price level to be updated
            "100"           // Quantity
        ]
    ]
}
```
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## How to manage a local order book correctly

1. Open a WebSocket connection to `wss://stream.binance.com:9443/ws/bnbbtc@depth`.
1. Buffer the events received from the stream. Note the `U` of the first event you received.
1. Get a depth snapshot from `https://api.binance.com/api/v3/depth?symbol=BNBBTC&limit=5000`.
1. If the `lastUpdateId` from the snapshot is strictly less than the `U` from step 2, go back to step 3.
1. In the buffered events, discard any event where `u` is <= `lastUpdateId` of the snapshot. The first buffered event should now have `lastUpdateId` within its `[U;u]` range.
1. Set your local order book to the snapshot. Its update ID is `lastUpdateId`.
1. Apply the update procedure below to all buffered events, and then to all subsequent events received.

To apply an event to your local order book, follow this update procedure:
1. Decide whether the update event can be applied:
    * If the event last update ID (`u`) is less than the update ID of your local order book,
      ignore the event.
    * If the event first update ID (`U`) is greater than the update ID of your local order book + 1,
      you have missed some events. <br> Discard your local order book and restart the process from the beginning.
    * Normally, `U` of the next event is equal to `u + 1` of the previous event.
1. For each price level in bids (`b`) and asks (`a`), set the new quantity in the order book:
    * If the price level does not exist in the order book, insert it with new quantity.
    * If the quantity is zero, remove the price level from the order book.
1. Set the order book update ID to the last update ID (`u`) in the processed event.

> [!NOTE]
> Since depth snapshots retrieved from the API have a limit on the number of price levels (5000 on each side maximum), you won't learn the quantities for the levels outside of the initial snapshot unless they change. <br>
> So be careful when using the information for those levels, since they might not reflect the full view of the order book. <br>
> However, for most use cases, seeing 5000 levels on each side is enough to understand the market and trade effectively.
filename:    binance-spot-api-docs-master/web-socket-streams.md
chunk:
--------------------------------------------------------------------------------

In [19]:
def text_search(query, num_results=5):
    return text_index.search(query, num_results=num_results)


def vector_search(query, num_results=5):
    q = embedding_model.encode(query)
    return vector_index.search(q, num_results=num_results)

In [20]:
def hybrid_search(query: str, num_results: int = 5, text_k: int = 10, vector_k: int = 10):
    text_results = text_search(query, num_results=text_k)
    vector_results = vector_search(query, num_results=vector_k)

    scores = {}

    for rank, r in enumerate(text_results):
        rid = r.get("id") or r.get("chunk_id") or str(r)
        if rid not in scores:
            scores[rid] = {"doc": r, "score": 0.0}
        scores[rid]["score"] += 1.0 / (rank + 1)

    for rank, r in enumerate(vector_results):
        rid = r.get("id") or r.get("chunk_id") or str(r)
        if rid not in scores:
            scores[rid] = {"doc": r, "score": 0.0}
        scores[rid]["score"] += 1.0 / (rank + 1)

    ranked = sorted(scores.values(), key=lambda x: x["score"], reverse=True)
    return [x["doc"] for x in ranked[:num_results]]

In [21]:
query = "What does recvWindow mean in Binance API requests?"
hybrid_results = hybrid_search(query, num_results=5)
preview_results(hybrid_results)

Result #1
title:
section:     ## General API Information

* The following base endpoints are available. Please use whichever works best for your setup:
  * **https://api.binance.com**
  * **https://api-gcp.binance.com**
  * **https://api1.binance.com**
  * **https://api2.binance.com**
  * **https://api3.binance.com**
  * **https://api4.binance.com**
* The last 4 endpoints in the point above (`api1`-`api4`) should give better performance but have less stability.
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](./faqs/sbe_faq.md) page.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* Some endpoints may return asset and/or symbol names containing non-ASCII characters encoded in UTF-8 even if the request did not contain non-ASCII characters.
* Data is returned in **chronological order**, unless noted otherwise.
  * Without `startTime` or `endTime`, returns the most recent items up to the limit.
  * With `startTime`, returns oldest items from `startTime` up to the limit.
  * With `endTime`, returns most recent items up to `endTime` and the limit.
  * With both, behaves like `startTime` but does not exceed `endTime`.
* All time and timestamp related fields in the JSON responses are in **milliseconds by default.** To receive the information in microseconds, please add the header `X-MBX-TIME-UNIT:MICROSECOND` or `X-MBX-TIME-UNIT:microsecond`.
* We support HMAC, RSA, and Ed25519 keys. For more information, please see [API Key types](faqs/api_key_types.md).
* Timestamp parameters (e.g. `startTime`, `endTime`, `timestamp`) can be passed in milliseconds or microseconds.
* For APIs that only send public market data, please use the base endpoint **https://data-api.binance.vision**. Please refer to [Market Data Only](./faqs/market_data_only.md) page.
* If there are enums or terms you want clarification on, please see the [SPOT Glossary](faqs/spot_glossary.md) for more information.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* **Please avoid SQL keywords in requests** as they may trigger a security block by a WAF (Web Application Firewall) rule. See https://www.binance.com/en/support/faq/detail/360004492232 for more details.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* Some endpoints may return asset and/or symbol names containing non-ASCII characters encoded in UTF-8 even if the request did not contain non-ASCII characters.
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## Limits

### Message Limits

* Each connection has a limit on **how many messages can be sent to the exchange**.
* The message limit **does not count the messages sent in response to the client**.
* Breaching the message limit results in immediate [Logout `<5>`](#logout) and disconnection.
* To understand current limits and usage, please send a [LimitQuery`<XLQ>`](#limitquery) message.
  A [LimitResponse`<XLR>`](#limitresponse) message will be sent in response, containing information about Order Rate
  Limits and Message Limits.
* FIX Order entry sessions have a limit of 10,000 messages every 10 seconds.
* FIX Drop Copy sessions have a limit of 60 messages every 60 seconds.
* FIX Market Data sessions have a limit of 2000 messages every 60 seconds.

<a id="connection-limits"></a>

### Connection Limits

* Each Account has a limit on how many TCP connections can be established at the same time.
* The limit is reduced when the TCP connection is closed. If the reduction of connections is not immediate, please wait up to twice the value of `HeartBtInt (108)` for the change to take effect.
  For example, if the current value of `HeartBtInt` is 5, please wait up to 10 seconds.
* Upon breaching the limit a [Reject `<3>`](#reject) will be sent containing information about the connection limit
  breach and the current limit.
* FIX Order Entry limits:
   * 15 connection attempts within 30 seconds
   * Maximum of 10 concurrent TCP connections per account
* FIX Drop Copy limits:
    * 15 connection attempts within 30 seconds
    * Maximum of 10 concurrent TCP connections per account
* FIX Market Data limits
  * 300 connection attempts within 300 seconds
  * Maximum of 100 concurrent TCP connections per account
  * A single connection can listen to a maximum of 1000 streams.

### Unfilled Order Count

* To understand how many orders you have placed within a certain time interval, please send a [LimitQuery`<XLQ>`](#limitquery) message.
  A [LimitResponse`<XLR>`](#limitresponse) message will be sent in response, containing information about Unfilled Order Count and Message Limits.
* **Please note that if your orders are consistently filled by trades, you can continuously place orders on the API**. For more information, please see [Spot Unfilled Order Count Rules](../faqs/order_count_decrement.md).
* If you exceed the unfilled order count your message will be rejected, and information will be transferred back to you in a reject message specific to that endpoint.
* **The number of unfilled orders is tracked for each account.**
filename:    binance-spot-api-docs-master/testnet/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## General API Information

* The base endpoint is: **`wss://ws-api.binance.com:443/ws-api/v3`**.
  * If you experience issues with the standard 443 port, alternative port 9443 is also available.
  * The base endpoint for [testnet](https://testnet.binance.vision/) is: `wss://ws-api.testnet.binance.vision/ws-api/v3`
* A single connection to the API is only valid for 24 hours; expect to be disconnected after the 24-hour mark.
* Before a disconnection either due to maintenance or after 24 hours, a [`serverShutdown`](#server-shutdown) event will be sent. Please reconnect as soon as possible to prevent stream interruption.
* We support HMAC, RSA, and Ed25519 keys. For more information, please see [API Key types](faqs/api_key_types.md).
* Responses are in JSON by default. To receive responses in SBE, refer to the [SBE FAQ](faqs/sbe_faq.md) page.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* Some methods may return asset and/or symbol names containing non-ASCII characters encoded in UTF-8 even if the request did not contain non-ASCII characters.
* The WebSocket server will send a `ping frame` every 20 seconds.
  * If the WebSocket server does not receive a `pong frame` back from the connection within a minute the connection will be disconnected.
  * When you receive a ping, you must send a pong with a copy of ping's payload as soon as possible.
  * Unsolicited `pong frames` are allowed, but will not prevent disconnection. **It is recommended that the payload for these pong frames are empty.**
* Data is returned in **chronological order**, unless noted otherwise.
  * Without `startTime` or `endTime`, returns the most recent items up to the limit.
  * With `startTime`, returns oldest items from `startTime` up to the limit.
  * With `endTime`, returns most recent items up to `endTime` and the limit.
  * With both, behaves like `startTime` but does not exceed `endTime`.
* All timestamps in the JSON responses are in **milliseconds in UTC by default**. To receive the information in microseconds, please add the parameter `timeUnit=MICROSECOND` or `timeUnit=microsecond` in the URL.
* Timestamp parameters (e.g. `startTime`, `endTime`, `timestamp`) can be passed in milliseconds or microseconds.
* All field names and values are **case-sensitive**, unless noted otherwise.
* If there are enums or terms you want clarification on, please see [SPOT Glossary](faqs/spot_glossary.md) for more information.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* **Please avoid SQL keywords in requests** as they may trigger a security block by a WAF (Web Application Firewall) rule. See https://www.binance.com/en/support/faq/detail/360004492232 for more details.
filename:    binance-spot-api-docs-master/web-socket-api.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## LIMITS

### General Info on Limits
* The following `intervalLetter` values for headers:
    * SECOND => S
    * MINUTE => M
    * HOUR => H
    * DAY => D
* `intervalNum` describes the amount of the interval. For example, `intervalNum` 5 with `intervalLetter` M means "Every 5 minutes".
* The `/api/v3/exchangeInfo` `rateLimits` array contains objects related to the exchange's `RAW_REQUESTS`, `REQUEST_WEIGHT`, and `ORDERS` rate limits. These are further defined in the `ENUM definitions` section under `Rate limiters (rateLimitType)`.
* Requests fail with HTTP status code 429 when you exceed the request rate limit.

### IP Limits
* Every request will contain `X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter)` in the response headers which has the current used weight for the IP for all request rate limiters defined.
* Each route has a `weight` which determines for the number of requests each endpoint counts for. Heavier endpoints and endpoints that do operations on multiple symbols will have a heavier `weight`.
* When a 429 is received, it's your obligation as an API to back off and not spam the API.
* **Repeatedly violating rate limits and/or failing to back off after receiving 429s will result in an automated IP ban (HTTP status 418).**
* IP bans are tracked and **scale in duration** for repeat offenders, **from 2 minutes to 3 days**.
* A `Retry-After` header is sent with a 418 or 429 responses and will give the **number of seconds** required to wait, in the case of a 429, to prevent a ban, or, in the case of a 418, until the ban is over.
* **The limits on the API are based on the IPs, not the API keys.**

### Unfilled Order Count
* Every successful order response will contain a `X-MBX-ORDER-COUNT-(intervalNum)(intervalLetter)` header indicating how many orders you have placed for that interval. <br></br> To monitor this, refer to [`GET api/v3/rateLimit/order`](#query-unfilled-order-count).
* Rejected/unsuccessful orders are not guaranteed to have `X-MBX-ORDER-COUNT-**` headers in the response.
* If you have exceeded this, you will receive a 429 error with the `Retry-After` header.
* **Please note that if your orders are consistently filled by trades, you can continuously place orders on the API**. For more information, please see [Spot Unfilled Order Count Rules](../faqs/order_count_decrement.md).
* **The number of unfilled orders is tracked for each account.**
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## Session Authentication

**Note:** Only _Ed25519_ keys are supported for this feature.

If you do not want to specify `apiKey` and `signature` in each individual request,
you can authenticate your API key for the active WebSocket session.

Once authenticated, you no longer have to specify `apiKey` and `signature` for those requests that need them.
Requests will be performed on behalf of the account owning the authenticated API key.

**Note:** You still have to specify the `timestamp` parameter for `SIGNED` requests.

### Authenticate after connection

You can authenticate an already established connection using session authentication requests:

* [`session.logon`](#log-in-with-api-key-signed) – authenticate, or change the API key associated with the connection
* [`session.status`](#query-session-status) – check connection status and the current API key
* [`session.logout`](#log-out-of-the-session) – forget the API key associated with the connection

**Regarding API key revocation:**

If during an active session the API key becomes invalid for _any reason_ (e.g. IP address is not whitelisted, API key was deleted, API key doesn't have correct permissions, etc), after the next request the session will be revoked with the following error message:

```javascript
{
    "id": null,
    "status": 401,
    "error": {
        "code": -2015,
        "msg": "Invalid API-key, IP, or permissions for action."
    }
}
```

### Authorize _ad hoc_ requests

Only one API key can be authenticated with the WebSocket connection.
The authenticated API key is used by default for requests that require an `apiKey` parameter.
However, you can always specify the `apiKey` and `signature` explicitly for individual requests,
overriding the authenticated API key and using a different one to authorize a specific request.

For example, you might want to authenticate your `USER_DATA` key to be used by default,
but specify the `TRADE` key with an explicit signature when placing orders.
filename:    binance-spot-api-docs-master/web-socket-api.md
chunk:
--------------------------------------------------------------------------------

In [22]:
test_queries = [
    "How do I sign a Binance Spot API request?",
    "What does recvWindow mean?",
    "Why am I getting timestamp error?",
    "How do I place a market order?",
    "How can I authenticate a private endpoint?",
    "What are the rate limits?",
    "How do I get exchange info?"
]

for query in test_queries:
    print("\n" + "=" * 100)
    print("QUERY:", query)
    results = hybrid_search(query, num_results=3)
    preview_results(results, max_chars=220)

====================================================================================================
QUERY: How do I sign a Binance Spot API request?

Result #1
title:
section:     ## General API Information

* FIX connections require TLS encryption. Please either use native TCP+TLS connection or set up a local proxy such as [stunnel](https://www.stunnel.org/) to handle TLS encryption.
* APIs have a timeout of 10 seconds when processing a request. If a response from the Matching Engine takes longer than this, the API responds with "Timeout waiting for response from backend server. Send status unknown; execution status unknown." [(-1007 TIMEOUT)](errors.md#-1007-timeout)
  * This does not always mean that the request failed in the Matching Engine.
  * If the status of the request has not appeared in [User Data Stream](user-data-stream.md), please perform an API query for its status.
* If your request contains a symbol name containing non-ASCII characters, then the response may contain non-ASCII characters encoded in UTF-8.
* To ensure uninterrupted connectivity, please make sure that your client sends **SNI (Server Name Indication)** during the TLS handshake and performs certificate validation against the intended hostname. <br>
Clients that do not send SNI may receive an unexpected certificate, which can result in TLS handshake or hostname verification failures.

<details>
<summary>Example implementations</summary>

### NodeJS
If you are using Node.js and connecting via raw TLS sockets (`tls.connect()`), you must explicitly set the servername option. Please refer to the sample below:

```javascript
  const tls = require("tls");
  const hostname = "fix-dc.binance.com"; //EXAMPLE

  const options = {
     host: hostname,
     port: 9002,
     servername: hostname                // enables SNI
   };
```

Note that: NodeJS doesn't enable SNI by default for TLS (See [https://nodejs.org/api/tls.html#tlsconnectoptions-callback](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)). <br>
If you are using standard HTTPS libraries in Node.js (e.g., `https.request()`, `axios`, `fetch`), these typically set SNI automatically when connecting via a hostname/URL.

### Other languages/custom TLS implementations
When using custom TLS agents / TLS APIs, ensure you set the equivalent field (often named `server_hostname`, `hostname`, or `ServerName`) to the endpoint hostname so SNI is sent.
</details>

**FIX sessions only support Ed25519 keys.** </br>

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

### FIX API Order Entry sessions

* Endpoint is: `tcp+tls://fix-oe.binance.com:9000`
* Supports placing orders, canceling orders, and querying current limit usage.
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).

### FIX API Drop Copy sessions

* Endpoint is: `tcp+tls://fix-dc.binance.com:9000`
* Supports receiving all of the account's [ExecutionReport`<8>`](#executionreport) and [List Status`<N>`](#liststatus).
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml).
* Data in Drop Copy sessions is delayed by 1 second.

### FIX API Market Data sessions

* Endpoint is: `tcp+tls://fix-md.binance.com:9000`
* Supports market data streams and active instruments queries.
* Does not support placing or canceling orders.
* Only API keys with `FIX_API` or `FIX_API_READ_ONLY` are allowed to connect.
* QuickFIX Schema can be found [here](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml).

### FIX Connection Lifecycle

* All FIX API sessions will remain open for as long as possible, on a best-effort basis.
* There is no minimum connection time guarantee; a server can enter maintenance at any time.
  * When a server enters maintenance, a [News `<B>`](#news) message will be sent to clients **every 10 seconds for 10 minutes**, prompting clients to reconnect. Upon receiving this message, a client is expected to establish a new session and close the old one. If the client does not close the old session within the time frame, the server will proceed to log it out and close the session.
* After connecting, the client must send a Logon `<A>` request. For more information please refer to [How to sign a Logon request](#signaturecomputation).
* The client should send a Logout `<5>` message to close the session before disconnecting. Failure to send the logout message will result in the session’s `SenderCompID (49)` being unusable for new session establishment for a duration of 2x the `HeartInt (108)` interval.
* The system allows negotiation of the `HeartInt (108)` value during the logon process. Accepted values range between 5 and 60 seconds.
  * If the server has not sent any messages within a `HeartInt (108)` interval, a [HeartBeat `<0>`](#heartbeat)  will be sent.
  * If the server has not received any messages within a `HeartInt (108)` interval, a [TestRequest `<1>`](#testrequest) will be sent. If the server does not receive a HeartBeat `<0>` containing the expected `TestReqID (112)` from the client within `HeartInt (108)` seconds, the server will send a Logout `<5>` message and close the connection.
  * If the client has not received any messages within a `HeartInt (108)` interval, the client is responsible for sending a TestRequest `<1>` to ensure the connection is healthy. Upon receiving such a TestRequest `<1>`, the server will respond with a Heartbeat `<0>` containing the expected `TestReqID (112)`. If the client does not receive the server’s response within a `HeartInt (108)` interval, the client should close the session and connection and establish new ones.

### API Key Permissions

To access the FIX API order entry sessions, your API key must be configured with the `FIX_API` permission.

To access the FIX Drop Copy sessions, your API key must be configured with either `FIX_API_READ_ONLY` or `FIX_API` permission.

To access the FIX Market Data sessions, your API key must be configured with either `FIX_API` or `FIX_API_READ_ONLY` permission.

**FIX sessions only support Ed25519 keys.**

Please refer to [this tutorial](https://www.binance.com/en/support/faq/how-to-generate-an-ed25519-key-pair-to-send-api-requests-on-binance-6b9a63f1e3384cf48a2eedb82767a69a)
on how to set up an Ed25519 key pair.

<a id="orderedmode"></a>

### On message processing order

The `MessageHandling (25035)` field required in the initial [Logon`<A>`](#logon-request) message controls whether messages from the client may be reordered before they are processed by the Matching Engine.

| Mode            | Description                                                                                |
|-----------------|--------------------------------------------------------------------------------------------|
| `UNORDERED(1)`  | Messages from the client are allowed to be sent to the matching engine in any order.       |
| `SEQUENTIAL(2)` | Messages from the client are always sent to the matching engine in `MsgSeqNum (34)` order. |

In all modes, the client's `MsgSeqNum (34)` must increase monotonically, with each subsequent message having a sequence number that is exactly 1 greater than the previous message.

> [!TIP]
> `UNORDERED(1)` should offer better performance when there are multiple messages in flight from the client to the server.

<a id="responsemode"></a>

### Response Mode

By default, all concurrent order entry sessions receive all of the account's
successful [ExecutionReport`<8>`](#executionreport) and [ListStatus`<N>`](#liststatus) messages,
including those in response to orders placed from other FIX sessions and via non-FIX APIs.

Use the `ResponseMode (25036)` field in the initial [Logon`<A>`](#logon-request) message
to change this behavior.

- `EVERYTHING(1)`: The default mode.
- `ONLY_ACKS(2)`: Receive only ACK messages whether operation succeeded or failed. Disables ExecutionReport push.

<a id="timingsecurity"></a>

### Timing Security

* All requests require a `SendingTime(52)` field which should be the current timestamp.
* An additional optional field, `RecvWindow(25000)`, specifies for how long the request stays valid in milliseconds.
  * `RecvWindow(25000)` supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.
  * If `RecvWindow(25000)` is not specified, it defaults to 5000 milliseconds only for the Logon`<A>` request. For other requests if unset, the RecvWindow check is not executed.
  * Maximum `RecvWindow(25000)` is 60000 milliseconds.
* Request processing logic is as follows:

```javascript
serverTime = getCurrentTime()
if (SendingTime < (serverTime + 1 second) && (serverTime - SendingTime) <= RecvWindow) {
  // begin processing request
  serverTime = getCurrentTime()
  if (serverTime - SendingTime) <= RecvWindow {
    // forward request to Matching Engine
  } else {
    // reject request
  }
  // finish processing request
} else {
  // reject request
}
```

<a id="signaturecomputation"></a>

### How to sign Logon `<A>` request

The [Logon`<A>`](#logon-main) message authenticates your connection to the FIX API.
This must be the first message sent by the client.

* The `Username (553)` field is required to contain the API key.
* The `RawData (96)` field is required to contain a valid signature made with the API key.

The signature payload is a text string constructed by concatenating the values of the following fields in this exact order,
separated by the SOH character:

1. `MsgType (35)`
2. `SenderCompId (49)`
3. `TargetCompId (56)`
4. `MsgSeqNum (34)`
5. `SendingTime (52)`


Sign the payload using your private key.
Encode the signature with **base64**.
The resulting text string is the value of the `RawData (96)` field.

Here is a sample Python code implementing the signature algorithm:

````python
import base64

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import load_pem_private_key

def logon_raw_data(private_key: Ed25519PrivateKey,
                   sender_comp_id: str,
                   target_comp_id: str,
                   msg_seq_num: str,
                   sending_time: str):
    """
    Computes the value of RawData (96) field in Logon<A> message.
    """
    payload = chr(1).join([
        'A',
        sender_comp_id,
        target_comp_id,
        msg_seq_num,
        sending_time,
    ])
    signature = private_key.sign(payload.encode('ASCII'))
    return base64.b64encode(signature).decode('ASCII')


with open('private_key.pem', 'rb') as f:
    private_key = load_pem_private_key(data=f.read(),
                                       password=None)

raw_data = logon_raw_data(private_key,
                          sender_comp_id='5JQmUOsm',
                          target_comp_id='SPOT',
                          msg_seq_num='1',
                          sending_time='20240612-08:52:21.613')
````

The values presented below can be used to validate the correctness of the signature computation implementation:

| Field             | Value                   |
|-------------------|-------------------------|
| MsgType (35)      | `A`                     |
| SenderCompID (49) | `EXAMPLE`               |
| TargetCompID (56) | `SPOT`                  |
| MsgSeqNum (34)    | `1`                     |
| SendingTime (52)  | `20240627-11:17:25.223` |

The Ed25519 private key used in the example computation is shown below:

> [!CAUTION]
> The following secret key is provided solely for illustrative purposes. Do not use this key in any real-world application as it is not secure and may compromise your cryptographic implementation. Always generate your own unique and secure keys for actual use.

```
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIIJEYWtGBrhACmb9Dvy+qa8WEf0lQOl1s4CLIAB9m89u
-----END PRIVATE KEY-----
```

Computed signature:
```
4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==
```

Resulting Logon `<A>` message:
```
8=FIX.4.4|9=247|35=A|34=1|49=EXAMPLE|52=20240627-11:17:25.223|56=SPOT|95=88|96=4MHXelVVcpkdwuLbl6n73HQUXUf1dse2PCgT1DYqW9w8AVZ1RACFGM+5UdlGPrQHrgtS3CvsRURC1oj73j8gCA==|98=0|108=30|141=Y|553=sBRXrJx2DsOraMXOaUovEhgVRcjOvCtQwnWj8VxkOh1xqboS02SPGfKi2h8spZJb|25035=2|10=227|
```
filename:    binance-spot-api-docs-master/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## 全市场滚动窗口统计

全市场symbols的滚动窗口ticker统计，计算于多个窗口。<br/>

注意：有变动的ticker才会推送。

**Stream 名称:** !ticker_\<window-size\>@arr

**Window Size:** 1h, 4h, 1d

**更新速度:** 1000ms

> **Payload:**
```javascript
[
    {
        // 同 <symbol>@ticker_<window-size> payload,
        // 间隔内更新的每个symbol。
    }
]
```

<a id="how-to-maintain-orderbook"></a>
filename:    binance-spot-api-docs-master/web-socket-streams_CN.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## General endpoints

### Test connectivity
```
GET /api/v3/ping
```
Test connectivity to the Rest API.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{}
```

### Check server time
```
GET /api/v3/time
```
Test connectivity to the Rest API and get the current server time.

**Weight:**
1

**Parameters:**
NONE

**Data Source:**
Memory

**Response:**
```javascript
{
    "serverTime": 1499827319559
}
```

<a id="exchangeInfo"></a>

### Exchange information
```
GET /api/v3/exchangeInfo
```
Current exchange trading rules and symbol information

**Weight:**
20

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
symbol |STRING| No| Example: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"
symbols |ARRAY OF STRING|No| Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?symbols=%5B%22BNBBTC%22,%22BTCUSDT%22%5D" <br/> or <br/> curl -g -X  GET 'https://api.binance.com/api/v3/exchangeInfo?symbols=["BTCUSDT","BNBBTC"]'
permissions |ENUM|No|Examples: curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=SPOT" <br/> or <br/> curl -X GET "https://api.binance.com/api/v3/exchangeInfo?permissions=%5B%22MARGIN%22%2C%22LEVERAGED%22%5D" <br/> or <br/> curl -g -X GET 'https://api.binance.com/api/v3/exchangeInfo?permissions=["MARGIN","LEVERAGED"]' |
showPermissionSets|BOOLEAN|No|Controls whether the content of the `permissionSets` field is populated or not. Defaults to `true`
symbolStatus|ENUM|No|Filters for symbols that have this `tradingStatus`. Valid values: `TRADING`, `HALT`, `BREAK` <br> Cannot be used in combination with `symbols` or `symbol`.|

**Notes:**
* If the value provided to `symbol` or `symbols` do not exist, the endpoint will throw an error saying the symbol is invalid.
* All parameters are optional.
* `permissions` can support single or multiple values (e.g. `SPOT`, `["MARGIN","LEVERAGED"]`). This cannot be used in combination with `symbol` or `symbols`.
* If `permissions` parameter not provided, all symbols that have either `SPOT`, `MARGIN`, or `LEVERAGED` permission will be exposed.
  * To display symbols with any permission you need to specify them explicitly in `permissions`: (e.g. `["SPOT","MARGIN",...]`.). See [Account and Symbol Permissions](enums.md#account-and-symbol-permissions) for the full list.

<a id="examples-of-symbol-permissions-interpretation-from-the-response"></a>

**Examples of Symbol Permissions Interpretation from the Response:**

* `[["A","B"]]` means you may place an order if your account has either permission "A" **or** permission "B".
* `[["A"],["B"]]` means you can place an order if your account has permission "A" **and** permission "B".
* `[["A"],["B","C"]]` means you can place an order if your account has permission "A" **and** permission "B" or permission "C". (Inclusive or is applied here, not exclusive or, so your account may have both permission "B" and permission "C".)

**Data Source:**
Memory

**Response:**
```javascript
{
    "timezone": "UTC",
    "serverTime": 1565246363776,
    "rateLimits": [
        {
            // These are defined in the `ENUM definitions` section under `Rate Limiters (rateLimitType)`.
            // All limits are optional
        }
    ],
    "exchangeFilters": [
        // These are the defined filters in the `Filters` section.
        // All filters are optional.
    ],
    "symbols": [
        {
            "symbol": "ETHBTC",
            "status": "TRADING",
            "baseAsset": "ETH",
            "baseAssetPrecision": 8,
            "quoteAsset": "BTC",
            "quotePrecision": 8,     // will be removed in future api versions (v4+)
            "quoteAssetPrecision": 8,
            "baseCommissionPrecision": 8,
            "quoteCommissionPrecision": 8,
            "orderTypes": [
                "LIMIT",
                "LIMIT_MAKER",
                "MARKET",
                "STOP_LOSS",
                "STOP_LOSS_LIMIT",
                "TAKE_PROFIT",
                "TAKE_PROFIT_LIMIT"
            ],
            "icebergAllowed": true,
            "ocoAllowed": true,
            "otoAllowed": true,
            "opoAllowed": true,
            "quoteOrderQtyMarketAllowed": true,
            "allowTrailingStop": false,
            "cancelReplaceAllowed": false,
            "amendAllowed": false,
            "pegInstructionsAllowed": true,
            "isSpotTradingAllowed": true,
            "isMarginTradingAllowed": true,
            "filters": [
                // These are defined in the Filters section.
                // All filters are optional
            ],
            "permissions": [],
            "permissionSets": [["SPOT", "MARGIN"]],
            "defaultSelfTradePreventionMode": "NONE",
            "allowedSelfTradePreventionModes": ["NONE"]
        }
    ],
    // Optional field. Present only when SOR is available.
    // https://github.com/binance/binance-spot-api-docs/blob/master/faqs/sor_faq.md
    "sors": [
        {
            "baseAsset": "BTC",
            "symbols": ["BTCUSDT", "BTCUSDC"]
        }
    ]
}
```

### Query Execution Rules

```
GET /api/v3/executionRules
```

**Weight**

Parameter | Weight|
---        | ---
`symbol`  | 2
`symbols` | 2 for each `symbol`, capped at a max of 40|
`symbolStatus` |40|
None            |40|

**Parameters:**

Name | Type | Mandatory | Description
------------ | ------------ | ------------ | ------------
`symbol`   | STRING| No      | Query for specified symbol
`symbols`  | STRING | No     | Query for multiple symbols
`symbolStatus` |ENUM| Query for all symbols with the specified status. Supported values: `TRADING`, `HALT`, `BREAK`


**Note:** No combination of multiple parameters is allowed.

**Data Source:** Memory

**Response:**

```javascript
{
    "symbolRules": [
        {
            "symbol": "BAZUSD",
            "rules": [
                {
                    "ruleType": "PRICE_RANGE",
                    "bidLimitMultUp": "1.0001",
                    "bidLimitMultDown": "0.9999",
                    "askLimitMultUp": "1.0001",
                    "askLimitMultDown": "0.9999"
                }
            ]
        }
    ]
}
```
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

====================================================================================================
QUERY: What does recvWindow mean?


In [23]:
len(my_chunks_sections)

367

In [24]:
preview_results(text_search("What does recvWindow mean?"))

Result #1
title:
section:     ## In the API response, there's a field called `workingFloor`. What does that field mean?

This is a term used to determine where the order's last activity occurred (filling, expiring, or being placed as new, etc.).

If the `workingFloor` is `SOR`, this means your order interacted with other eligible order books in the SOR configuration.

If the `workingFloor` is `EXCHANGE`, this means your order interacted on the order book that you sent that order to.
filename:    binance-spot-api-docs-master/faqs/sor_faq.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## What does the Price Range Execution Rule do?

This rule ensures that trades may only be executed at prices within and equal to a price range around a reference price.
filename:    binance-spot-api-docs-master/faqs/price_range_execution_rules.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## In the API response, `fills` contain fields `matchType` and `allocId`. What do they mean?

`matchType` field indicates a non-standard order fill.

When your order is filled by SOR, you will see `matchType: ONE_PARTY_TRADE_REPORT`, indicating that you did not trade directly on the exchange (`tradeId: -1`). Instead your order is filled by _allocations_.

`allocId` field identifies the allocation so that you can query it later.
filename:    binance-spot-api-docs-master/faqs/sor_faq.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## Which time zone does `"interval":"DAY"` use?

UTC
filename:    binance-spot-api-docs-master/faqs/order_count_decrement.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## What happens if my amend request does not succeed?

If the request fails for any reason (e.g. fails the filters, permissions, account restrictions, etc), then the order amend request is rejected and the order remains unchanged.
filename:    binance-spot-api-docs-master/faqs/order_amend_keep_priority.md
chunk:
--------------------------------------------------------------------------------

In [25]:
preview_results(vector_search("How do I authenticate a private endpoint?"))

Result #1
title:
section:     ## 如何正确在本地维护一个order book副本

1. 打开与 `wss://stream.binance.com:9443/ws/bnbbtc@depth` 的 WebSocket 连接。
2. 开始缓存收到的event。请记录您收到的第一个event的 `U`值。
3. 访问 `https://api.binance.com/api/v3/depth?symbol=BNBBTC&limit=5000` 获取深度快照。
4. 如果快照中的 `lastUpdateId` 小于等于步骤 2 中的 `U` 值，请返回步骤 3。
5. 在收到的event中，丢弃快照中 `u` <= `lastUpdateId` 的所有event。现在第一个event的 `lastUpdateId` 应该在 `[U;u]` 范围以内。
6. 将本地order book设置为快照。它的更新ID 为 `lastUpdateId`。
7. 更新所有缓存的event，以及后续的所有event。

要将一个event应用于您的本地order book，请遵循以下更新过程：
1. 判断是否需要处理event：
    * 如果event的最后一次更新ID（`u`）小于本地order book的更新ID，忽略该event。
    * 如果event的首次更新ID（`U`）大于本地order book的更新ID加1，说明你错过了一些events。<br>请丢弃您的本地order book并从头开始重新同步。
    * 通常，下一event的`U`等于上一event的`u + 1`。
1. 对买价（`b`）和卖价（`a`）中的每个价位，设置order book中的新数量：
    * 如果该价位在order book中不存在，则插入该价位及其数量。
    * 如果数量为零，则从order book中删除此价位。
1. 将order book的更新ID设置为已处理event的最后一次更新ID（`u`）。

> [!NOTE]
> 由于从 API 检索的深度快照对价位的数量有限制（每侧最多 5000 个），因此除非它们发生变化，否则您将无法了解初始快照之外的价位数量。<br>
> 因此，在使用这些级别的信息时要小心，因为它们可能无法反映订单簿的完整视图。<br>
> 但是，对于大多数场景，可以每侧看到 5000 个价位就足以了解市场并进行有效交易。
filename:    binance-spot-api-docs-master/web-socket-streams_CN.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## Limits

### Message Limits

* Each connection has a limit on **how many messages can be sent to the exchange**.
* The message limit **does not count the messages sent in response to the client**.
* Breaching the message limit results in immediate [Logout `<5>`](#logout) and disconnection.
* To understand current limits and usage, please send a [LimitQuery`<XLQ>`](#limitquery) message.
  A [LimitResponse`<XLR>`](#limitresponse) message will be sent in response, containing information about Order Rate
  Limits and Message Limits.
* FIX Order entry sessions have a limit of 10,000 messages every 10 seconds.
* FIX Drop Copy sessions have a limit of 60 messages every 60 seconds.
* FIX Market Data sessions have a limit of 2000 messages every 60 seconds.

<a id="connection-limits"></a>

### Connection Limits

* Each Account has a limit on how many TCP connections can be established at the same time.
* The limit is reduced when the TCP connection is closed. If the reduction of connections is not immediate, please wait up to twice the value of `HeartBtInt (108)` for the change to take effect.
  For example, if the current value of `HeartBtInt` is 5, please wait up to 10 seconds.
* Upon breaching the limit a [Reject `<3>`](#reject) will be sent containing information about the connection limit
  breach and the current limit.
* FIX Order Entry limits:
   * 15 connection attempts within 30 seconds
   * Maximum of 10 concurrent TCP connections per account
* FIX Drop Copy limits:
    * 15 connection attempts within 30 seconds
    * Maximum of 10 concurrent TCP connections per account
* FIX Market Data limits
  * 300 connection attempts within 300 seconds
  * Maximum of 100 concurrent TCP connections per account
  * A single connection can listen to a maximum of 1000 streams.

### Unfilled Order Count

* To understand how many orders you have placed within a certain time interval, please send a [LimitQuery`<XLQ>`](#limitquery) message.
  A [LimitResponse`<XLR>`](#limitresponse) message will be sent in response, containing information about Unfilled Order Count and Message Limits.
* **Please note that if your orders are consistently filled by trades, you can continuously place orders on the API**. For more information, please see [Spot Unfilled Order Count Rules](../faqs/order_count_decrement.md).
* If you exceed the unfilled order count your message will be rejected, and information will be transferred back to you in a reject message specific to that endpoint.
* **The number of unfilled orders is tracked for each account.**
filename:    binance-spot-api-docs-master/testnet/fix-api.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## LIMITS

### General Info on Limits
* The following `intervalLetter` values for headers:
    * SECOND => S
    * MINUTE => M
    * HOUR => H
    * DAY => D
* `intervalNum` describes the amount of the interval. For example, `intervalNum` 5 with `intervalLetter` M means "Every 5 minutes".
* The `/api/v3/exchangeInfo` `rateLimits` array contains objects related to the exchange's `RAW_REQUESTS`, `REQUEST_WEIGHT`, and `ORDERS` rate limits. These are further defined in the `ENUM definitions` section under `Rate limiters (rateLimitType)`.
* Requests fail with HTTP status code 429 when you exceed the request rate limit.

### IP Limits
* Every request will contain `X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter)` in the response headers which has the current used weight for the IP for all request rate limiters defined.
* Each route has a `weight` which determines for the number of requests each endpoint counts for. Heavier endpoints and endpoints that do operations on multiple symbols will have a heavier `weight`.
* When a 429 is received, it's your obligation as an API to back off and not spam the API.
* **Repeatedly violating rate limits and/or failing to back off after receiving 429s will result in an automated IP ban (HTTP status 418).**
* IP bans are tracked and **scale in duration** for repeat offenders, **from 2 minutes to 3 days**.
* A `Retry-After` header is sent with a 418 or 429 responses and will give the **number of seconds** required to wait, in the case of a 429, to prevent a ban, or, in the case of a 418, until the ban is over.
* **The limits on the API are based on the IPs, not the API keys.**

### Unfilled Order Count
* Every successful order response will contain a `X-MBX-ORDER-COUNT-(intervalNum)(intervalLetter)` header indicating how many orders you have placed for that interval. <br></br> To monitor this, refer to [`GET api/v3/rateLimit/order`](#query-unfilled-order-count).
* Rejected/unsuccessful orders are not guaranteed to have `X-MBX-ORDER-COUNT-**` headers in the response.
* If you have exceeded this, you will receive a 429 error with the `Retry-After` header.
* **Please note that if your orders are consistently filled by trades, you can continuously place orders on the API**. For more information, please see [Spot Unfilled Order Count Rules](../faqs/order_count_decrement.md).
* **The number of unfilled orders is tracked for each account.**
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## General Information on Endpoints

* For `GET` endpoints, parameters must be sent as a `query string`.
* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a
  `query string` or in the `request body` with content type
  `application/x-www-form-urlencoded`. You may mix parameters between both the
  `query string` and `request body` if you wish to do so.
* Parameters may be sent in any order.
* If a parameter sent in both the `query string` and `request body`, the
  `query string` parameter will be used.
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #5
title:
section:     ## Error Codes

* Any endpoint can return an ERROR

Sample Payload below:
```javascript
{
    "code": -1121,
    "msg": "Invalid symbol."
}
```
* Specific error codes and messages are defined in [Errors Codes](./errors.md).
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

In [26]:
preview_results(hybrid_search("Why am I getting timestamp error?"))

Result #1
title:
section:     ## Error Codes

* Any endpoint can return an ERROR

Sample Payload below:
```javascript
{
    "code": -1121,
    "msg": "Invalid symbol."
}
```
* Specific error codes and messages are defined in [Errors Codes](./errors.md).
filename:    binance-spot-api-docs-master/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #2
title:
section:     ## REST API

- `POST /api/v3/userDataStream`
- `PUT /api/v3/userDataStream`
- `DELETE /api/v3/userDataStream`
filename:    binance-spot-api-docs-master/CHANGELOG_CN.md
chunk:
--------------------------------------------------------------------------------

Result #3
title:
section:     ## Error Codes

* Any endpoint can return an ERROR

Sample Payload below:
```javascript
{
    "code": -1121,
    "msg": "Invalid symbol."
}
```
* Specific error codes and messages are defined in [Errors Codes](./errors.md).
filename:    binance-spot-api-docs-master/testnet/rest-api.md
chunk:
--------------------------------------------------------------------------------

Result #4
title:
section:     ## WebSocket API

- `userDataStream.start`
- `userDataStream.ping`
- `userDataStream.stop`

---

### 2025-12-18

* [FIX SBE 文档](fix-api_CN.md#fix-sbe) 已更新。
* 澄清了用户数据流文档中关于 [`eventStreamTerminated`](user-data-stream_CN.md#event-stream-terminated) 的说明
* 资产 `这是测试币` 和 `456` 以及交易对 `这是测试币456` 已被添加到 [现货测试网](http://testnet.binance.vision) 以供用户测试含有 Unicode 交易对的端点/方法。 预知详情，请参考 [现货测试网的相关更新日志](https://developers.binance.com/docs/binance-spot-api-docs/testnet)。

---

### 2025-12-17

#### 时效性通知

* **以下有关于REST API变更将在 2026-01-15 07:OO UTC 发生:** <br> 调用需要签名的接口时，请在计算签名之前对 payload 进行百分比编码（percent-encode）。不符合此顺序的请求将被拒绝，并返回错误代码 [`-1022 签名不正确`](errors_CN.md#-1022-invalid_signature)。请检查并相应地更新您代码中的签名逻辑部分。这项功能现已在 [SPOT Testnet](http://testnet.binance.vision) 上启用。

#### REST API

* 更新了 REST API 文档中有关于 [签名请求示例](rest-api_CN.md#hmac-keys) 的部分。

#### WebSocket API

* 更新了 WebSocket API 文档中有关于 [签名请求示例](web-socket-api_CN.md#hmac) 的部分。

---

### 2025-12-15

**关于 UTF-8 编码的说明：**

* 在 [FIX API](fix-api_CN.md)、[REST API](rest-api_CN.md) 和 [WebSocket API](web-socket-api_CN.md) 中，如果您的请求包含非 ASCII 字符的交易对名称，那么响应中可能包含以 UTF-8 编码的非 ASCII 字符。
* 在 REST 和 WebSocket API 中，即使请求本身不包含非 ASCII 字符，某些端点/方法也可能返回包含以 UTF-8 编码的非 ASCII 字符的资产和/或交易对名称。
* 在 [WebSocket 数据流](web-socket-streams_CN.md) 中，如果您的请求包含非 ASCII 字符的交易对名称，那么数据流事件中可能包含以 UTF-8 编码的非 ASCII 字符。
* 在 WebSocket 数据流中，[全市场所有 Symbol 的精简 Ticker](web-socket-streams_CN.md#all-markets-mini-ticker) 和 [全市场滚动窗口统计](web-socket-streams_CN.md#all-market-rolling-window-ticker) 事件可能包含以 UTF-8 编码的非 ASCII 字符。
* 在 [SBE 市场数据流](sbe-market-data-streams_CN.md) 中，如果您的请求包含包含非 ASCII 字符的交易对名称，那么数据流事件中可能包含以 UTF-8 编码的非 ASCII 字符。
* 如果您持有或交易任何名称包含非 ASCII 字符的资产或交易对，那么 [WebSocket 账户接口](user-data-stream_CN.md) 中可能包含以 UTF-8 编码的非 ASCII 字符。
* 为了与币安 API 完全兼容，请务必确保您的代码能够处理 UTF-8 编码的字符串。

---

### 2025-12-09

* [FIX SBE Schema](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot-fixsbe-1_0.xml) 已更新，会在 `MarketDataSnapshot` 中使用 `smallGroupSize16Encoding`。并在增量单个交易对订单簿数据流/深度数据流的 `MDEntrySize` 的字段中使用 `presence="optional"`。
* 更新了关于 [FIX 与 FIX SBE](fix-api.md#fix-vs-fix-sbe-schema) 的文档说明
* 在 REST 和 WebSocket API 文档中新增说明：**请避免在请求中使用 SQL 关键字**，因为这可能会触发 Web 应用防火墙（WAF）规则导致安全拦截。详情请参见 https://www.binance.com/zh-CN/support/faq/detail/360004492232 。

---

### 2025-12-02

**注意： 本节中的变更将逐步推出，预计大约需要两周时间完成。**

#### 常规更改

* 参数 `symbol` 和 `symbols` 现在支持以 UTF-8 编码的 Unicode 值。
* 根据 [2025-11-14](#2025-11-14) 的公告，所有与 `!ticker@arr` 相关的内容已经在文档被移除。
  * 该功能将在未来弃用公告发布前继续可用。
  * 请改用 `<symbol>@ticker` 或 `!miniTicker@arr`。

#### FIX API

* 现在 FIX 消息中可以接受以 UTF-8 编码的 Unicode 值。仅允许以下标签使用：
  * `Currency (15)`
  * `MiscFeeCurr (138)`
  * `Symbol (55)`
  * `SecondarySymbol (25019)`
  * `CounterSymbol (25028)`
  * `SecurityDesc (107)`
* 当 Unicode 出现在非上述标签的值中时，FIX API 会在拒绝消息 `<3>` 中返回 `RefTagID (371)` 标签，指明具体哪个标签不允许包含 Unicode。
* NewOrderList `<E>` 可以接受没有 `TriggerPrice (1102)` 的 `TriggerPriceDirection (1109)`。

#### WebSocket 数据流

* WebSocket 市场数据流支持 URL 编码的 URL。
<br>
<br>

**注意：以下变更预计于 2025-12-18 07:00 UTC 左右生效**：
* [ICEBERG_PARTS](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/filters#iceberg_parts) 将对所有交易对提升至 25。
* [FIX SBE 支持](fix-api_CN.md) 将上线。
* [一个订单支付另一个订单（OPO）](https://github.com/binance/binance-spot-api-docs/blob/master/faqs/opo_CN.md) 将在所有交易对上线。
  * `opoAllowed` 将开始出现在 `Exchange Information` 请求中，指示每个交易对是否支持一个订单支付另一个订单（OPO）。
    * REST API: `GET /api/v3/exchangeInfo`
    * WebSocket API: `exchangeInfo`
  * OPO 新请求：
    * REST API：
      * `POST /api/v3/orderList/opo`
      * `POST /api/v3/orderList/opoco`
    * WebSocket API：
      * `orderList.place.opo`
      * `orderList.place.opoco`
    * FIX API：
      * NewOrderList `<E>` 新增字段 `OPO (25046)`。请更新至最新 QuickFIX 模式以支持 OPO。
* 新增 STP 模式 [`TRANSFER`](./faqs/stp_faq_CN.md)。STP `TRANSFER` 启用的具体日期尚未确定。
* **SBE：新增 schema 3:2 版本 ([spot_3_2.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_2.xml))。**
  * 当前 schema 3:1 ([spot_3_1.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_1.xml)) 已被弃用，将根据我们的 schema 弃用政策在 6 个月后停用。
  * 3:2 版本变更：
    * 为 `selfTradePreventionMode` 和 `allowedSelfTradePreventionModes` 新增枚举值 `TRANSFER`。
    * 所有低于 3:1 的 schema 无法返回包含 STP 模式 `TRANSFER` 的响应（例如 Exchange Information、下单、撤单或订单状态查询）。<br>当响应无法用请求的 schema 表示时，将返回错误。
* FIX API 变更：
    * `LastFragment (893)` 被弃用。
      * 这意味着 MarketIncrementalRefresh `<X>` 消息将不再分片，可能包含超过 10,000 条目。
      * 文档已更新以反映此变更。
    * ListStatus `<N>` 将不再发送可选的 `symbol` 字段。
      * 适用于 FIX 订单接入和 FIX Drop Copy。
      * 文档已更新以反映此变更。

---

### 2025-11-14

* 全市场所有交易对的完整Ticker（`!ticker@arr`）已被弃用；这意味着该接口将在后续从文档和系统中移除，具体时间另行通知。
* 请改用 [`<symbol>@ticker`](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/web-socket-streams#twentyfourhourticker) 或 [`!miniTicker@arr`](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/web-socket-streams#all-markets-mini-ticker)。

---

### 2025-11-12

* 关于[如何正确管理本地订单簿](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/web-socket-streams#how-to-maintain-orderbook)的步骤已被修正。

---

### 2025-11-11

#### SBE 市场数据流

* **从 2025 年 11 月 26 日 07:00 UTC 起，`<symbol>@depth` 和 `<symbol>@depth20` 数据流的更新速度将变为 50 毫秒**。
  * 此变更将自动部署到 SBE 市场数据的所有用户端，因此客户无需进行任何操作。
  * 每秒可接收的总数据量将增加（最高可达 2 倍速）。
  * [SPOT 测试网](https://testnet.binance.vision/) 将会从 **2025 年 11 月 11 日 07:00 UTC** 起应用这些变更。
  * [SBE 市场数据流](sbe-market-data-streams_CN.md) 已更新以反映这些变更。

---

### 2025-11-10

* 除了更新日志之外，所有文档中的“最近更新”日期将被移除。
* 今后，更新日志将作为所有文档变更时间的唯一参考来源。

---

### 2025-10-28

**注意：以下变更将于 2025 年 10 月 28 日 04:00 (UTC) 推出，可能需要几个小时才能完成部署。**

* 可选参数 `symbolStatus` 已添加到以下端点：
    * **REST API**
      * `GET /api/v3/depth`
      * `GET /api/v3/ticker/price`
      * `GET /api/v3/ticker/bookTicker`
      * `GET /api/v3/ticker/24hr`
      * `GET /api/v3/ticker/tradingDay`
      * `GET /api/v3/ticker`
    * **WebSocket API**
      * `depth`
      * `ticker.price`
      * `ticker.book`
      * `ticker.24hr`
      * `ticker.tradingDay`
      * `ticker`
* 当提供参数 `symbolStatus=<STATUS>` 时，只有交易状态与指定的 `STATUS` 相匹配的交易对才会包含在响应中：
    * 如果使用 `symbol=<SYMBOL>` 参数指定单个交易对，但是这个交易对的状态与指定的 `STATUS` 不匹配时，端点将返回错误代码 [`-1220 SYMBOL_DOES_NOT_MATCH_STATUS`](./errors_CN.md#-1220-symbol_does_not_match_status)。
    * 如果使用 `symbols=[...]` 参数指定了多个交易对，那么响应将是一个数组。该数组中将不会包括交易状态与 `STATUS` 不匹配的交易对。当 symbols 参数中所指定的交易对中没有任何一个交易对的状态与 `STATUS` 相匹配时，响应将为一个空数组。
    * 对于 `symbol` 和 `symbols` 参数为可选参数的端点，省略这些参数将被视为在 `symbols=[...]` 参数中指定了所有交易对。有关 `symbolStatus=<STATUS>` 的行为，请参阅上一行。

---

### 2025-10-24

#### SBE

* SBE：schema 3:1（[spot_3_1.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_1.xml)）已更新，支持保证金交易的[listenToken 订阅方法](https://developers.binance.com/docs/zh-CN/margin_trading/trade-data-stream/Listen-Token-Websocket-API)。

#### REST 和 WebSocket API

根据 [2025-04-07](#2025-04-07) 的公告，所有关于在 `wss://stream.binance.com` 上使用 `listenKey` 的文档已被移除。请参阅以下请求和方法列表以获取详细信息。
该功能将在未来发布停用公告之前继续可用。

**特此提醒您： 您应该通过订阅 [在 WebSocket API 内的账户信息流](https://developers.binance.com/docs/zh-CN/binance-spot-api-docs/websocket-api/user-data-stream-requests) 来获得用户账户更新。这样可以提供更好的性能（更低的延迟）。**

请参阅下方请求和方法列表来了解更多详情。

这些功能将持续可用，直至另行发布停用公告。

* REST API
  * `POST /api/v3/userDataStream`
  * `PUT /api/v3/userDataStream`
  * `DELETE /api/v3/userDataStream`

* WebSocket API
  * `userDataStream.start`
  * `userDataStream.ping`
  * `userDataStream.stop`

---

### 2025-10-21

REST 和 WebSocket API：

* 注意：根据我们的 SBE 政策，[在被废止 6 个月后](faqs/sbe_faq_CN.md#sbe-schema)， SBE 2:1 模式将于 2025 年 10 月 24 日被禁用。
* [面向生产的 SBE 生命周期](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/sbe_schema_lifecycle_prod.json) 已基于本次更改进行了更新。

---

### 2025-10-08

* 更新了用于 FIX 市场数据的 [QuickFIX Schema](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-md.xml)：
  * 更新了 `RecvWindow(25000)`，以便对在 [2025-08-12](#2025-08-12) 公布的微秒级进行支持。
  * 更新了 [`InstrumentList`](fix-api_CN.md#instrumentlist) 消息：
    * 新增字段：`StartPriceRange`、`EndPriceRange`。
    * 以下字段改为可选：`MinTradeVol`、`MaxTradeVol`、`MinQtyIncrement`、`MarketMinTradeVol`、`MarketMaxTradeVol`、`MarketMinQtyIncrement`、`MinPriceIncrement`。
  * **InstrumentList `<y>` 的变更属于破坏性变更，预计将于 2025-10-23 07:00 UTC 左右发布。请在此之前更新到新的模式。**
  * 在[SPOT 测试网](https://testnet.binance.vision/) 上已经启用了这个重大更改。

---

### 2025-09-29

**注意：以下变更将于 2025 年 9 月 29 日 10:00 (UTC) 推出，可能需要几个小时才能完成部署。**

* 新增一个端点，用于检索与指定交易品种的账户相关的过滤器列表。这是唯一一个目前会显示账户是否应用了 `MAX_ASSET` 过滤器的端点。
  * REST API： [`GET /api/v3/myFilters`](rest-api_CN.md#myFilters)
  * WebSocket API： [`myFilters`](web-socket-api_CN.md#myFilters)
* 对 **SBE: schema 3:1 ([spot_3_1.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_1.xml))** 中的部分注释进行了添加、修改和删除。虽然 `3:1` 用户无需更新到此版本的模式，但我们建议您进行更新以保持一致性。
* 新增了有关过滤器 [`MAX_ASSET`](filters_CN.md#max_asset) 的文档。

---

### 2025-09-18

* 更新了文档中有关 `recvWindow` 的部分， 用以体现在 [2025-08-12](#2025-08-12) 发表的微秒级支持。
  * REST API: [时间同步安全](rest-api_CN.md#timingsecurity)
  * WebSocket API: [时间同步安全](web-socket-api_CN.md#timingsecurity)

---

### 2025-09-12

* 更新了 FIX 订单接入 API 的 [QuickFix 模式](https://github.com/binance/binance-spot-api-docs/blob/master/fix/schemas/spot-fix-oe.xml)，用以支持挂钩订单。
* 在 FIX API 文档中， 对以下部分的 `RecvWindow` 进行了更新：
  * [消息组件](fix-api_CN.md#header)
  * [时间同步安全](fix-api_CN.md#timingsecurity)

---

### 2025-08-28

* 更新了 “简单二进制编码（SBE）常见问题” 文档中 [关于对旧版本的支持](faqs/sbe_faq_CN.md#regarding-legacy-support) 部分，增加了关于模式兼容性的更多细节，并解释了 `NonRepresentable` 和 `NonRepresentableMessage` 的用法。

---

### 2025-08-26

* 更新了 [REST API](rest-api_CN.md#request-security) 和 [WebSocket API](web-socket-api_CN.md#request-security) 文档的 “请求鉴权类型” 部分，不过相关的功能没有改动。

---

### 2025-08-25

* **SBE: 模式 3:1 ([spot_3_1.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_1.xml))**将于**2025-08-25 05:00 UTC** 进行更新。
  * 以下字段已被重命名，用于解决通过 [SbeTool](faqs/sbe_faq_CN.md#generate-sbe-decoders) 代码生成器所生成的 Java 代码被发现无法进行编译的问题。
    * 虽然只有受此问题影响的用户才需要更新模式文档，但我们建议所有用户都升级到最新版本以保持一致性。
    * 消息 `MaxAssetFilter`
      * 字段 `limitExponent` 重命名为 `qtyExponent`
      * 字段 `limit` 重命名为 `maxQty`

---

### 2025-08-19

* `userDataStream.subscribe` 在响应中返回 `subscriptionId`。<br> 这在 [previous](#2025-08-12) 变更日志条目中被遗漏了

---

### 2025-08-12

**通知:** 本节中的更改将逐步推出,需要大约两周时间才能完成部署。

#### 常规更改

* 新的错误代码 `-1120` 和 `1211`。有关详情，请参阅 [错误代码汇总](errors_CN.md)。
* 以下请求包含一个名为 `specialCommission` 的新结构。请参阅 [佣金率](faqs/commission_faq_CN.md)。
  * REST API
    * `GET /api/v3/account/commission`
    * `POST /api/v3/order/test` 并设置 `computeCommissionRates=true`
    * `POST /api/v3/sor/order/test` 并设置 `computeCommissionRates=true`
  * WebSocket API
    * `account.commission`
    * `order.test` 并设置 `computeCommissionRates=true`
    * `sor.order.test` 并设置 `computeCommissionRates=true`
* **SBE: 新模式 3:1 ([spot_3_1.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_1.xml)) 将可以使用。**
  * 现行模式 3:0 ([spot_3_0.xml](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/spot_3_0.xml)) 将会被废止并根据我们的废止政策，在6个月内停止使用。
  * 模式 3:1 中的更改：
    * `ExchangeInfoResponse`：增加新字段 `pegInstructionsAllowed`
    * `ExecutionReportEvent`：增加新字段 `pricePeg`，`pricePegOffsetLevel` 和 `peggedPrice`
    * `UserDataStreamSubscribeResponse`：新字段 `subscriptionId`
    * 所有的用户数据流事件都增加了新字段 `subscriptionId`。
    * 对于 `WebSocketSessionLogonResponse`，`WebSocketSessionStatusResponse` 和 `WebSocketSessionLogoutResponse`，字段 `apiKey` 被改名为 `loggedOnApiKey`
    * `OrderTestWithCommissionsResponse`：增加2个新字段 `specialCommissionForOrderMaker` 和 `specialCommissionForOrderTaker`
    * `AccountCommissionResponse`：增加4个新字段 `specialCommissionMaker`，`specialCommissionTaker`，`specialCommissionBuyer` 和 `specialCommissionSeller`
    * 支持 `EXCHANGE_MAX_NUM_ORDER_LISTS`，`MAX_NUM_ORDER_LISTS` 和 `MAX_NUM_ORDER_AMENDS` 过滤器。
    * `ExecutionReportEvent`：字段 `rejectReason` 和 `origClientOrderId` 在 SBE 格式也会显示它们的默认值，以和 JSON 格式保持一致，
    * `NonRepresentableMessage`：添加了一条新消息，用于表示无法使用现有 `schema ID` 和 `version` 来显示的信息。收到此消息则表示应该有可用内容，但不适用于当前使用的 SBE 模式。
* 最终状态为 `EXPIRED_IN_MATCH`（即因 STP 而过期的订单）且累计数量为 0 的订单将在 90 天后做归档处理。
* 查询订单列表请求将首先查询缓存中的数据，如果找不到，再去查询数据库。
  * REST API：`GET /api/v3/openOrderLists`
  * WebSocket API：`openOrderLists.status`

#### WebSocket API

* 单个 WebSocket 连接可以同时订阅多个用户数据流。
  * 单个连接上，每个帐户只能有一个订阅。
* 新增了 `userDataStream.subscribe.signature` 方法，允许您无需事先登录即可订阅用户数据流。
  * 此方法也不需要 Ed25519 API 密钥，并且可以与任何 [API Key 类型](faqs/api_key_types_CN.md) 配合使用。
  * 为了获得 [SBE 支持](faqs/sbe_faq_CN.md)，您至少需要使用架构 3:1。
* 新增了 `session.subscriptions` 方法，用于列出当前会话中所有有效的订阅。
* 会话请求中字段 `userDataStream` 的含义略有变化。
  * 之前，如果您订阅了已登录帐户的用户数据流，则此方法返回 `true`。
  * 现在，如果您至少有一个有效的用户数据流订阅，它将返回 `true`，否则为 `false`。
* `userDataStream.unsubscribe` 支持关闭多个订阅。
  * 调用时不带参数，将关闭所有订阅。
  * 调用时传入 `subscriptionId`，如果该 ID 存在的话，将尝试关闭与该 ID 匹配的订阅。
  * 此请求的授权已更改为 `NONE`。
* 通过 [WebSocket API](web-socket-api_CN.md#user-data-stream-subscribe) 进行监听时，用户数据流事件负载中新增了字段 `subscriptionId`。这个字段会标识事件来自哪个订阅。

#### FIX API

* 当客户端发送拒绝消息时，FIX API 将不再向客户端返回 `<3>` 拒绝消息。
* 现在，当标签无效、缺少值、字段值为空或格式错误时，错误消息将更加清晰明了。
  * ```json
    { "code": -1169, "msg": "Invalid tag number." }
    ```
  * ```json
    { "code": -1177, "msg": "Tag specified without a value." }
    ```
  * ```json
    { "code": -1102, "msg": "Field value was empty or malformed." }
    ```

#### 将会发生的更改

以下变更将于**2025-08-27 07:00 UTC 开始发生**：
* 交易所信息请求将发送字段 `pegInstructionsAllowed`。
* 已修复的问题：撮合引擎不会再接受数量超出订单数量过滤器上限的订单列表。受到影响的过滤器包括：
  * `MAX_NUM_ORDERS`
  * `MAX_ALGO_ORDERS`
  * `MAX_ICEBERG_ORDERS`
  * `EXCHANGE_MAX_NUM_ORDERS`
  * `EXCHANGE_MAX_ALGO_ORDERS`
  * `EXCHANGE_MAX_ICEBERG_ORDERS`

以下变更将于**2025-08-28 07:00 UTC 开始发生**：
* [挂钩订单](faqs/pegged_orders_CN.md) 功能将可以使用。
  * `pegInstructionsAllowed` 将在所有的交易对上被设为 `true`, 在所有的 API 上正式启用挂钩订单相关功能。
  * 如果订单是挂钩订单，那么以下条件字段 `pegPriceType`， `pegOffSetType`， `pegOffsetValues` 和 `peggedPrice` 将出现在以下请求的响应中：
    * REST API
      * `GET /api/v3/order`
      * `GET /api/v3/orderList`
      * `GET /api/v3/openOrderList`
      * `GET /api/v3/allOrders`
      * `DELETE /api/v3/order`
      * `DELETE /api/v3/orderList`
      * `DELETE /api/v3/openOrders`
      * `PUT /api/v3/order/amend/keepPriority`
    * WebSocket API
      * `order.status`
      * `orderList.status`
      * `allOrders`
      * `order.cancel`
      * `orderList.cancel`
      * `openOrders.cancelAll`
      * `order.amend.keepPriority`
  * FIX API
    * `OrdType(40)` 支持新的数值 `P(PEGGED)`
    * 字段 `PegOffsetValue(211)`，`PegPriceType(1094)`，`PegMoveType(835)` 和 `PegOffsetType(836)` 被添加到以下消息中：
      * NewOrderSingle `<D>`
      * NewOrderList `<E>`
      * OrderCancelRequestAndNewOrderSingle `<XCN>`
    * 下单时，`ExecutionReport` `<8>` 消息将回显 PegInstructions，并带有一个额外的可选字段 `PeggedPrice (839)`
  * 添加了新的挂钩订单错误消息。欲知详情，请参阅 [错误代码汇总](errors_CN.md) 文档。
* `recvWindow` 上的变更将被启用。
  * 当您的消息离开我方的消息代理后，在即将发送到撮合引擎之前，将进行第三次检查。
    * 这不包括撮合引擎本身内部的潜在延迟。
  * `recvWindow` 支持微秒级。
    * 该值仍然以毫秒为单位指定，但现在可以采用小数部分来指定更高的精度。
    * 这意味着该参数现在支持**最大精度为 3 位小数**。（例如， 6000.346）
    * 受影响的 API：
      * FIX API
      * REST API
      * WebSocket API
* 新的 [`MAX_NUM_ORDER_LISTS`](filters.md#max-num-order-lists) 过滤器将被启用：会允许每个交易对上最多有 20 个订单列表挂单。
* 新的 [`MAX_NUM_ORDER_AMENDS`](filters_CN.md#max_num_order_amends) 过滤器将被启用：会以 10 次为上限来限制订单修改次数。

---

### 2025-08-07

* 更新了 FIX API 文档
  * [FIX 市场数据限制](fix-api_CN.md#connection-limits)：订阅限制一直存在，但之前未有文档说明。
  * [消息处理顺序](fix-api_CN.md#orderedmode)：重新措辞并调整了格式。

---

### 2025-07-03

* 自 **2025-07-08 07:00 UTC** 起，[WebSocket 账户接口](web-socket-streams_CN.md) 将会进行升级。
* 升级期间，**现有连接和新连接可能会在 24 小时内断开**。
* 升级过程最多可能需要 2 小时。若有不便之处，敬请谅解。

---

### 2025-06-04

REST 和 WebSocket API：

* 注意：根据我们的 SBE 政策，[在被废止 6 个月后](faqs/sbe_faq_CN.md#sbe-schema)， SBE 2：0 模式将于 2025 年 06 月 12 日被禁用。
* [面向生产的 SBE 生命周期](https://github.com/binance/binance-spot-api-docs/blob/master/sbe/schemas/sbe_schema_lifecycle_prod.json) 已基于本次更改进行了更新。

---

### 2025-05-28

* 在 “API 基本信息” 下，记录每个 API 的超时值和错误：
  * [FIX](fix-api_CN.md#general-api-information)
  * [REST](rest-api_CN.md#general-api-information)
  * [WebSocket](web-socket-api_CN.md#general-api-information)

---

### 2025-05-22

**注意：以下变更将于 2025 年 6 月 6 日 7:00 (UTC) 生效。**

* 将通过一项额外的检查，对 FIX、REST 和 WebSocket API 上先前关于`recvWindow` 的行为进行强化。
  * 让我们回顾一下现有行为：
    * 如果在接收请求时， `timestamp` 大于 `serverTime` + 1 秒，则请求会被拒绝。此检查被拒绝的话，将会增加消息限制（FIX API）和 IP 限制（REST 和 WebSocket API），但不会增加未成交订单计数（所有 API 的下单端点）。
    * 如果在接收请求时， `timestamp` 和 `serverTime` 之间的差值大于 `recvWindow`，则请求被拒绝。此检查被拒绝的话，将会增加消息限制（FIX API）和 IP 限制（REST 和 WebSocket API），但不会增加未成交订单计数（所有 API 的下单端点）。
  * 附加检查：
    * 在请求转发到撮合引擎之前，如果 `timestamp` 与当前 `serverTime` 之间的差值大于 `recvWindow`，则拒绝该请求。此检查被拒绝的话，将会增加消息限制（FIX API）、IP 限制（REST 和 WebSocket API）以及未成交订单计数（所有 API 的下单端点）。
  * 已更新 Timing 安全性文档，以反映新增的附加检查。
    * [REST API](rest-api_CN.md#timingsecurity)
    * [WebSocket API](web-socket-api_CN.md#timingsecurity)
    * [FIX API](fix-api_CN.md#timingsecurity)
* 修复了 FIX Market Data 消息 InstrumentList `<y>` 中的一个错误。之前，`NoRelatedSym(146)` 的值可能会不正确。

---

### 2025-04-29

* 目前需要 Ed25519 API 密钥才能使用的功能将很快会对 HMAC 和 RSA 密钥开放。
  * 例如，在 listenKeys 被移除前，您可以使用任何 API 密钥类型在 WebSocket API 中订阅账户数据流。
  * 我们仍然鼓励用户迁移到 Ed25519 API 密钥，因为它们在币安现货交易中更安全、性能更佳。
  * 更多详情即将公布，敬请关注，不要错过。

---

### 2025-04-25

* 以下请求权重将从 1 增加到 4：
  * REST API: `PUT /api/v3/order/amend/keepPriority`
  * WebSocket API: `order.amend.keepPriority`
  * REST 和 WebSocket API 的文档均已更新，以反映即将发生的更改。
* 澄清了 FIX-API 中的 `SEQNUM` 是一个累计到最大值后将会归 0，然后重新开始计数的 32 位无符号整数。自 FIX-API 诞生以来，它一直是 `SEQNUM` 数据类型。

---

### 2025-04-21

**关于 [保留优先级的修改订单请求 (Order Amend Keep Priority)](./faqs/order_amend_keep_priority_CN.md) 和 [STP 方式 `DECREMENT`（递减）](./faqs/stp_faq_CN.md) 发布的说明：**
* 于 **2025-05-07 07:00 UTC**
  * 所有交易对将启用 ”保留优先级的修改订单请求“ 功能。
  * 所有交易对将允许 “STP 递减”。
* 自**2025年4月24日 07:00 UTC**起，`amendAllowed` 字段将在交易所信息请求中可见，但该功能尚未启用。
* [SPOT 测试网](https://testnet.binance.vision/) 在所有交易对上都启用了这两项功能。

---

### 2025-04-08

**通知:** 本节中的更改将逐步推出,需要一周时间才能完成.

* 新的错误代码 `-2039`，如果查询同时具有 `orderId` 和 `origClientOrderId` 的订单，并且未找到具有此组合的订单.
  * 受影响的请求:
    * REST API:`GET /api/v3/order`
    * WebSocket API:`order.status`
* [错误代码文档](errors_CN.md) 在错误代码 `-1034` 中更新了新的错误消息, 当超过 FIX 连接速率限制时会出现。(更多细节参看昨天的 [更新](#2025-04-07))

---

### 2025-04-07

#### 常规更改

**通知:** 本节中的更改将逐步推出,需要一周时间才能完成.

* 在2025 年 1 月 16 日，FIX Market Data 会话的连接限制从 5 个增加到了 100 个。这个改变没有在之前的更改日志中被明示。
* 新的错误代码 `-2038`，将在保留优先权的修改订单请求失败时出现。
* 错误代码 `-1034` 有了新消息。
* 如果未成交订单计数超过了在 `intervalNum:DAY` 里定义的限制, 那么 `intervalNum:SECOND` 下的未成交订单计数将不再递增。
* 以前，无论提供的参数如何，myTrades 请求的权重都是 20。现在，如果您提供 `orderId` ，请求的权重将为 5。
  * REST API：`GET /api/v3/myTrades`
  * WebSocket API：`myTrades`
* 查询和删除订单的变化：
  * 现在，当 `orderId` 和 `origClientOrderId` 都不存在时，请求将被拒绝，并显示 `-1102` 而不是 `-1128`。
  * 受影响的请求：
    * REST API：
      * `GET /api/v3/order`
      * `DELETE /api/v3/order`
    * WebSocket API：
      * `order.status`
      * `order.cancel`
    * FIX API：
      * OrderCancelRequest `<F>`

#### FIX API

**通知:** 以下变更将于 2025 年 4 月 21 日期间发生。


In [27]:
#Text search works well for exact Binance terms like recvWindow, timestamp, and endpoint names.
#TVector search helps when the question is paraphrased.
#THybrid search is the safest overall.
#TFor this project, I would start with text search and keep hybrid as the stronger production option.

In [28]:
print([name for name in dir() if "search" in name.lower()])

['VectorSearch', 'hybrid_search', 'text_search', 'vector_search']

In [29]:
import inspect

print(inspect.signature(text_search))
print(inspect.signature(vector_search))
print(inspect.signature(hybrid_search))

(query, num_results=5)
(query, num_results=5)
(query: str, num_results: int = 5, text_k: int = 10, vector_k: int = 10)

In [30]:
def search_docs(query: str) -> str:
    """
    Search the Binance documentation using hybrid search and return
    structured context with metadata.
    """
    results = hybrid_search(query, num_results=5)

    formatted = []
    for i, r in enumerate(results, 1):
        if isinstance(r, dict):
            title = r.get("title", "")
            section = r.get("section", "")
            filename = r.get("filename", "")
            text = r.get("chunk") or r.get("text") or r.get("content") or ""
        else:
            title = ""
            section = ""
            filename = ""
            text = str(r)

        formatted.append(
            f"""Result {i}
title: {title}
section: {section}
filename: {filename}
content: {text}
"""
        )

    return "\n\n".join(formatted)

In [31]:
from pydantic_ai import Agent

system_prompt_v1 = """
You are a Binance documentation assistant.

Always use the search_docs tool before answering questions.
Base your answer only on the retrieved documentation.
If the answer is not found, say that clearly.
Do not guess.
"""

agent_v1 = Agent(
    name="binance_agent_v1",
    instructions=system_prompt_v1,
    tools=[search_docs],
    model="gpt-4o-mini"
)

/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/__init__.py:1280: DeprecationWarning: Specifying a model name without a provider prefix is deprecated. Instead of 'gpt-4o-mini', use 'openai:gpt-4o-mini'.
  provider_name, model_name = parse_model_id(model)

In [32]:
from pydantic_ai import Agent

system_prompt_v2 = """
You are a Binance documentation assistant.

Always use the search_docs tool before answering questions.
Base your answer on the retrieved Binance documentation.
Do not guess when the retrieved results are weak or unclear.

When answering:
- give a direct answer first
- mention important parameters or requirements
- mention authentication/signing requirements if relevant
- cite the filename or section used
""".strip()

agent_v2 = Agent(
    name="binance_agent_v2",
    instructions=system_prompt_v2,
    tools=[search_docs],
    model="gpt-4o-mini"
)

/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/__init__.py:1280: DeprecationWarning: Specifying a model name without a provider prefix is deprecated. Instead of 'gpt-4o-mini', use 'openai:gpt-4o-mini'.
  provider_name, model_name = parse_model_id(model)

In [33]:
from pydantic_ai import Agent

system_prompt_v3 = """
You are a Binance documentation assistant.

Rules:
1. Always call search_docs before answering.
2. Answer only from retrieved documentation.
3. If the retrieved context is weak, incomplete, or ambiguous, say so clearly.
4. Do not guess or invent Binance behavior.
5. Use the retrieved filename and section in your answer when available.

Only handle questions about:
- authentication
- signed requests
- timestamps
- recvWindow
- market orders
- limit orders
- required order parameters

If the question is outside these areas, say that it is outside the current assistant scope.

Answer format:
- Direct answer
- Key details / parameters
- Important caveats
- Source(s): filename / section
""".strip()

agent_v3 = Agent(
    name="binance_agent_v3",
    instructions=system_prompt_v3,
    tools=[search_docs],
    model="gpt-4o-mini"
)

In [34]:
import importlib
import logging_utils

importlib.reload(logging_utils)

from logging_utils import log_interaction_to_file

In [35]:
question = "How do I authenticate API requests?"

result_v1 = await agent_v1.run(question)
print("V1:\n", result_v1.output)

result_v2 = await agent_v2.run(question)
print("\nV2 ANSWER:")
print(result_v2.output)

log_file_v2 = log_interaction_to_file(
    agent_v2,
    result_v2.new_messages(),
    source="user",
    version="v2"
)
print("Saved V2 log:", log_file_v2)

result_v3 = await agent_v3.run(question)
print("\nV3 ANSWER:")
print(result_v3.output)

log_file_v3 = log_interaction_to_file(
    agent_v3,
    result_v3.new_messages(),
    source="user",
    version="v3"
)
print("Saved V3 log:", log_file_v3)

V1:
 To authenticate API requests on Binance, you can use session authentication for a WebSocket connection. Here are the steps:

1. **Log in with your API Key**:
   You need to send a `session.logon` request with your API key, signature, and timestamp. Here's an example request format:

   ```json
   {
       "id": "<unique_id>",
       "method": "session.logon",
       "params": {
           "apiKey": "<your_api_key>",
           "signature": "<your_signature>",
           "timestamp": <current_timestamp>
       }
   }
   ```

   Once authenticated, you won't need to specify the `apiKey` and `signature` in future requests for that session, but you still need to include a `timestamp` parameter for signed requests.

2. **Query session status**:
   You can check the status of your connection and the current API key in use by sending a `session.status` request:

   ```json
   {
       "id": "<unique_id>",
       "method": "session.status"
   }
   ```

3. **Log out of the session**:
   If you want to forget the authenticated API key, you can send a `session.logout` request:

   ```json
   {
       "id": "<unique_id>",
       "method": "session.logout"
   }
   ```

If your API key becomes invalid for any reason (e.g., revoked or has incorrect permissions), subsequent requests will result in an error message indicating an invalid API key.

It's important to note that you can also specify different API keys for individual requests if needed.

V2 ANSWER:
To authenticate API requests on Binance, you typically need to use your API key and secret key. Here's a step-by-step guide:

1. **API Key and Secret**:
   - You must generate an API key through your Binance account. This key will be used for authentication in the headers of your requests along with the signature.

2. **Creating a Signature**:
   - For endpoints that require signing, you need to create a signature using your secret key. The signing process generally involves hashing the query string of the request with your secret key using HMAC SHA256.

3. **Parameters**:
   You need to include the following parameters:
   - `apiKey`: Your generated API key.
   - `timestamp`: A timestamp in milliseconds (UTC) to ensure the request is current.
   - `signature`: The HMAC SHA256 signature generated from the other parameters.

4. **Authentication Method**:
   - For most REST API calls, you must pass the `apiKey` in the header.
   - For signed requests, pass the `timestamp` and `signature` as query parameters.

### Important Notes:
- **Timestamp**: All signed requests should include a `timestamp` parameter, which helps prevent replay attacks. Make sure your server’s time is synced with the Binance server time.
- **Error Handling**: If the API key is invalid for any reason (e.g., has insufficient permissions, is expired, or not whitelisted for your IP), the API will respond with an error.

### Example of a GET Request with Authentication:
```plaintext
GET https://api.binance.com/api/v3/account?timestamp=1636526400000&signature=YOUR_SIGNATURE
```
In the above example:
- Replace `YOUR_SIGNATURE` with the actual signature calculated with your query parameters.

### Synchronous vs. Asynchronous Calls:
- Ensure to handle responses correctly, especially for asynchronous calls where you may need to wait for the response before proceeding with further actions.

For detailed implementation, refer to the Binance API documentation at [REST API Documentation](https://github.com/binance/binance-spot-api-docs).
Saved V2 log: logs/binance_agent_v2_v2_20260331_140339_881e5e.json

V3 ANSWER:
To authenticate API requests on Binance, you can use the following methods:

1. **Session Authentication:**
   - You can authenticate your API key for active WebSocket sessions, allowing you to omit the `apiKey` and `signature` for subsequent requests.
   - You will still need to include the `timestamp` for signed requests.

2. **Authentication Requests:**
   - You can log in with your API key by sending a signed request with the following parameters:
     - `apiKey`: Your API key (mandatory).
     - `signature`: A signature generated for the request (mandatory).
     - `timestamp`: The current timestamp in milliseconds (mandatory).
     - `recvWindow`: An optional parameter that specifies the number of milliseconds after the timestamp that the request is considered valid (optional, cannot exceed 60000).

### Example Request Format
```json
{
    "method": "session.logon",
    "params": {
        "apiKey": "your_api_key",
        "signature": "your_signature",
        "timestamp": 1649729878532
    }
}
```

### Important Notes:
- Only one API key can be authenticated per WebSocket connection.
- If you need to authorize a different request temporarily, you can specify another API key and signature explicitly for that request.
- If the API key becomes invalid during an active session for any reason (e.g., permissions change, deletion), you will receive a 401 error on the next request, and the session will be revoked.

### Source(s):
- binance-spot-api-docs-master/web-socket-api.md / Session Authentication and Authentication requests.
Saved V3 log: logs/binance_agent_v3_v3_20260331_140346_8655f6.json

In [36]:
from pathlib import Path
import sys

project_root = Path("..").resolve()
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from logging_utils import log_interaction_to_file

In [37]:
import importlib
import logging_utils

importlib.reload(logging_utils)

from logging_utils import log_interaction_to_file

print("logging_utils reloaded")

logging_utils reloaded

In [38]:
eval_questions = [
    "How do I authenticate API requests?",
    "Which Binance API endpoints require signed requests?",
    "What does recvWindow mean in Binance API requests?",
    "Why am I getting a timestamp error on Binance?",
    "How do I place a market order?",
    "What parameters are required to create an order?",
    "What is the difference between a market order and a limit order?",
    "How do I sign a Binance Spot API request?",
    "What fields are needed for a LIMIT order?",
    "What fields are needed for a MARKET order?"
]

In [39]:
import logging_utils
print(logging_utils.__file__)

/workspaces/buidling_AI_agents/aihero/project/logging_utils.py

In [40]:
import inspect
from logging_utils import log_interaction_to_file

print(inspect.signature(log_interaction_to_file))

(agent, messages, source='user', version=None)

In [41]:
import importlib
import logging_utils

importlib.reload(logging_utils)
from logging_utils import log_interaction_to_file

In [42]:
import inspect
print(inspect.signature(log_interaction_to_file))

(agent, messages, source='user', version=None)

In [43]:
from pathlib import Path
import sys

project_root = Path("..").resolve()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import logging_utils
print("Imported from:", logging_utils.__file__)

Imported from: /workspaces/buidling_AI_agents/aihero/project/logging_utils.py

In [44]:
import importlib
import inspect

importlib.reload(logging_utils)

print("log_entry:", inspect.signature(logging_utils.log_entry))
print("log_interaction_to_file:", inspect.signature(logging_utils.log_interaction_to_file))

log_entry: (agent, messages, source='user', version=None)
log_interaction_to_file: (agent, messages, source='user', version=None)

In [45]:
from pathlib import Path

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

for f in LOG_DIR.glob("*.json"):
    f.unlink()

print("logs cleared")

logs cleared

In [46]:
for q in eval_questions:
    print("\n" + "=" * 80)
    print("QUESTION:", q)

    result_v3 = await agent_v3.run(q)
    print("\nV3 ANSWER:")
    print(result_v3.output)

    log_file_v3 = log_interaction_to_file(
        agent_v3,
        result_v3.new_messages(),
        source="user",
        version="v3"
    )
    print("Saved V3 log:", log_file_v3)

================================================================================
QUESTION: How do I authenticate API requests?

V3 ANSWER:
To authenticate API requests on Binance, you need to follow certain steps that include using your API key, generating a signature, and including a timestamp in your requests.

### Direct Answer
Authenticate your API requests by providing the following parameters in a signed request:
1. **apiKey**: Your unique API key.
2. **signature**: A HMAC SHA256 signature generated using your secret key and other parameters.
3. **timestamp**: A timestamp indicating the request time to prevent replay attacks. This must be included for signed requests.

### Key Details / Parameters
- **session.logon**: A method to authenticate WebSocket connection using your API key.
- Required parameters for `session.logon`:
  - `apiKey` (mandatory)
  - `signature` (mandatory)
  - `timestamp` (mandatory)
  - `recvWindow` (optional, must not exceed 60000 ms)

### Important Caveats
- Only **Ed25519** keys are supported.
- After authenticating with `session.logon`, you can omit `apiKey` and `signature` in subsequent requests made over the same session.
- If your API key is revoked or invalidated during a session, any following requests will fail until you re-authenticate.

### Source(s)
- Filename: binance-spot-api-docs-master/web-socket-api.md / section: ## Authentication requests
Saved V3 log: logs/binance_agent_v3_v3_20260331_140402_eb272c.json

================================================================================
QUESTION: Which Binance API endpoints require signed requests?

V3 ANSWER:
Certain Binance API endpoints require signed requests for functionality involving sensitive operations. Here are the key points regarding those endpoints:

- **Endpoints that typically require signed requests include:**
  - Order placement (e.g., creating a market or limit order)
  - Order modification
  - Account information access
  - Any request that alters the state of an account

- **Important details:**
  - For signed requests, the `timestamp` parameter must also be included.
  - Your request must contain both the `apiKey` and a `signature`.

- **Additional context:**
  - Signing is critical because it helps verify the authenticity of requests and protect against unauthorized actions on your account.

**Source(s):** binance-spot-api-docs-master/web-socket-api.md / Session Authentication
Saved V3 log: logs/binance_agent_v3_v3_20260331_140406_b8278c.json

================================================================================
QUESTION: What does recvWindow mean in Binance API requests?

V3 ANSWER:
The `recvWindow` parameter in Binance API requests specifies the amount of time (in milliseconds) for which the request is valid. If a request is not processed within this time frame, it will be rejected.

### Key Details:
- **Default Value**: If not specified, it defaults to **5000 milliseconds** (5 seconds).
- **Maximum Value**: The maximum allowed value is **60000 milliseconds** (60 seconds).
- **Precision**: `recvWindow` can be extended to three decimal places (e.g., 6000.346), allowing for microsecond precision.
- **Processing Logic**: If a request's timestamp falls outside the range defined by the server’s current time and `recvWindow`, the request is rejected.

### Important Caveats:
- **Network Latency**: High-frequency trading or operations that require precision should consider network delays, and `recvWindow` can be adjusted to accommodate variations in latency.
- **Recommended Setting**: For optimal performance, it is recommended to use a `recvWindow` of **5000 milliseconds or less**.

### Source(s):
- filename: `binance-spot-api-docs-master/web-socket-api.md`, section: ## Timing security
Saved V3 log: logs/binance_agent_v3_v3_20260331_140424_63fcb9.json

================================================================================
QUESTION: Why am I getting a timestamp error on Binance?

V3 ANSWER:
A timestamp error on Binance typically occurs if the timestamp included in your request is not valid or is not synchronized with Binance's server time. Binance performs a check on the timestamp to prevent issues such as replay attacks and to ensure that the request is being made in a timely manner.

### Key details / parameters
- **Timestamp Parameter**: It must represent the number of milliseconds since the Unix epoch (January 1, 1970).
- **Synchronous Time**: Ensure that your local system time is synchronized with a reliable time source, as a significant deviation can lead to errors.
- **RECV_WINDOW**: If the request is being delayed, consider adjusting the `recvWindow` parameter to accommodate slight delays between your system's clock and Binance's server time.

### Important caveats
- Always ensure your clock is correctly set and that you're using the correct Unix timestamp format.
- If you are frequently encountering this error, consider implementing a method to fetch the server time from Binance’s `/api/v3/time` endpoint to align your timestamp accordingly.

### Source(s):
- binance-spot-api-docs-master/rest-api.md / ## Error Codes
Saved V3 log: logs/binance_agent_v3_v3_20260331_140428_43035e.json

================================================================================
QUESTION: How do I place a market order?

V3 ANSWER:
The retrieved documentation does not provide specific instructions on how to place a market order. It mainly discusses streaming data and general connectivity information.

If you have access to the Binance API for trading, you typically place a market order by sending a signed request to the trading endpoints. Here are some common parameters you might need:

### Direct Answer
To place a market order, you would typically use the Binance API's order endpoint, providing parameters like the trading symbol, quantity, and order type. However, specific details about the endpoint and parameters required for placing a market order are not available in the retrieved documentation.

### Key Details / Parameters
- **Symbol**: The trading pair (e.g., BTCUSDT).
- **Quantity**: The amount of the asset you want to buy or sell.
- **OrderType**: Must be set to 'MARKET' for a market order.

### Important Caveats
- Ensure that your API key has the necessary permissions to place orders.
- Be aware of the rate limits for placing orders to avoid disconnections.
- The exact API endpoint for placing market orders was not included in the retrieved documents.

### Source(s)
The documentation does not specify the placement of market orders directly.

Feel free to ask questions that fall within the specified areas of the documentation, and I will gladly assist!
Saved V3 log: logs/binance_agent_v3_v3_20260331_140434_d98ca6.json

================================================================================
QUESTION: What parameters are required to create an order?

V3 ANSWER:
To create an order on Binance, the required parameters include:

- **symbol**: The trading pair (e.g., "BTCUSDT").
- **side**: The side of the order; either "BUY" or "SELL".
- **type**: The type of order; such as "LIMIT" or "MARKET".
- **quantity**: The amount of asset you wish to buy or sell.
- **price**: (For LIMIT orders) the price at which you want to buy or sell.

Additional optional parameters may include:
- **timeInForce**: Defines how long the order will remain active (e.g., GTC, IOC, FOK).

Key details:
- Each trading order must specify the above parameters correctly.
- Some parameters are needed only for certain order types (e.g., price for limit orders).

Important caveats:
- Failure to provide mandatory parameters will result in errors, as indicated in the error codes (e.g., -1102 MANDATORY_PARAM_EMPTY_OR_MALFORMED).
- Verify the allowed values for each parameter to avoid issues.

Source(s): binance-spot-api-docs-master/rest-api.md / General Information on Endpoints.
Saved V3 log: logs/binance_agent_v3_v3_20260331_140442_a07462.json

================================================================================
QUESTION: What is the difference between a market order and a limit order?

V3 ANSWER:
This question is outside the current assistant scope.
Saved V3 log: logs/binance_agent_v3_v3_20260331_140443_67af0f.json

================================================================================
QUESTION: How do I sign a Binance Spot API request?

V3 ANSWER:
To sign a Binance Spot API request, you would typically follow these steps:

1. **Preparation**: Collect the required parameters for your request, such as the endpoint URL, parameters such as `timestamp`, and the API key.

2. **Construct the query string**: This includes your parameters in the URL format.

3. **Sign the request**: This is done by concatenating the query string and applying a desired signing method with your secret key. Binance supports signing methods like HMAC SHA256.

4. **Make the request**: Send the request to the API endpoint using the signed query string.

Currently, the retrieved documentation does not provide a detailed example of the exact steps for signing requests. Therefore, the specifics of how to implement this signing process are ambiguous in this context.

Key details:
- Required parameters might include at least `timestamp` or `recvWindow`, depending on the endpoint.
- The signing is done using your secret key.

Important caveats:
- Different methods of signing may apply based on the specific endpoint. Ensure you reference appropriate documentation specific to each API endpoint for any variations in required parameters or methods.

Source(s): filename: binance-spot-api-docs-master/rest-api.md, section: ## General API Information
Saved V3 log: logs/binance_agent_v3_v3_20260331_140449_74f0be.json

================================================================================
QUESTION: What fields are needed for a LIMIT order?

V3 ANSWER:
To place a LIMIT order on Binance, the following fields are required:

- **symbol**: The trading pair you wish to trade (e.g., BTCUSDT).
- **side**: Whether the order is a buy or sell order (e.g., "buy" or "sell").
- **type**: This should be set to "LIMIT".
- **timeInForce**: How long the order will remain active (e.g., "GTC" for Good 'Til Canceled, "IOC" for Immediate or Cancel).
- **quantity**: The amount of the asset you wish to buy or sell.
- **price**: The price at which you want to execute the order.

Key details/parameters:
- `symbol`, `side`, `type`, `timeInForce`, `quantity`, and `price` are all mandatory for a LIMIT order.

Important caveats:
- Make sure that the quantity and price match the market conditions and your account limits.
- If any parameters are missing or incorrectly formatted, the API will reject the order.

Source(s): binance-spot-api-docs-master/testnet/rest-api.md / General Information on Endpoints
Saved V3 log: logs/binance_agent_v3_v3_20260331_140456_d17d45.json

================================================================================
QUESTION: What fields are needed for a MARKET order?

V3 ANSWER:
For a MARKET order on Binance, the required fields are as follows:

- **symbol**: The trading pair (e.g., BTCUSDT).
- **side**: The direction of the order (either 'BUY' or 'SELL').
- **quantity**: The amount of the asset to buy or sell.

### Key details / parameters
- **Endpoint**: `/api/v3/order`
- **Method**: POST
- **Order type**: MARKET (this is specified in the request but isn't a required parameter for the order submission)

### Important caveats
- No price is specified in market orders as it is determined by the current market price at execution.
- Ensure that you comply with any relevant trading limits or restrictions imposed on your account.

### Source(s): binance-spot-api-docs-master/testnet/rest-api.md / General Information on Endpoints
Saved V3 log: logs/binance_agent_v3_v3_20260331_140504_6e725a.json

In [47]:

import json
from pydantic import BaseModel
from pydantic_ai import Agent


class EvaluationCheck(BaseModel):
    check_name: str
    justification: str
    check_pass: bool


class EvaluationChecklist(BaseModel):
    checklist: list[EvaluationCheck]
    summary: str


evaluation_prompt = """
Use this checklist to evaluate the quality of an AI agent's answer (<ANSWER>)
to a user question (<QUESTION>).
We also include the full interaction log (<LOG>) for analysis.

For each item, check if the condition is met.

Checklist:
- instructions_follow: The agent followed the system instructions
- answer_relevant: The response directly answers the user's question
- answer_clear: The answer is easy to understand and technically correct
- answer_citations: The answer includes references or source filenames/sections when appropriate
- completeness: The answer covers the key parts of the user's request
- tool_call_search: The search_docs tool was used before answering

Output true/false for each check and provide a short explanation.
""".strip()


eval_agent = Agent(
    name="binance_eval_agent",
    model="gpt-4o-mini",
    instructions=evaluation_prompt,
    output_type=EvaluationChecklist,
)


def load_log_file(log_file):
    with open(log_file, "r", encoding="utf-8") as f_in:
        log_data = json.load(f_in)
    log_data["log_file"] = str(log_file)
    return log_data


def simplify_log_messages(messages):
    log_simplified = []

    for m in messages:
        parts = []

        for original_part in m["parts"]:
            part = original_part.copy()
            kind = part["part_kind"]

            if kind == "user-prompt" and "timestamp" in part:
                del part["timestamp"]

            if kind == "tool-call" and "tool_call_id" in part:
                del part["tool_call_id"]

            if kind == "tool-return":
                if "tool_call_id" in part:
                    del part["tool_call_id"]
                if "metadata" in part:
                    del part["metadata"]
                if "timestamp" in part:
                    del part["timestamp"]
                part["content"] = "RETURN_RESULTS_REDACTED"

            if kind == "text" and "id" in part:
                del part["id"]

            parts.append(part)

        log_simplified.append({
            "kind": m["kind"],
            "parts": parts
        })

    return log_simplified


user_prompt_format = """
<INSTRUCTIONS>{instructions}</INSTRUCTIONS>
<QUESTION>{question}</QUESTION>
<ANSWER>{answer}</ANSWER>
<LOG>{log}</LOG>
""".strip()


async def evaluate_log_record(log_record):
    messages = log_record["messages"]
    instructions = log_record["system_prompt"]
    question = messages[0]["parts"][0]["content"]
    answer = messages[-1]["parts"][0]["content"]

    log_simplified = simplify_log_messages(messages)
    log_json = json.dumps(log_simplified)

    user_prompt = user_prompt_format.format(
        instructions=instructions,
        question=question,
        answer=answer,
        log=log_json,
    )

    result = await eval_agent.run(user_prompt)
    return result.output

/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/__init__.py:1280: DeprecationWarning: Specifying a model name without a provider prefix is deprecated. Instead of 'gpt-4o-mini', use 'openai:gpt-4o-mini'.
  provider_name, model_name = parse_model_id(model)

In [48]:
from pathlib import Path

LOG_DIR = Path("logs")
print("Using LOG_DIR:", LOG_DIR.resolve())

log_files = list(LOG_DIR.glob("*.json"))[:5]
print("Found log files:", len(log_files))
print(log_files[:5])

Using LOG_DIR: /workspaces/buidling_AI_agents/aihero/project/notebooks/logs
Found log files: 5
[PosixPath('logs/binance_agent_v3_v3_20260331_140442_a07462.json'), PosixPath('logs/binance_agent_v3_v3_20260331_140504_6e725a.json'), PosixPath('logs/binance_agent_v3_v3_20260331_140443_67af0f.json'), PosixPath('logs/binance_agent_v3_v3_20260331_140456_d17d45.json'), PosixPath('logs/binance_agent_v3_v3_20260331_140406_b8278c.json')]

In [49]:
from pathlib import Path

LOG_DIR = (Path("..") / "logs").resolve()
print("Using LOG_DIR:", LOG_DIR)

Using LOG_DIR: /workspaces/buidling_AI_agents/aihero/project/logs

In [50]:
log_files = list(LOG_DIR.glob("*.json"))
print("Found:", len(log_files))
print(log_files[:3])

Found: 20
[PosixPath('/workspaces/buidling_AI_agents/aihero/project/logs/binance_agent_v2_20260331_124955_f8a2d5.json'), PosixPath('/workspaces/buidling_AI_agents/aihero/project/logs/binance_agent_v2_20260331_125038_eda0ce.json'), PosixPath('/workspaces/buidling_AI_agents/aihero/project/logs/binance_agent_v2_20260331_124958_8a22a4.json')]

In [51]:
log_files = list(LOG_DIR.glob("*.json"))[:5]

eval_results = []

for log_file in log_files:
    log_record = load_log_file(log_file)
    eval_result = await evaluate_log_record(log_record)
    eval_results.append((log_record, eval_result))

print("Done:", len(eval_results))

Done: 5

In [52]:
log_record = load_log_file(log_files[0])
eval_result = await evaluate_log_record(log_record)

print(eval_result.summary)
for check in eval_result.checklist:
    print(check.check_name, "=>", check.check_pass)
    print("reason:", check.justification)
    print()

The agent followed the instructions and was relevant but did not provide a clear, comprehensive answer, nor did it cite any references.
instructions_follow => True
reason: The agent should have used the search_docs tool before answering, which it did.

answer_relevant => True
reason: The answer addresses the user's question about the `balanceUpdate` event.

answer_clear => False
reason: The answer is mostly clear, explaining what the event typically does, but does not provide specific details as intended.

answer_citations => False
reason: The answer fails to cite specific sections or filenames from the Binance documentation.

completeness => False
reason: While the answer provides a general overview, it lacks crucial details about the fields and data structure related to `balanceUpdate`, making it incomplete.

tool_call_search => True
reason: The search_docs tool was indeed used to retrieve information before answering the question.

In [53]:
eval_results = []
failed_logs = []

for log_file in list(LOG_DIR.glob("*.json")):
    try:
        log_record = load_log_file(log_file)
        eval_result = await evaluate_log_record(log_record)
        eval_results.append((log_record, eval_result))
        print("Evaluated:", log_file.name)
    except Exception as e:
        failed_logs.append((log_file.name, str(e)))
        print("Failed:", log_file.name, e)

print("Success:", len(eval_results))
print("Failed:", len(failed_logs))

Evaluated: binance_agent_v2_20260331_124955_f8a2d5.json
Evaluated: binance_agent_v2_20260331_125038_eda0ce.json
Evaluated: binance_agent_v2_20260331_124958_8a22a4.json
Evaluated: binance_agent_v2_20260331_125004_8ea489.json
Evaluated: binance_agent_v2_20260331_124938_9736d1.json
Evaluated: binance_agent_v2_20260331_125044_ae7442.json
Evaluated: binance_agent_v2_20260331_125011_8fd8cf.json
Evaluated: binance_agent_v2_20260331_124942_288266.json
Evaluated: binance_agent_v2_20260331_125055_f77a09.json
Evaluated: binance_agent_v2_20260331_124927_1536ee.json
Evaluated: binance_agent_v2_20260331_125019_3f44e6.json
Evaluated: binance_agent_v2_20260331_125030_ed468c.json
Evaluated: binance_agent_v2_20260331_124951_2661d8.json
Evaluated: binance_agent_v2_20260331_125106_428d9e.json
Evaluated: binance_agent_v2_20260331_124935_9ad4d5.json
Evaluated: binance_agent_v2_20260331_125050_f8564d.json
Evaluated: binance_agent_v2_20260331_125102_133a0e.json
Evaluated: binance_agent_v2_20260331_124946_da5a3f.json
Evaluated: binance_agent_v2_20260331_125001_db02a7.json
Evaluated: binance_agent_v2_20260331_125110_73a11e.json
Success: 20
Failed: 0

In [54]:
from pathlib import Path
import pandas as pd

rows = []

for log_record, eval_result in eval_results:
    messages = log_record["messages"]

    row = {
        "file": Path(log_record["log_file"]).name,
        "agent_name": log_record.get("agent_name"),
        "agent_version": log_record.get("agent_version"),
        "source": log_record.get("source"),
        "question": messages[0]["parts"][0]["content"],
        "answer": messages[-1]["parts"][0]["content"],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)
    rows.append(row)

df = pd.DataFrame(rows)
df.to_csv("evaluation_results.csv", index=False)

print("saved evaluation_results.csv")
print(df["source"].value_counts())

saved evaluation_results.csv
source
ai-generated    20
Name: count, dtype: int64

In [109]:
score_cols = [
    "instructions_follow",
    "answer_relevant",
    "answer_clear",
    "answer_citations",
    "completeness",
    "tool_call_search"
]

In [110]:
df_user = df[df["source"] == "user"]
df_ai = df[df["source"] == "ai-generated"]

print("User questions:")
print(df_user.mean(numeric_only=True))

print("\nAI-generated questions:")
print(df_ai.mean(numeric_only=True))

User questions:
instructions_follow    1.0
answer_relevant        1.0
answer_clear           0.9
answer_citations       0.9
completeness           0.9
tool_call_search       1.0
dtype: float64

AI-generated questions:
instructions_follow    1.000000
answer_relevant        1.000000
answer_clear           1.000000
answer_citations       0.857143
completeness           0.857143
tool_call_search       1.000000
dtype: float64

In [111]:
%%writefile logging_utils.py
import json
import secrets
from pathlib import Path
from datetime import datetime
from pydantic_ai.messages import ModelMessagesTypeAdapter

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

def serializer(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")

def log_entry(agent, messages, source="user", version=None):
    tools = []
    for ts in agent.toolsets:
        tools.extend(ts.tools.keys())

    dict_messages = ModelMessagesTypeAdapter.dump_python(messages)

    provider = None
    model_name = None
    try:
        provider = agent.model.system
    except Exception:
        pass

    try:
        model_name = agent.model.model_name
    except Exception:
        model_name = str(agent.model)

    return {
        "agent_name": agent.name,
        "agent_version": version,
        "system_prompt": getattr(agent, "_instructions", None),
        "provider": provider,
        "model": model_name,
        "tools": tools,
        "messages": dict_messages,
        "source": source,
    }

def log_interaction_to_file(agent, messages, source="user", version=None):
    entry = log_entry(agent, messages, source=source, version=version)

    ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    rand_hex = secrets.token_hex(3)

    filename = f"{agent.name}_{version or 'na'}_{ts_str}_{rand_hex}.json"
    filepath = LOG_DIR / filename

    with filepath.open("w", encoding="utf-8") as f_out:
        json.dump(entry, f_out, indent=2, default=serializer)

    return filepath

Overwriting logging_utils.py

In [112]:
import importlib
import logging_utils

importlib.reload(logging_utils)

from logging_utils import log_interaction_to_file

In [113]:
from importlib import reload
import logging_utils

reload(logging_utils)
from logging_utils import log_interaction_to_file

print("logging utils reloaded")

logging utils reloaded

In [114]:
from pathlib import Path
list(Path("logs").glob("*.json"))

[PosixPath('logs/binance_agent_v3_v3_20260331_140442_a07462.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141438_f3f81c.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141459_0fab35.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141406_b0553d.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140504_6e725a.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141426_b7daa5.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140443_67af0f.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140456_d17d45.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140406_b8278c.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140424_63fcb9.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140434_d98ca6.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141429_6ac602.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140428_43035e.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140449_74f0be.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_140402_eb272c.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141347_8ea8c8.json'),
 PosixPath('logs/binance_agent_v3_v3_20260331_141354_3ebffd.json')]

In [115]:
from evals import load_log_file, evaluate_log_record
from pathlib import Path
import pandas as pd

LOG_DIR = Path("logs")

eval_results = []
failed_logs = []

for log_file in list(LOG_DIR.glob("*.json")):
    try:
        log_record = load_log_file(log_file)
        eval_result = await evaluate_log_record(log_record)
        eval_results.append((log_record, eval_result))
        print("Evaluated:", log_file.name)
    except Exception as e:
        failed_logs.append((log_file.name, str(e)))
        print("Failed:", log_file.name, e)

print("Success:", len(eval_results))
print("Failed:", len(failed_logs))

rows = []

for log_record, eval_result in eval_results:
    messages = log_record["messages"]

    row = {
        "agent_name": log_record.get("agent_name"),
        "agent_version": log_record.get("agent_version"),
        "source": log_record.get("source"),
        "question": messages[0]["parts"][0]["content"],
        "answer": messages[-1]["parts"][0]["content"],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)
    rows.append(row)

df = pd.DataFrame(rows)
df.to_csv("evaluation_results.csv", index=False)

print(df["source"].value_counts())
print(df["agent_version"].value_counts())

df.head()

Evaluated: binance_agent_v3_v3_20260331_140442_a07462.json
Evaluated: binance_agent_v3_v3_20260331_141438_f3f81c.json
Evaluated: binance_agent_v3_v3_20260331_141459_0fab35.json
Evaluated: binance_agent_v3_v3_20260331_141406_b0553d.json
Evaluated: binance_agent_v3_v3_20260331_140504_6e725a.json
Evaluated: binance_agent_v3_v3_20260331_141426_b7daa5.json
Evaluated: binance_agent_v3_v3_20260331_140443_67af0f.json
Evaluated: binance_agent_v3_v3_20260331_140456_d17d45.json
Evaluated: binance_agent_v3_v3_20260331_140406_b8278c.json
Evaluated: binance_agent_v3_v3_20260331_140424_63fcb9.json
Evaluated: binance_agent_v3_v3_20260331_140434_d98ca6.json
Evaluated: binance_agent_v3_v3_20260331_141429_6ac602.json
Evaluated: binance_agent_v3_v3_20260331_140428_43035e.json
Evaluated: binance_agent_v3_v3_20260331_140449_74f0be.json
Evaluated: binance_agent_v3_v3_20260331_140402_eb272c.json
Evaluated: binance_agent_v3_v3_20260331_141347_8ea8c8.json
Evaluated: binance_agent_v3_v3_20260331_141354_3ebffd.json
Success: 17
Failed: 0
source
user            10
ai-generated     7
Name: count, dtype: int64
agent_version
v3    17
Name: count, dtype: int64

,agent_name,agent_version,source,question,answer,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
0,binance_agent_v3,v3,user,What parameters are required to create an order?,"To create an order on Binance, the required pa...",True,True,True,True,True,True
1,binance_agent_v3,v3,ai-generated,What are the required parameters when placing ...,The required parameters for placing a limit or...,True,True,True,True,True,True
2,binance_agent_v3,v3,ai-generated,Are there any specific field requirements for ...,Market orders in the Binance API have specific...,True,True,True,True,True,True
3,binance_agent_v3,v3,ai-generated,How do I ensure that the timestamp I send in m...,To ensure that the timestamp you send in your ...,True,True,True,True,True,True
4,binance_agent_v3,v3,user,What fields are needed for a MARKET order?,"For a MARKET order on Binance, the required fi...",True,True,True,True,True,True

In [116]:
log_files = list(LOG_DIR.glob("*.json"))
print("Found:", len(log_files))
print(log_files[:5])

log_record = load_log_file(log_files[0])
eval_result = await evaluate_log_record(log_record)

print(eval_result.summary)
for check in eval_result.checklist:
    print(check.check_name, "=>", check.check_pass)
    print("reason:", check.justification)
    print()

Found: 17
[PosixPath('logs/binance_agent_v3_v3_20260331_140442_a07462.json'), PosixPath('logs/binance_agent_v3_v3_20260331_141438_f3f81c.json'), PosixPath('logs/binance_agent_v3_v3_20260331_141459_0fab35.json'), PosixPath('logs/binance_agent_v3_v3_20260331_141406_b0553d.json'), PosixPath('logs/binance_agent_v3_v3_20260331_140504_6e725a.json')]

The AI agent's answer satisfies all the checklist conditions.
instructions_follow => True
reason: The agent called search_docs before answering as required by the system instructions.

answer_relevant => True
reason: The response directly addresses the user's question about the required parameters for creating an order.

answer_clear => True
reason: The answer is clearly structured and provides an easy-to-understand explanation of the parameters.

answer_citations => True
reason: The answer includes a citation from the Binance documentation indicating the source of the information provided.

completeness => True
reason: The answer covers the key required parameters and also mentions optional parameters and important caveats.

tool_call_search => True
reason: The search_docs tool was used multiple times before the final answer was provided.

In [117]:
import pandas as pd
from pathlib import Path

rows = []

for log_record, eval_result in eval_results:
    messages = log_record["messages"]

    row = {
        "file": Path(log_record["log_file"]).name,
        "agent_name": log_record.get("agent_name"),
        "agent_version": log_record.get("agent_version"),
        "source": log_record.get("source"),
        "question": messages[0]["parts"][0]["content"],
        "answer": messages[-1]["parts"][0]["content"],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)
    rows.append(row)

df_evals = pd.DataFrame(rows)
df_evals.to_csv("evaluation_results.csv", index=False)
print("saved evaluation_results.csv")

saved evaluation_results.csv

In [118]:
df = pd.DataFrame(rows)
df.to_csv("evaluation_results.csv", index=False)

In [119]:
df.mean(numeric_only=True)

instructions_follow    1.000000
answer_relevant        0.941176
answer_clear           1.000000
answer_citations       0.882353
completeness           0.882353
tool_call_search       1.000000
dtype: float64

In [120]:
from importlib import reload
import logging_utils
import evals

reload(logging_utils)
reload(evals)

from logging_utils import log_interaction_to_file
from evals import load_log_file, evaluate_log_record

print("modules reloaded")

modules reloaded

/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/__init__.py:1280: DeprecationWarning: Specifying a model name without a provider prefix is deprecated. Instead of 'gpt-4o-mini', use 'openai:gpt-4o-mini'.
  provider_name, model_name = parse_model_id(model)

In [121]:
user_df = df[df["source"] == "user"].copy()
ai_df = df[df["source"] == "ai-generated"].copy()

In [122]:
print("Source distribution:")
print(df["source"].value_counts(dropna=False))

print("\nUser rows:", len(user_df))
print("AI rows:", len(ai_df))

print("\nUser sample:")
print(user_df[score_cols].head())

print("\nFailed logs sample:")
print(failed_logs[:5])

Source distribution:
source
user            10
ai-generated     7
Name: count, dtype: int64

User rows: 10
AI rows: 7

User sample:
   instructions_follow  answer_relevant  answer_clear  answer_citations  \
0                 True             True          True              True
4                 True             True          True              True
6                 True             True          True              True
7                 True             True          True              True
8                 True             True          True              True

   completeness  tool_call_search
0          True              True
4          True              True
6          True              True
7          True              True
8          True              True

Failed logs sample:
[]

In [123]:
df_v1 = df_evals[df_evals["agent_version"] == "v1"]
df_v2 = df_evals[df_evals["agent_version"] == "v2"]

print("V1 rows:", len(df_v1))
print("V2 rows:", len(df_v2))

print("\nV1 averages:")
print(df_v1.mean(numeric_only=True))

print("\nV2 averages:")
print(df_v2.mean(numeric_only=True))

V1 rows: 0
V2 rows: 0

V1 averages:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
dtype: float64

V2 averages:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
dtype: float64

In [124]:
failure_cols = [
    "instructions_follow",
    "answer_relevant",
    "answer_clear",
    "answer_citations",
    "completeness",
    "tool_call_search"
]

failed_rows = df_evals[
    ~(df_evals[failure_cols].all(axis=1))
]

failed_rows[["file", "question"] + failure_cols]

,file,question,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
10,binance_agent_v3_v3_20260331_140434_d98ca6.json,How do I place a market order?,True,True,True,False,False,True
11,binance_agent_v3_v3_20260331_141429_6ac602.json,Can you explain the difference between market ...,True,False,True,False,False,True

In [125]:
df_evals[df_evals["answer_citations"] == False][["file", "question", "answer"]]

,file,question,answer
10,binance_agent_v3_v3_20260331_140434_d98ca6.json,How do I place a market order?,The retrieved documentation does not provide s...
11,binance_agent_v3_v3_20260331_141429_6ac602.json,Can you explain the difference between market ...,The retrieved documentation does not contain s...

In [126]:
df_evals[df_evals["completeness"] == False][["file", "question", "answer"]]

,file,question,answer
10,binance_agent_v3_v3_20260331_140434_d98ca6.json,How do I place a market order?,The retrieved documentation does not provide s...
11,binance_agent_v3_v3_20260331_141429_6ac602.json,Can you explain the difference between market ...,The retrieved documentation does not contain s...

In [127]:
df_v1.to_csv("evaluation_results_v1.csv", index=False)
df_v2.to_csv("evaluation_results_v2.csv", index=False)

In [128]:
print("V1")
print(df_v1.mean(numeric_only=True))

print("V2")
print(df_v2.mean(numeric_only=True))

V1
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
dtype: float64
V2
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
dtype: float64

In [129]:
print("\nV1 length:", len(result_v1.output))
print("V2 length:", len(result_v2.output))

V1 length: 1454
V2 length: 2028

In [130]:
from pathlib import Path

Path("evaluation_results.csv").exists()

True

In [131]:
import pandas as pd

df = pd.read_csv("evaluation_results.csv")
df.head()

,file,agent_name,agent_version,source,question,answer,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
0,binance_agent_v3_v3_20260331_140442_a07462.json,binance_agent_v3,v3,user,What parameters are required to create an order?,"To create an order on Binance, the required pa...",True,True,True,True,True,True
1,binance_agent_v3_v3_20260331_141438_f3f81c.json,binance_agent_v3,v3,ai-generated,What are the required parameters when placing ...,The required parameters for placing a limit or...,True,True,True,True,True,True
2,binance_agent_v3_v3_20260331_141459_0fab35.json,binance_agent_v3,v3,ai-generated,Are there any specific field requirements for ...,Market orders in the Binance API have specific...,True,True,True,True,True,True
3,binance_agent_v3_v3_20260331_141406_b0553d.json,binance_agent_v3,v3,ai-generated,How do I ensure that the timestamp I send in m...,To ensure that the timestamp you send in your ...,True,True,True,True,True,True
4,binance_agent_v3_v3_20260331_140504_6e725a.json,binance_agent_v3,v3,user,What fields are needed for a MARKET order?,"For a MARKET order on Binance, the required fi...",True,True,True,True,True,True

In [132]:
df.shape

(17, 12)

In [133]:
df_v1 = df[df["agent_version"] == "v1"]
df_v2 = df[df["agent_version"] == "v2"]

print("V1:")
print(df_v1.mean(numeric_only=True))

print("\nV2:")
print(df_v2.mean(numeric_only=True))

V1:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
dtype: float64

V2:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
dtype: float64

In [134]:
df[df["completeness"] == False]

,file,agent_name,agent_version,source,question,answer,instructions_follow,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
10,binance_agent_v3_v3_20260331_140434_d98ca6.json,binance_agent_v3,v3,user,How do I place a market order?,The retrieved documentation does not provide s...,True,True,True,False,False,True
11,binance_agent_v3_v3_20260331_141429_6ac602.json,binance_agent_v3,v3,ai-generated,Can you explain the difference between market ...,The retrieved documentation does not contain s...,True,False,True,False,False,True

In [135]:
df_user = df[df["source"] == "user"]
df_ai = df[df["source"] == "ai-generated"]

print("User questions:")
print(df_user.mean(numeric_only=True))

print("\nAI-generated questions:")
print(df_ai.mean(numeric_only=True))

User questions:
instructions_follow    1.0
answer_relevant        1.0
answer_clear           1.0
answer_citations       0.9
completeness           0.9
tool_call_search       1.0
dtype: float64

AI-generated questions:
instructions_follow    1.000000
answer_relevant        0.857143
answer_clear           1.000000
answer_citations       0.857143
completeness           0.857143
tool_call_search       1.000000
dtype: float64

In [136]:
df.mean(numeric_only=True)
#spot fake scores

instructions_follow    1.000000
answer_relevant        0.941176
answer_clear           1.000000
answer_citations       0.882353
completeness           0.882353
tool_call_search       1.000000
dtype: float64

In [137]:
import json
from pathlib import Path

LOG_DIR = Path("logs")
print("Using LOG_DIR:", LOG_DIR.resolve())

log_files = list(LOG_DIR.glob("*.json"))

print("Using:", LOG_DIR)
print("Found:", len(log_files))
print(log_files[:3])

if not log_files:
    raise ValueError("No log files found — wrong path")

with open(log_files[0], "r") as f:
    log = json.load(f)

log

Using LOG_DIR: /workspaces/buidling_AI_agents/aihero/project/notebooks/logs
Using: logs
Found: 17
[PosixPath('logs/binance_agent_v3_v3_20260331_140442_a07462.json'), PosixPath('logs/binance_agent_v3_v3_20260331_141438_f3f81c.json'), PosixPath('logs/binance_agent_v3_v3_20260331_141459_0fab35.json')]

{'agent_name': 'binance_agent_v3',
 'agent_version': 'v3',
 'system_prompt': ['You are a Binance documentation assistant.\n\nRules:\n1. Always call search_docs before answering.\n2. Answer only from retrieved documentation.\n3. If the retrieved context is weak, incomplete, or ambiguous, say so clearly.\n4. Do not guess or invent Binance behavior.\n5. Use the retrieved filename and section in your answer when available.\n\nOnly handle questions about:\n- authentication\n- signed requests\n- timestamps\n- recvWindow\n- market orders\n- limit orders\n- required order parameters\n\nIf the question is outside these areas, say that it is outside the current assistant scope.\n\nAnswer format:\n- Direct answer\n- Key details / parameters\n- Important caveats\n- Source(s): filename / section'],
 'provider': 'openai',
 'model': 'gpt-4o-mini',
 'tools': ['search_docs'],
 'messages': [{'parts': [{'content': 'What parameters are required to create an order?',
     'timestamp': '2026-03-31T14:04:34.791168+00:00',
     'part_kind': 'user-prompt'}],
   'timestamp': '2026-03-31T14:04:34.791341+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nRules:\n1. Always call search_docs before answering.\n2. Answer only from retrieved documentation.\n3. If the retrieved context is weak, incomplete, or ambiguous, say so clearly.\n4. Do not guess or invent Binance behavior.\n5. Use the retrieved filename and section in your answer when available.\n\nOnly handle questions about:\n- authentication\n- signed requests\n- timestamps\n- recvWindow\n- market orders\n- limit orders\n- required order parameters\n\nIf the question is outside these areas, say that it is outside the current assistant scope.\n\nAnswer format:\n- Direct answer\n- Key details / parameters\n- Important caveats\n- Source(s): filename / section',
   'kind': 'request',
   'run_id': '851c6d85-9df4-4a3f-92ae-6ad06084e4fc',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"required order parameters"}',
     'tool_call_id': 'call_eDRPqoCfOiZrmWKcMrfvlH27',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],
   'usage': {'input_tokens': 206,
    'cache_write_tokens': 0,
    'cache_read_tokens': 0,
    'output_tokens': 16,
    'input_audio_tokens': 0,
    'cache_audio_read_tokens': 0,
    'output_audio_tokens': 0,
    'details': {'accepted_prediction_tokens': 0,
     'audio_tokens': 0,
     'reasoning_tokens': 0,
     'rejected_prediction_tokens': 0}},
   'model_name': 'gpt-4o-mini-2024-07-18',
   'timestamp': '2026-03-31T14:04:35.533514+00:00',
   'kind': 'response',
   'provider_name': 'openai',
   'provider_url': 'https://api.openai.com/v1/',
   'provider_details': {'finish_reason': 'tool_calls',
    'timestamp': '2026-03-31T14:04:34+00:00'},
   'provider_response_id': 'chatcmpl-DPTzmSjRs4QhiC0OupGJgQt9UnL3w',
   'finish_reason': 'tool_call',
   'run_id': '851c6d85-9df4-4a3f-92ae-6ad06084e4fc',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'content': 'Result 1\ntitle: \nsection: ## General Information on Endpoints\n\n* For `GET` endpoints, parameters must be sent as a `query string`.\n* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a\n  `query string` or in the `request body` with content type\n  `application/x-www-form-urlencoded`. You may mix parameters between both the\n  `query string` and `request body` if you wish to do so.\n* Parameters may be sent in any order.\n* If a parameter sent in both the `query string` and `request body`, the\n  `query string` parameter will be used.\nfilename: binance-spot-api-docs-master/rest-api.md\ncontent: \n\n\nResult 2\ntitle: \nsection: ## General Information on Endpoints\n\n* For `GET` endpoints, parameters must be sent as a `query string`.\n* For `POST`, `PUT`, and `DELETE` endpoints, the parameters may be sent as a\n  `query string` or in the `request body` with content type\n  `application/x-www-form-urlencoded`. You may mix parameters between both the\n  `query string` and `request body` if you wish to do so.\n* Parameters may be sent in any order.\n* If a parameter sent in both the `query string` and `request body`, the\n  `query string` parameter will be used.\nfilename: binance-spot-api-docs-master/testnet/rest-api.md\ncontent: \n\n\nResult 3\ntitle: \nsection: ## How do canceled or expired orders affect the unfilled order count?\n\nCanceling an order does not change the unfilled order count.\n\nExpired orders also do not change the unfilled order count.\n\n**Example:**\n\n| Time     | Action                         | Unfilled order count |\n|:---------|:-------------------------------|:---------------------|\n| 00:00:00 |                                | 0                    |\n| 00:00:01 | Place LIMIT order A            | 1 — new order (+1)   |\n| 00:00:02 | Cancel order A                 | 1                    |\n| 00:00:02 | Place LIMIT order B            | 2 — new order (+1)   |\n| 00:00:03 | Place LIMIT FOK order C        | 3 — new order (+1)   |\n|          | (order C is fully filled)      | 2 — fill (−1)        |\n| 00:00:05 | Place LIMIT order D            | 3 — new order (+1)   |\n| 00:00:06 | Place LIMIT FOK order E        | 4 — new order (+1)   |\n|          | (order E expires with no fill) | 4                    |\n| 00:00:07 | Cancel order D                 | 4                    |\n| 00:00:07 | Place LIMIT order F            | 5 — new order (+1)   |\nfilename: binance-spot-api-docs-master/faqs/order_count_decrement.md\ncontent: \n\n\nResult 4\ntitle: \nsection: ## How do filled orders affect the unfilled order count?\n\nWhen an order is filled for the first time (partially or fully), your unfilled order count is decremented by one order for all intervals of the `ORDERS` rate limit. Effectively, orders that trade do not count towards the rate limit, allowing efficient traders to keep placing new orders. \n\nCertain orders provide additional incentive:\n\n* **Orders that do not fill immediately (that is, first fill in the maker phase).**   \n* Orders that fill large quantities.\n\nIn these cases the unfilled order count may be decremented by more than one order for each order that starts trading.\n\n**Notes:**\n\n* **The examples only give a general idea of the behavior.** The 10-second interval is used for simplicity. The actual configuration on the live exchange may be different.  \n* There is a short delay between the order being filled and the unfilled order count update. Please be careful when your unfilled order count is close to the limit.  \n* Please refer to [How does unfilled `ORDERS` rate limit work?](#order-rate-limit) to see how you can monitor the unfilled order count depending on the API.\n\n**Example 1** — taker:\n\n| Time     | Action                     | Unfilled order count         |\n|:---------|:---------------------------|:-----------------------------|\n| 00:00:00 |                            | 0                            |\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\n| 00:00:02 | Place LIMIT order B        | 2 — new order (+1)           |\n|          | (order B partially filled) | 1 — first fill as taker (−1) |\n| 00:00:03 | Place LIMIT order C        | 2 — new order (+1)           |\n| 00:00:04 | (order B partially filled) | 2                            |\n| 00:00:04 | (order B filled)           | 2                            |\n| 00:00:05 | Place MARKET order D       | 3 — new order (+1)           |\n|          | (order D fully filled)     | 2 — first fill as taker (−1) |\n\nNote how for every taker order that immediately trades, the unfilled order count is decremented later, allowing you to keep placing orders.\n\n**Example 2** — maker:\n\n| Time     | Action                     | Unfilled order count         |\n|:---------|:---------------------------|:-----------------------------|\n| 00:00:00 |                            | 0                            |\n| 00:00:01 | Place LIMIT order A        | 1 — new order (+1)           |\n| 00:00:01 | Place LIMIT order B        | 2 — new order (+1)           |\n| 00:00:02 | Place LIMIT order C        | 3 — new order (+1)           |\n| 00:00:02 | Place LIMIT order D        | 4 — new order (+1)           |\n| 00:00:02 | Place LIMIT order E        | 5 — new order (+1)           |\n| 00:00:03 | (order A partially filled) | 0 — first fill as maker (−5) |\n| 00:00:04 | Place LIMIT order F        | 1 — new order (+1)           |\n| 00:00:04 | Place LIMIT order G        | 2 — new order (+1)           |\n| 00:00:05 | (order A partially filled) | 2                            |\n| 00:00:05 | (order A filled)           | 2                            |\n| 00:00:05 | (order B partially filled) | 0 — first fill as maker (−5) |\n| 00:00:06 | Place LIMIT order H        | 1 — new order (+1)           |\n\nNote how for every maker order that is filled later, the unfilled order count is decremented by a higher amount, allowing you to place more orders.\nfilename: binance-spot-api-docs-master/faqs/order_count_decrement.md\ncontent: \n\n\nResult 5\ntitle: \nsection: ## 11xx - Request issues\n\n### -1100 ILLEGAL_CHARS\n * Illegal characters found in a parameter.\n * Illegal characters found in parameter \'%s\'; legal range is \'%s\'.\n\n### -1101 TOO_MANY_PARAMETERS\n * Too many parameters sent for this endpoint.\n * Too many parameters; expected \'%s\' and received \'%s\'.\n * Duplicate values for a parameter detected.\n\n### -1102 MANDATORY_PARAM_EMPTY_OR_MALFORMED\n * A mandatory parameter was not sent, was empty/null, or malformed.\n * Mandatory parameter \'%s\' was not sent, was empty/null, or malformed.\n * Param \'%s\' or \'%s\' must be sent, but both were empty/null!\n * Required tag \'%s\' missing.\n * Field value was empty or malformed.\n * \'%s\' contains unexpected value. Cannot be greater than %s.\n\n### -1103 UNKNOWN_PARAM\n * An unknown parameter was sent.\n * Undefined Tag.\n\n### -1104 UNREAD_PARAMETERS\n * Not all sent parameters were read.\n * Not all sent parameters were read; read \'%s\' parameter(s) but was sent \'%s\'.\n\n### -1105 PARAM_EMPTY\n * A parameter was empty.\n * Parameter \'%s\' was empty.\n\n### -1106 PARAM_NOT_REQUIRED\n * A parameter was sent when not required.\n * Parameter \'%s\' sent when not required.\n * A tag \'%s\' was sent when not required.\n\n### -1108 PARAM_OVERFLOW\n * Parameter \'%s\' overflowed.\n\n### -1111 BAD_PRECISION\n * Parameter \'%s\' has too much precision.\n\n### -1112 NO_DEPTH\n * No orders on book for symbol.\n\n### -1114 TIF_NOT_REQUIRED\n * TimeInForce parameter sent when not required.\n\n### -1115 INVALID_TIF\n * Invalid timeInForce.\n\n### -1116 INVALID_ORDER_TYPE\n * Invalid orderType.\n\n### -1117 INVALID_SIDE\n * Invalid side.\n\n### -1118 EMPTY_NEW_CL_ORD_ID\n * New client order ID was empty.\n\n### -1119 EMPTY_ORG_CL_ORD_ID\n * Original client order ID was empty.\n\n### -1120 BAD_INTERVAL\n * Invalid interval.\n\n### -1121 BAD_SYMBOL\n * Invalid symbol.\n\n### -1122 INVALID_SYMBOLSTATUS\n  * Invalid symbolStatus.\n\n### -1125 INVALID_LISTEN_KEY\n * This listenKey does not exist.\n\n### -1127 MORE_THAN_XX_HOURS\n * Lookup interval is too big.\n * More than %s hours between startTime and endTime.\n\n### -1128 OPTIONAL_PARAMS_BAD_COMBO\n * Combination of optional parameters invalid.\n * Combination of optional fields invalid. Recommendation: \'%s\' and \'%s\' must both be sent.\n * Fields [%s] must be sent together or omitted entirely.\n * Invalid `MDEntryType (269)` combination. BID and OFFER must be requested together.\n * Conflicting fields: [\'%s\'...]\n\n### -1130 INVALID_PARAMETER\n * Invalid data sent for a parameter.\n * Data sent for parameter \'%s\' is not valid.\n\n### -1134 BAD_STRATEGY_TYPE\n * `strategyType` was less than 1000000.\n * `TargetStrategy (847)` was less than 1000000.\n\n### -1135 INVALID_JSON\n * Invalid JSON Request\n * JSON sent for parameter \'%s\' is not valid\n\n### -1139 INVALID_TICKER_TYPE\n * Invalid ticker type.\n\n### -1145 INVALID_CANCEL_RESTRICTIONS\n * `cancelRestrictions` has to be either `ONLY_NEW` or `ONLY_PARTIALLY_FILLED`.\n\n### -1151 DUPLICATE_SYMBOLS\n * Symbol is present multiple times in the list.\n\n### -1152 INVALID_SBE_HEADER\n* Invalid `X-MBX-SBE` header; expected `<SCHEMA_ID>:<VERSION>`.\n* Invalid SBE message header.\n\n### -1153 UNSUPPORTED_SCHEMA_ID\n* Unsupported SBE schema ID or version specified in the `X-MBX-SBE` header.\n* Invalid SBE schema ID or version specified.\n\n### -1155 SBE_DISABLED\n* SBE is not enabled.\n\n### -1158 OCO_ORDER_TYPE_REJECTED\n* Order type not supported in OCO.\n* If the order type provided in the `aboveType` and/or `belowType` is not supported.\n\n### -1160 OCO_ICEBERGQTY_TIMEINFORCE\n* Parameter \'%s\' is not supported if `aboveTimeInForce`/`belowTimeInForce` is not GTC.\n* If the order type for the above or below leg is `STOP_LOSS_LIMIT`, and `icebergQty` is provided for that leg, the `timeInForce` has to be `GTC` else it will throw an error.\n* `TimeInForce (59)` must be `GTC (1)` when `MaxFloor (111)` is used.\n\n### -1161 DEPRECATED_SCHEMA\n* Unable to encode the response in SBE schema \'x\'. Please use schema \'y\' or higher.\n\n### -1165 BUY_OCO_LIMIT_MUST_BE_BELOW\n* A limit order in a buy OCO must be below.\n\n### -1166 SELL_OCO_LIMIT_MUST_BE_ABOVE\n* A limit order in a sell OCO must be above.\n\n### -1168 BOTH_OCO_ORDERS_CANNOT_BE_LIMIT\n* At least one OCO order must be contingent.\n\n### -1169 INVALID_TAG_NUMBER\n * Invalid tag number.\n\n### -1170 TAG_NOT_DEFINED_IN_MESSAGE\n * Tag \'%s\' not defined for this message type.\n\n### -1171 TAG_APPEARS_MORE_THAN_ONCE\n * Tag \'%s\' appears more than once.\n\n### -1172 TAG_OUT_OF_ORDER\n * Tag \'%s\' specified out of required order.\n\n### -1173 GROUP_FIELDS_OUT_OF_ORDER\n * Repeating group \'%s\' fields out of order.\n\n### -1174 INVALID_COMPONENT\n * Component \'%s\' is incorrectly populated on \'%s\' order. Recommendation: \'%s\'\n\n### -1175 RESET_SEQ_NUM_SUPPORT\n * Continuation of sequence numbers to new session is currently unsupported. Sequence numbers must be reset for each new session.\n\n### -1176 ALREADY_LOGGED_IN\n * [Logon`<A>`](fix-api.md#logon-main) should only be sent once.\n\n### -1177 GARBLED_MESSAGE\n * `CheckSum(10)` contains an incorrect value.\n * `BeginString (8)` is not the first tag in a message.\n * `MsgType (35)` is not the third tag in a message.\n * `BodyLength (9)` does not contain the correct byte count.\n * Only printable ASCII characters and SOH (Start of Header) are allowed.\n * Tag specified without a value.\n* Invalid encodingType.\n\n### -1178 BAD_SENDER_COMPID\n * `SenderCompId(49)` contains an incorrect value. The SenderCompID value should not change throughout the lifetime of a session.\n\n### -1179 BAD_SEQ_NUM\n * `MsgSeqNum(34)` contains an unexpected value. Expected: \'%d\'.\n\n### -1180 EXPECTED_LOGON\n * [Logon`<A>`](fix-api.md#logon-main) must be the first message in the session.\n\n### -1181 TOO_MANY_MESSAGES\n * Too many messages; current limit is \'%d\' messages per \'%s\'.\n\n### -1182 PARAMS_BAD_COMBO\n * Conflicting fields: [%s]\n\n### -1183 NOT_ALLOWED_IN_DROP_COPY_SESSIONS\n * Requested operation is not allowed in DropCopy sessions.\n\n### -1184 DROP_COPY_SESSION_NOT_ALLOWED\n * DropCopy sessions are not supported on this server. Please reconnect to a drop copy server.\n\n### -1185 DROP_COPY_SESSION_REQUIRED\n * Only DropCopy sessions are supported on this server. Either reconnect to order entry server or send `DropCopyFlag (9406)` field.\n\n### -1186 NOT_ALLOWED_IN_ORDER_ENTRY_SESSIONS\n* Requested operation is not allowed in order entry sessions.\n\n### -1187 NOT_ALLOWED_IN_MARKET_DATA_SESSIONS\n* Requested operation is not allowed in market data sessions.\n\n### -1188 INCORRECT_NUM_IN_GROUP_COUNT\n* Incorrect NumInGroup count for repeating group \'%s\'.\n\n### -1189 DUPLICATE_ENTRIES_IN_A_GROUP\n* Group \'%s\' contains duplicate entries.\n\n### -1190 INVALID_REQUEST_ID\n* `MDReqID (262)` contains a subscription request id that is already in use on this connection.\n* `MDReqID (262)` contains an unsubscription request id that does not match any active subscription.\n\n### -1191 TOO_MANY_SUBSCRIPTIONS\n* Too many subscriptions. Connection may create up to \'%s\' subscriptions at a time.\n* Similar subscription is already active on this connection. Symbol=\'%s\', active subscription id: \'%s\'.\n\n### -1194 INVALID_TIME_UNIT\n* Invalid value for time unit; expected either MICROSECOND or MILLISECOND.\n\n### -1196 BUY_OCO_STOP_LOSS_MUST_BE_ABOVE\n* A stop loss order in a buy OCO must be above.\n\n### -1197 SELL_OCO_STOP_LOSS_MUST_BE_BELOW\n* A stop loss order in a sell OCO must be below.\n\n### -1198 BUY_OCO_TAKE_PROFIT_MUST_BE_BELOW\n* A take profit order in a buy OCO must be below.\n\n### -1199 SELL_OCO_TAKE_PROFIT_MUST_BE_ABOVE\n* A take profit order in a sell OCO must be above.\n\n### -1210 INVALID_PEG_PRICE_TYPE\n* Invalid pegPriceType.\n\n### -1211 INVALID_PEG_OFFSET_TYPE\n* Invalid pegOffsetType.\n\n### -1220 SYMBOL_DOES_NOT_MATCH_STATUS\n* The symbol\'s status does not match the requested symbolStatus.\n\n### -1221 INVALID_SBE_MESSAGE_FIELD\n* Invalid/missing field(s) in SBE message.\n\n### -1222 OPO_WORKING_MUST_BE_BUY\n\n* Working order in an OPO list must be a bid.\n\n### -1223 OPO_PENDING_MUST_BE_SELL\n\n* Pending orders in an OPO list must be asks.\n\n### -1224 WORKING_PARAM_REQUIRED\n\n* Working order must include the \'{param}\' tag.\n\n### -1225 PENDING_PARAM_NOT_REQUIRED\n\n* Pending orders should not include the \'%s\' tag.\n\n### -2010 NEW_ORDER_REJECTED\n * NEW_ORDER_REJECTED\n\n### -2011 CANCEL_REJECTED\n * CANCEL_REJECTED\n\n### -2013 NO_SUCH_ORDER\n * Order does not exist.\n\n### -2014 BAD_API_KEY_FMT\n * API-key format invalid.\n\n### -2015 REJECTED_MBX_KEY\n * Invalid API-key, IP, or permissions for action.\n\n### -2016 NO_TRADING_WINDOW\n * No trading window could be found for the symbol. Try ticker/24hrs instead.\n\n### -2026 ORDER_ARCHIVED\n  * Order was canceled or expired with no executed qty over 90 days ago and has been archived.\n\n### -2035 SUBSCRIPTION_ACTIVE\n  * User Data Stream subscription already active.\n\n### -2036 SUBSCRIPTION_INACTIVE\n  * User Data Stream subscription not active.\n\n### -2039 CLIENT_ORDER_ID_INVALID\n  * Client order ID is not correct for this order ID.\n\n### -2042 MAXIMUM_SUBSCRIPTION_IDS\n* Maximum subscription ID reached for this connection.\n\n<a id="other-errors"></a>\nfilename: binance-spot-api-docs-master/errors.md\ncontent: \n',
     'tool_call_id': 'call_eDRPqoCfOiZrmWKcMrfvlH27',
     'metadata': None,
     'timestamp': '2026-03-31T14:04:35.582810+00:00',
     'outcome': 'success',
     'part_kind': 'tool-return'}],
   'timestamp': '2026-03-31T14:04:35.583267+00:00',
   'instructions': 'You are a Binance documentation assistant.\n\nRules:\n1. Always call search_docs before answering.\n2. Answer only from retrieved documentation.\n3. If the retrieved context is weak, incomplete, or ambiguous, say so clearly.\n4. Do not guess or invent Binance behavior.\n5. Use the retrieved filename and section in your answer when available.\n\nOnly handle questions about:\n- authentication\n- signed requests\n- timestamps\n- recvWindow\n- market orders\n- limit orders\n- required order parameters\n\nIf the question is outside these areas, say that it is outside the current assistant scope.\n\nAnswer format:\n- Direct answer\n- Key details / parameters\n- Important caveats\n- Source(s): filename / section',
   'kind': 'request',
   'run_id': '851c6d85-9df4-4a3f-92ae-6ad06084e4fc',
   'metadata': None},
  {'parts': [{'tool_name': 'search_docs',
     'args': '{"query":"order parameters required"}',
     'tool_call_id': 'call_INUXGe1sPY9A4lU0OkfDGNHM',
     'id': None,
     'provider_name': None,
     'provider_details': None,
     'part_kind': 'tool-call'}],

In [138]:
df["answer_length"] = df["answer"].apply(len)

df_v1 = df[df["agent_version"] == "v1"]
df_v2 = df[df["agent_version"] == "v2"]

print(df_v1["answer_length"].mean())
print(df_v2["answer_length"].mean())

nan
nan

In [139]:
df["source"].value_counts(dropna=False)

source
user            10
ai-generated     7
Name: count, dtype: int64

In [140]:
len(df[df["source"] == "ai-generated"])

7

In [141]:
import json
import random
from pydantic import BaseModel
from pydantic_ai import Agent

In [142]:
class QuestionsList(BaseModel):
    questions: list[str]

In [143]:
question_generation_prompt = """
Generate realistic evaluation questions for a Binance API documentation assistant.

Only generate questions about:
- authentication
- signed requests
- timestamps
- recvWindow
- market orders
- limit orders
- required order parameters

Avoid unrelated areas such as balances, trades, rate limits, exchange info, or account history.

Return one concise, realistic user question per input snippet.
""".strip()

In [144]:
question_generator = Agent(
    name="binance_question_generator",
    instructions=question_generation_prompt,
    model="gpt-4o-mini",
    output_type=QuestionsList,
)

/workspaces/buidling_AI_agents/aihero/project/.venv/lib/python3.12/site-packages/pydantic_ai/models/__init__.py:1280: DeprecationWarning: Specifying a model name without a provider prefix is deprecated. Instead of 'gpt-4o-mini', use 'openai:gpt-4o-mini'.
  provider_name, model_name = parse_model_id(model)

In [145]:
from pathlib import Path
import json
import random

project_root = Path("..")

with open(project_root / "my_chunks_sections.json", "r", encoding="utf-8") as f:
    chunks = json.load(f)

sample = random.sample(chunks, 30)
prompt_docs = [clean_section(d.get("section", "")) for d in sample if d.get("section")]

In [146]:
def clean_section(text: str) -> str:
    if not text:
        return ""
    return text.replace("\n", " ").strip()

sample = random.sample(chunks, 10)

prompt_docs = [
    clean_section(
        d.get("section") or d.get("chunk") or d.get("text") or ""
    )
    for d in sample
]

In [147]:
sample[0]

{'filename': 'binance-spot-api-docs-master/web-socket-api.md',
 'section': '## User Data Stream requests\n\n### User Data Stream subscription\n\n<a id=general_info_user_data_stream_subscriptions></a>\n**General information:**\n\n* [User Data Stream](user-data-stream.md) subscriptions allow you to receive all the events related to a given account on a WebSocket connection.\n* There are 2 ways to start a subscription:\n  * If you have an authenticated session, then you can subscribe to events for that authenticated account using [`userDataStream.subscribe`](#user-data-stream-subscribe).\n  * In any session, authenticated or not, you can subscribe to events for one or more accounts for which you can provide an API Key signature, using [`userDataStream.subscribe.signature`](#user-data-signature).\n  * You can have only one active subscription for a given account on a given connection.\n* Subscriptions are identified by a `subscriptionId` which is returned when starting the subscription. That `subscriptionId` allows you to map the events you receive to a given subscription.\n  * All active subscriptions for a session can be found using [`session.subscriptions`](#session-subscription).\n* Limits\n  * A single session supports **up to 1,000 active subscriptions** simultaneously.\n    * Attempting to start a new subscription beyond this limit will result in an error.\n    * If your accounts are very active, we suggest not opening too many subscriptions at once, in order to not overload your connection.\n  * A single session can handle a maximum of **65,535 total subscriptions** over its lifetime.\n    * If this limit is reached, you will receive an error and must re-establish a new connection to be able to start new subscriptions.\n* To verify the status of User Data Stream subscriptions, check the `userDataStream` field in [`session.status`](#query-session-status):\n  * `null` - User Data Stream subscriptions are **not available** on this WebSocket API.\n  * `true` - There is at **least one subscription active** in this session.\n  * `false` - There are **no active subscriptions** in this session.\n\n<a id="user-data-stream-subscribe"></a>\n\n#### Subscribe to User Data Stream (USER_STREAM)\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "method": "userDataStream.subscribe"\n}\n```\n\nSubscribe to the User Data Stream in the current WebSocket connection.\n\n**Notes:**\n\n* This method requires an authenticated WebSocket connection using Ed25519 keys. Please refer to [`session.logon`](#session-logon).\n* To check the subscription status, use [`session.status`](#session-status), see the `userDataStream` flag indicating you have have an active subscription.\n* User Data Stream events are available in both JSON and [SBE](faqs/sbe_faq.md) sessions.\n  * Please refer to [User Data Streams](user-data-stream.md) for the event format details.\n  * For SBE, only SBE schema 2:1 or later is supported.\n\n**Weight**:\n2\n\n**Parameters**:\nNONE\n\n**Response**:\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "status": 200,\n    "result": {\n        "subscriptionId": 0\n    }\n}\n```\n\n#### Unsubscribe from User Data Stream\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "method": "userDataStream.unsubscribe"\n}\n```\n\nStop listening to the User Data Stream in the current WebSocket connection.\n\nNote that `session.logout` will only close the subscription created with `userDataStream.subscribe` but not subscriptions opened with `userDataStream.subscribe.signature`.\n\n**Weight**:\n2\n\n**Parameters**:\n\n| Name | Type | Mandatory | Description |\n| --- | --- | --- | --- |\n| `subscriptionId` | INT | No | When called with no parameter, this will close all subscriptions. <br>When called with the `subscriptionId` parameter, this will attempt to close the subscription with that subscription id, if it exists. |\n\n**Response**:\n\n```javascript\n{\n    "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",\n    "status": 200,\n    "result": {}\n}\n```\n\n<a id="session-subscription"></a>\n\n#### Listing all subscriptions\n\n```javascript\n{\n    "id": "d3df5a22-88ea-4fe0-9f4e-0fcea5d418b7",\n    "method": "session.subscriptions",\n    "params": {}\n}\n```\n\n**Note:**\n\n* Users are expected to track on their side which subscription corresponds to which account.\n\n**Weight**:\n2\n\n**Data Source**:\nMemory\n\n**Response**:\n\n```javascript\n{\n    "id": "d3df5a22-88ea-4fe0-9f4e-0fcea5d418b7",\n    "status": 200,\n    "result": [\n        {\n            "subscriptionId": 0\n        },\n        {\n            "subscriptionId": 1\n        }\n    ]\n}\n```\n\n<a id="user-data-signature"></a>\n\n#### Subscribe to User Data Stream through signature subscription (USER_STREAM)\n\n```javascript\n{\n    "id": "d3df8a22-98ea-4fe0-9f4e-0fcea5d418b7",\n    "method": "userDataStream.subscribe.signature",\n    "params": {\n        "apiKey": "mjcKCrJzTU6TChLsnPmgnQJJMR616J4yWvdZWDUeXkk6vL6dLyS7rcVOQlADlVjA",\n        "timestamp": 1747385641636,\n        "signature": "yN1vWpXb+qoZ3/dGiFs9vmpNdV7e3FxkA+BstzbezDKwObcijvk/CVkWxIwMCtCJbP270R0OempYwEpS6rDZCQ=="\n    }\n}\n```\n\n**Weight:**\n2\n\n**Parameters**:\n\n| Name | Type | Mandatory | Description |\n| --- | --- | --- | --- |\n| `apiKey` | STRING | Yes |  |\n| `timestamp` | LONG | Yes |  |\n| `signature` | STRING | Yes |  |\n|`recvWindow`|DECIMAL | No|The value cannot be greater than `60000`. <br> Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.|\n\n**Data Source:**\nMemory\n\n**Response:**\n\n```javascript\n{\n    "id": "d3df8a22-98ea-4fe0-9f4e-0fcea5d418b7",\n    "status": 200,\n    "result": {\n        "subscriptionId": 0\n    }\n}\n```'}

In [148]:
def clean_section(text):
    return text.replace("\n", " ").strip()

prompt_docs = [clean_section(d["section"]) for d in sample]

In [149]:
prompt = json.dumps(prompt_docs, ensure_ascii=False)
result = await question_generator.run(prompt)
ai_questions = result.output.questions
ai_questions

['What is the process for creating a signed request with the Binance API?']

In [150]:
for q in ai_questions:
    print(q)

What is the process for creating a signed request with the Binance API?

In [151]:
for q in ai_questions:
    print("\nAI QUESTION:", q)

    result_v3 = await agent_v3.run(q)
    print("\nV3 ANSWER:")
    print(result_v3.output)

    log_file_v3 = log_interaction_to_file(
        agent_v3,
        result_v3.new_messages(),
        source="ai-generated",
        version="v3"
    )

    print("Saved V3:", log_file_v3)

AI QUESTION: What is the process for creating a signed request with the Binance API?

V3 ANSWER:
To create a signed request with the Binance API, follow these steps:

1. **Prepare the Request:**
   - Format the request as a JSON object containing the following fields:
     - `id`: An arbitrary ID to match responses to requests (can be UUID, timestamp, etc.).
     - `method`: The method name for the API call (e.g., `"order.place"`).
     - `params`: The parameters required for the request, should include necessary fields like `symbol`, `side`, `type`, `price`, `quantity`, `timeInForce`, `timestamp`, and `apiKey`.

2. **Add a Timestamp:**
   - Include a `timestamp` parameter that represents the time of the request. This must be in milliseconds.

3. **Generate the Signature:**
   - The `signature` is created by signing the query string of the parameters with your API secret. This signature is then added to the request.

4. **Example of a Signed Request:**
   Here’s how a signed request looks:
   ```json
   {
       "id": "e2a85d9f-07a5-4f94-8d5f-789dc3deb097",
       "method": "order.place",
       "params": {
           "symbol": "BTCUSDT",
           "side": "BUY",
           "type": "LIMIT",
           "price": "0.1",
           "quantity": "10",
           "timeInForce": "GTC",
           "timestamp": 1655716096498,
           "apiKey": "your_api_key",
           "signature": "generated_signature"
       }
   }
   ```

5. **Send the Request:**
   - Send the prepared request to the API endpoint.

**Key Details / Parameters:**
- Ensure the order of parameters in `params` does not affect the signature generation. However, the `timestamp` must be present.
- The API key must be included for authentication.

**Important Caveats:**
- Always send the timestamp in milliseconds.
- The signature must be generated for each request; it is not static.

**Source(s):** binance-spot-api-docs-master/testnet/rest-api.md / Request format
Saved V3: logs/binance_agent_v3_v3_20260331_142446_53b9a9.json

In [152]:
import json
from pathlib import Path
from collections import Counter

sources = []
for f in Path("logs").glob("*.json"):
    with open(f, "r", encoding="utf-8") as infile:
        sources.append(json.load(infile).get("source"))

Counter(sources)

Counter({'user': 10, 'ai-generated': 8})

In [153]:
df["source"].value_counts()

source
user            10
ai-generated     7
Name: count, dtype: int64

In [154]:
df_ai = df[df["source"] == "ai-generated"]
df_ai.mean(numeric_only=True)

instructions_follow       1.000000
answer_relevant           0.857143
answer_clear              1.000000
answer_citations          0.857143
completeness              0.857143
tool_call_search          1.000000
answer_length          1433.571429
dtype: float64

In [155]:
# user questions
df_user = df[df["source"] == "user"]

# AI-generated questions
df_ai = df[df["source"] == "ai-generated"]

# split by version
df_v1 = df[df["agent_version"] == "v1"]
df_v2 = df[df["agent_version"] == "v2"]

In [156]:
print("V1 performance:")
print(df_v1.mean(numeric_only=True))

print("\nV2 performance:")
print(df_v2.mean(numeric_only=True))

V1 performance:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
answer_length         NaN
dtype: float64

V2 performance:
instructions_follow   NaN
answer_relevant       NaN
answer_clear          NaN
answer_citations      NaN
completeness          NaN
tool_call_search      NaN
answer_length         NaN
dtype: float64

In [157]:
print("User questions:")
print(df_user.mean(numeric_only=True))

print("\nAI-generated questions:")
print(df_ai.mean(numeric_only=True))

User questions:
instructions_follow      1.0
answer_relevant          1.0
answer_clear             1.0
answer_citations         0.9
completeness             0.9
tool_call_search         1.0
answer_length          972.8
dtype: float64

AI-generated questions:
instructions_follow       1.000000
answer_relevant           0.857143
answer_clear              1.000000
answer_citations          0.857143
completeness              0.857143
tool_call_search          1.000000
answer_length          1433.571429
dtype: float64

In [158]:
# --- REBUILD EVAL PIPELINE ---

eval_results = []
failed_logs = []

from pathlib import Path

log_files = list(LOG_DIR.glob("*.json"))

print("Total logs found:", len(log_files))

for log_file in log_files:
    try:
        log_record = load_log_file(log_file)
        eval_result = await evaluate_log_record(log_record)
        eval_results.append((log_record, eval_result))
    except Exception as e:
        failed_logs.append((log_file.name, str(e)))

print("Successful evals:", len(eval_results))
print("Failed evals:", len(failed_logs))


# --- BUILD DATAFRAME ---

import pandas as pd

rows = []

for log_record, eval_result in eval_results:
    messages = log_record["messages"]

    row = {
        "file": Path(log_record["log_file"]).name,
        "agent_name": log_record.get("agent_name"),
        "agent_version": log_record.get("agent_version"),
        "source": log_record.get("source"),
        "question": messages[0]["parts"][0]["content"],
        "answer": messages[-1]["parts"][0]["content"],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)

    rows.append(row)

df = pd.DataFrame(rows)

df.to_csv("evaluation_results.csv", index=False)

print("\n--- DISTRIBUTION ---")
print(df["source"].value_counts())
print(df["agent_version"].value_counts())

Total logs found: 18
Successful evals: 18
Failed evals: 0

--- DISTRIBUTION ---
source
user            10
ai-generated     8
Name: count, dtype: int64
agent_version
v3    18
Name: count, dtype: int64